### ISSUE TITLE
Calling C_Sign for size doesn't work

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#133]
Calling C_Sign/C_SignFinal ~~or C_Verify/C_VerifyFinal~~ with  a buffer to small or NULL should result in a CKR_BUFFER_TOO_SMALL|CKR_OK return respectively and the value of the length in the length pointer. 

Currently this fails, correct the behavior so it aligns to the specification, notably covered in section 5.2

**Comment by PeterHuewe** [comment]
Same applies to decrypt btw.

**Comment by williamcroberts** [comment]
@PeterHuewe fixed Encrypt/Decrypt too
