### ISSUE TITLE
Mutual Authentication TLS

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-pkcs11#145]
Is it possible to use in **curl** or **firefox** for **mutual tls**, I need to make requests for my api using tpm?

**Comment by flihp** [comment]
Throwing out a few ideas:
1. Last I tried (years ago) NSS has good PKCS#11 support. Firefox uses NSS so maybe you can configure Firefox to use TPM2 PKCS#11 through NSS?
2. Most distros have a curl package built to use openssl. Should be possible to use TPM2 OpenSSL engine https://github.com/tpm2-software/tpm2-tss-engine to use TPM2 for auth?

**Comment by williamcroberts** [comment]
You should be able to use this project once we have certificate support. Theirs also OpenSC's pkcs11 to OpenSSL engine library you could plug the TPM2 OSSL engine into.
