### ISSUE TITLE
libtool error: only absolute run-paths are allowed

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#146]
Could you fix error below?

libtool:   error: only absolute run-paths are allowed
make: *** [src/libtpm2_pkcs11.la] Error 1

I am following https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/BUILDING.md instructions with latest git clone.

**Comment by williamcroberts** [comment]
I have never seen this error and you're the only one reporting it, can you provide some context?

Have you tried deleting and re-cloning the repo?

**Comment by timdesi** [comment]
I have tried to delete and clone repo again, unfortunately this not work too. Also try with different machine with same error.

I am using CentOS 7 with latest updates.  Also tpm2-tss, tpm2-tools, tpm2-abrmd are latest versions from git.

1. First error comes after execute ./configure ...
ERROR : syntax error near unexpected token `P11_MODULE_PATH`

2. Checking buildserver find that P11KIT is not istalled, so simply patch configure file not to look for P11KIT and continue ... 

3. Running make produce "/usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization" error ... so need to run configure again with disable-hardening param. ./configure --prefix=/usr --disable-hardening

4. Running make again produce "libtool:   error: only absolute run-paths are allowed" error this time.

All terminal outputs are below;

[root@tim tpm2-pkcs11]$ ./bootstrap 
Generating file lists: src_vars.mk
configure.ac:39: installing './compile'
configure.ac:40: installing './config.guess'
configure.ac:40: installing './config.sub'
configure.ac:41: installing './install-sh'
configure.ac:41: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
[root@tim tpm2-pkcs11]$ ./configure --prefix=/usr
checking whether to enable debugging... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking whether to build with code coverage support... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for TSS2_ESYS... yes
checking for TCTI_DEVICE... yes
checking for TCTI_MSSIM... yes
checking for SQLITE3... yes
checking for CRYPTO... yes
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking if LD -Wl,--version-script works... yes
checking for P11KIT... yes
./configure: line 14302: syntax error near unexpected token `P11_MODULE_PATH,'
./configure: line 14302: `  PKG_CHECK_VAR(P11_MODULE_PATH, p11-kit-1, p11_module_path)'

[root@tim tpm2-pkcs11]$ ./configure --prefix=/usr
checking whether to enable debugging... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking whether to build with code coverage support... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for TSS2_ESYS... yes
checking for TCTI_DEVICE... yes
checking for TCTI_MSSIM... yes
checking for SQLITE3... yes
checking for CRYPTO... yes
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking if LD -Wl,--version-script works... yes
checking for P11KIT... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Werror... yes
checking whether C compiler accepts -Wformat... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wstack-protector... yes
checking whether C compiler accepts -fstack-protector-all... yes
checking whether C compiler accepts -Wstrict-overflow=5... yes
checking whether C preprocessor accepts -U_FORTIFY_SOURCE... yes
checking whether C preprocessor accepts -D_FORTIFY_SOURCE=2... yes
checking whether C compiler accepts -fPIC... yes
checking whether the linker accepts -shared... yes
checking whether C compiler accepts -fPIE... yes
checking whether the linker accepts -pie... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking whether C compiler accepts -fdata-sections... yes
checking whether C compiler accepts -ffunction-sections... yes
checking whether the linker accepts -Wl,--gc-sections... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/lib/config.h
config.status: executing libtool commands
config.status: executing depfiles commands

[root@tim tpm2-pkcs11]$ make
  CC       src/pkcs11.lo
In file included from /usr/include/assert.h:36:0,
                 from src/pkcs11.c:6:
/usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
cc1: all warnings being treated as errors
make: *** [src/pkcs11.lo] Error 1

[root@tim tpm2-pkcs11]$ ./configure --prefix=/usr --disable-hardening
checking whether to enable debugging... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking whether to build with code coverage support... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for TSS2_ESYS... yes
checking for TCTI_DEVICE... yes
checking for TCTI_MSSIM... yes
checking for SQLITE3... yes
checking for CRYPTO... yes
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking if LD -Wl,--version-script works... yes
checking for P11KIT... yes
configure: WARNING: Compiling with --disable-hardening is dangerous!
you should consider fixing the configure script compiler flags
and submitting patches upstream!
checking whether C compiler accepts -fdata-sections... yes
checking whether C compiler accepts -ffunction-sections... yes
checking whether the linker accepts -Wl,--gc-sections... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/lib/config.h
config.status: src/lib/config.h is unchanged
config.status: executing libtool commands
config.status: executing depfiles commands
[root@tim tpm2-pkcs11]$ make
  CC       src/pkcs11.lo
  CC       src/lib/db.lo
  CC       src/lib/digest.lo
  CC       src/lib/encrypt.lo
  CC       src/lib/general.lo
  CC       src/lib/key.lo
  CC       src/lib/mutex.lo
  CC       src/lib/object.lo
  CC       src/lib/random.lo
  CC       src/lib/session.lo
  CC       src/lib/session_ctx.lo
  CC       src/lib/session_table.lo
  CC       src/lib/sign.lo
  CC       src/lib/slot.lo
  CC       src/lib/tcti_ldr.lo
  CC       src/lib/token.lo
  CC       src/lib/tpm.lo
  CC       src/lib/twist.lo
  CC       src/lib/utils.lo
  CCLD     src/libtpm2_pkcs11.la
libtool:   error: only absolute run-paths are allowed
make: *** [src/libtpm2_pkcs11.la] Error 1

**Comment by williamcroberts** [comment]
I have no idea. perhaps things are older versions then the rest of the distro's, I did pick this up:
  - https://patchwork.kernel.org/patch/9078971/ 

You don't need P11 kit installed, that command is checking for P11 Kit, and if it's installed using a variable from pkg-config.

**Comment by timdesi** [comment]
Thx. a lot, now it works. Unfortunately it was not easy.

Looks that at Debian distros there is no problems, works as documented with Raspberry Pi, but with CentOS 7 have configuration problems.

1. Need to patch configure.ac for P11-Kit like sample url from previous comment.

2. Need to patch generated Makefile for P11 config and module paths with absolute paths. I don't know why path variables are not seen by Makefile.

https://p11-glue.github.io/p11-glue/p11-kit/manual/devel-paths.html#devel-paths-config

$ pkg-config p11-kit-1 --variable p11_module_configs
/usr/share/p11-kit/modules

$ pkg-config p11-kit-1 --variable p11_module_path
/usr/lib64/pkcs11

**Comment by dilyanpalauzov** [comment]
Perhaps you use an old libtool.

Perhaps debian overrides the default CFLAGS from ”-O2 -g” to something different, therefore the “warning _FORTIFY_SOURCE requires compiling with optimization (-O)”.

Please provide the output of “make V=1”, but not for compiling all the source files, this will be too much, just
* the command used when linking src/libtpm2_pkcs11.la and 
* the command called for compiling src/pkcs11.lo, where the FORTIFY complains come from.

**Comment by timdesi** [comment]
Hi, output from "make V=1" is below. 

[tim@tim tpm2-pkcs11]$ libtool --version
libtool (GNU libtool) 2.4.2
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

[tim@tim tpm2-pkcs11]$ make V=1
depbase=`echo src/pkcs11.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./src/lib    -I./src -I./src/lib -Wall -Wextra -Werror -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wstrict-overflow=5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fPIE    -pthread   -MT src/pkcs11.lo -MD -MP -MF $depbase.Tpo -c -o src/pkcs11.lo src/pkcs11.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src/lib -I./src -I./src/lib -Wall -Wextra -Werror -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wstrict-overflow=5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -pthread -MT src/pkcs11.lo -MD -MP -MF src/.deps/pkcs11.Tpo -c src/pkcs11.c  -fPIC -DPIC -o src/.libs/pkcs11.o
In file included from /usr/include/assert.h:36:0,
                 from src/pkcs11.c:8:
/usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
cc1: all warnings being treated as errors
make: *** [src/pkcs11.lo] Error 1

**Comment by williamcroberts** [comment]
try
`make -j4 EXTRA_CFLAGS=-O2`
or
`./configure --disable-hardening`
and then set what you want in CFLAGS when building. I force a set of what I think are reasonable flags you would want for a hardened build, but it doesn't work with nor tested with every toolchain.

**Comment by williamcroberts** [comment]
I wonder if their some way to tell non-debug builds to optimize...

**Comment by timdesi** [comment]
Thx. both commands are working. 

[tim@tim tpm2-pkcs11]$ make EXTRA_CFLAGS=-O2 V=1
/bin/sh ./libtool  --tag=CC   --mode=link gcc -I./src -I./src/lib -O2    -pthread   -Wl,--version-script=./lib/tpm2-pkcs11.map  -o src/libtpm2_pkcs11.la -rpath  src/pkcs11.lo  src/lib/db.lo src/lib/digest.lo src/lib/encrypt.lo src/lib/general.lo src/lib/key.lo src/lib/mutex.lo src/lib/object.lo src/lib/random.lo src/lib/session.lo src/lib/session_ctx.lo src/lib/session_table.lo src/lib/sign.lo src/lib/slot.lo src/lib/tcti_ldr.lo src/lib/token.lo src/lib/tpm.lo src/lib/twist.lo src/lib/utils.lo  -shared -pie -Wl,-z,relro -Wl,-z,now  -ltss2-esys -ltss2-sys -ltss2-mu   -lsqlite3    -lcrypto   -ltss2-tcti-device -ltss2-mu    -ltss2-tcti-mssim -ltss2-mu   -ldl 
libtool: link: only absolute run-paths are allowed
make: *** [src/libtpm2_pkcs11.la] Error 1

Unfortunately after this error comes other error "libtool: link: only absolute run-paths are allowed".
To solve this i need to patch Makefile 

1. at line 838 
p11libdir =/usr/lib64/pkcs11# $(P11_MODULE_PATH)

2. at line 840
p11configdir =/usr/share/p11-kit/modules# $(P11_CONFIGS_PATH)

**Comment by williamcroberts** [comment]
Can you just post the git diff output as a comment in 3 back-ticked source code block. I think you can add diff just after the backticks to get color coding to work.

I wonder if P11_* stuff is not getting set right. You show that pkg-config is reporting them correctly, I wonder if something wonky is going on with autoconf and CentOS.

**Comment by dilyanpalauzov** [comment]
About “libtool: error: only absolute run-paths are allowed”

My reading of the thread is that upgrading pkg-config does resolve the absolute-path problem.  So the doc/BUILDING.md needs to updated to reflect that there is an optional dependency to P11-KIT-1 and for the bootstrapping process at least pkg-config >= 0.28 needs to be installed.  

About “error: #warning _FORTIFY_SOURCE requires compiling with optimization”

m4/ax_check_enable_debug.m4 calls "AS_IF([test "x${CFLAGS+set}" != "xset"], [CFLAGS=""])", which means that calling ./configure implies CFLAGS="".  In short, AX_CHECK_ENABLE_DEBUG([no]) and add_hardened_define_flag([-D_FORTIFY_SOURCE=2]) in configure.ac are mutually exclusive.

Having CFLAGS="" (from ax_check_enable_debug.m4) after ./configure is non-standard and not necessary.  Users expect that during and after ./configure CFLAGS will be “-O2 -g”.  I propose removing completely AX_CHECK_ENABLE_DEBUG from configure.ac.  Users who understand about compling software, profiling, debug builds, and autoconf are supposed to understand how to tweak CFLAGS when calling configure.  Moreover, users who compile software choose something for CFLAGS and they expect that all software honours these CFLAGS.  So they can decide not to have -Wl,-z,now.

The current configuration has no problems, when CFLAGS is set over CONFIG_SITE and is ./configure is called, but just the pure ./configure fails.

About “I wonder if their some way to tell non-debug builds to optimize...”
“Debug builds” and “optimized builds” are not mutually exclusive.  As a general rule, do not try to be cool by playing with CFLAGS and let this to the one who builds the software set it.  This includes not adding -Wl,-z,relro -Wl,-z,now -Werror -fstack-protector and not removing anything from the default "-O2 -g".

**Comment by timdesi** [comment]
I am closing this issue because latest commits looks that solve most of problems described here.

Problem is at CentOS/RHEL based distributions that use pkg-config below 0.28 and gcc 4.8.5.

To solve problems;

```
1. try to set newer version of gcc.
scl enable devtoolset-7 bash

2. try to install libpjproject-devel
sudo yum install libpjproject-devel

3. try to pkgconf instead of pkg-config
https://github.com/pkgconf/pkgconf
```
