### ISSUE TITLE
dependency on tpm2_encryptdecrypt

### ISSUE THREAD

**Issue by irtimmer** [tpm2-software/tpm2-pkcs11#15]
Currently tpm2-pkcs11 depends on tpm2_encryptdecrypt to be able to support a normal user and a security officer as defined by PKCS#11. However doesn't seem to work on TPMs (see also https://github.com/tpm2-software/tpm2-tools/issues/407 ) based on an older revision like mine. So it would be nice if this dependency could be removed. However I'm not sure what would be an acceptable solutions, as I'm not completely sure how tpm2-pkcs11 works internally:
- make pins optional (less secure, but could also have it own use cases)
- optional only use a single pin (if pins are equal or only user pin is set) directly on the object itself

or are there other ideas on having these two users without the usage of tpm2_encryptdecrypt?

**Comment by williamcroberts** [comment]
We could just use an asymmetric key to wrap a symmetric key and use software based encrypt/decrypt. One more layer of indirection to solve that.

**Comment by williamcroberts** [comment]
I think we just set the seal objects to contain a key rather than an auth for a key in this situation
