### ISSUE TITLE
Using tpm2-pkcs11 as Java security provider (SunPKCS11)

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#156]
I am trying to use libtpm2_pkcs11.so as a security provider for Java.  Is this possible?

Following this https://docs.oracle.com/javase/9/security/pkcs11-reference-guide1.htm#JSSEC-GUID-30E98B63-4910-40A1-A6DD-663EAF466991 documentation.

After initializing store and creating token, keys with tpm2_ptool as documented with samples i am trying to view keystore from java keytool but always get "your keystore contains 0 entries" message. 

[root@tim security]$ keytool -v -keystore NONE -storetype PKCS11 -list
Enter keystore password:  
Keystore type: PKCS11
Keystore provider: SunPKCS11-TPM2

Your keystore contains 0 entries

**Comment by williamcroberts** [comment]
Enable verbose logging, what's the log look like?

**Comment by timdesi** [comment]
I found that "The Java Keystore API simply ignores key pair entries without a certificate. That's why keytool -list ... does not show the entry." https://docs.oracle.com/javase/8/docs/technotes/guides/security/p11guide.html#KeyStoreRestrictions

Looks like we need to implement option/tool to store certificates at db and associate them with private, public keys.

This issue is commented at https://github.com/tpm2-software/tpm2-pkcs11/issues/16 "Add support for certificates at db".

**Comment by williamcroberts** [comment]
This part of your problem has been solved, we still need to fix the other issue and get java tests in place

**Comment by timdesi** [comment]
Thx. @williamcroberts
