### ISSUE TITLE
Add support for CKA_ALWAYS_AUTHENTICATE

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#170]
The p11 engine_pkcs11 for OpenSSL seems to require CKA_ALWAYS_AUTHENTICATE attribute for operations on private keys.
https://github.com/OpenSC/libp11/blob/58230eb4869fad540fab450b79f325ca76d2320e/src/p11_key.c#L334

This is e.g. needed to create CSR with openssl and our pkcs11 provider

**Comment by williamcroberts** [comment]
dup of #169
