### ISSUE TITLE
Add Support for CKU_CONTEXT_SPECIFIC

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#171]
Currentl Login Mechanism does not support CKU_CONTEXT_SPECIFIC which is needed e.g. for re-authentication if CKA_ALWAYS_AUTHENTICATE is set (#170)

**Comment by williamcroberts** [comment]
@PeterHuewe what happens in the case of:
1. a global user C_Login event followed by a login context specific event?
2. a context specific login event prior to the beginning of any multi-part operation?
  a. you need to know what object the context is referring too or is just deferred?

**Comment by williamcroberts** [comment]
@PeterHuewe ^^^

**Comment by PeterHuewe** [comment]
If I understand the spec correctly, the` CKU_CONTEXT_SPECIFIC` **MUST** only be called for re-authentification, i.e. **AFTER** a previous successful `C_Login`. 
This is needed  if `CKA_ALWAYS_AUTHENTICATE` is set.

So to answer your first question: This is the correct, expected flow.
Calling `C_Login(CKU_CONTEXT_SPECIFIC)` without a prior `C_Login(CKU_USER)` or `C_Login(CKU_SO) `does not work. (`C_Login` will return `CKR_OPERATION_NOT_INITIALIZED`)

Second Question:
The spec says: "_Re-authentication occurs by calling C_Login with userType set to CKU_CONTEXT_SPECIFIC immediately after a cryptographic operation using the key has been initiated (e.g. after C_SignInit)_."

So a cryptographic operation must have been initialized first, so that the reference to the object has already been set (e.g. `C_SignInit`). "_In this call [to C_Login], the actual user type is implicitly given by the usage requirements of the active key._ "

Once the re-authentication is successful "t_he user was successfully authenticated and this sets the active key in an authenticated state that lasts until the cryptographic operation has successfully or unsuccessfully been completed (e.g. by C_Sign, C_SignFinal,..)_."
This means that there is NO need to call `C_SignInit `again.

So I read it this way, the correct flow is:
```
C_Login(CKU_USER) -> returns CKR_OK;
C_SignInit () -> returns CKR_USER_NOT_LOGGED_IN ;
C_Login(CKU_CONTEXT_SPECIFIC) -> returns CKR_OK;
C_Sign() -> returns CKR_OK;
```

**Comment by williamcroberts** [comment]
I think I captured this in the PR https://github.com/tpm2-software/tpm2-pkcs11/pull/309
