### ISSUE TITLE
Build Problem Esys_Free not in tss2_esys.h?

### ISSUE THREAD

**Issue by KEZHwMlXV1vFzs6QvY8v5WjX5** [tpm2-software/tpm2-pkcs11#178]
https://github.com/tpm2-software/tpm2-pkcs11/blob/5c4ca5eb1a5d1f9c16d1324eaa704ee3ecde7996/src/lib/tpm.c#L2285

src/lib/tpm.c: In function ‘tpm2_generate_key’:
src/lib/tpm.c:2285:5: error: implicit declaration of function ‘Esys_Free’ [-Werror=implicit-function-declaration]
     Esys_Free(out_pub);                                                                   
     ^~~~~~~~~                                   
cc1: all warnings being treated as errors                  
Makefile:1266: recipe for target 'src/lib/tpm.lo' failed
make: *** [src/lib/tpm.lo] Error 1

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
only true for
tpm2-tss version 2.0.0. I think master has it.
https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_esys.h#L3228

**Comment by williamcroberts** [comment]
You need at least 2.1:
https://github.com/tpm2-software/tpm2-tss/blob/master/CHANGELOG.md#210
