### ISSUE TITLE
Segfault when setting log level

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#179]
When setting loglevel via environment variable, the pkcs11provider segfaults.

```
TPM2_PKCS11_LOG_LEVEL=3  pkcs11-dump info libtpm2_pkcs11.so
Segmentation Fault
```

Reason is https://github.com/tpm2-software/tpm2-pkcs11/blob/master/src/lib/log.h#L34 
-> You cannot assign strings in C.
-> Also returning a pointer on stack is probably not a good idea.
and it's calling itself in a recursive endless loop in case of error.

**Comment by williamcroberts** [comment]
> When setting loglevel via environment variable, the pkcs11provider segfaults.
> 
> ```
> TPM2_PKCS11_LOG_LEVEL=3  pkcs11-dump info libtpm2_pkcs11.so
> Segmentation Fault
> ```
> Reason is https://github.com/tpm2-software/tpm2-pkcs11/blob/master/src/lib/log.h#L34
> -> You cannot assign strings in C.
> -> Also returning a pointer on stack is probably not a good idea.

String literals should be global ro, that's the difference between:
```C
char *x = "foo";
char y[]="foo';
```
But that's really undefined behavior in C, so should mark them static to be clear. Either way, you're PR addresses some issues with this I have wanted to get to.

> and it's calling itself in a recursive endless loop in case of error.

That's likely the cause of the segfault.
