### ISSUE TITLE
mechanism: support proper mechanism querying

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#198]
- [x] slot_mechanism_info_get: doesn't actually return correct information to what the tpm can support.
- [ ] slot_mechanism_list_get: doesn't actually query the TPM for supported mechanisms.

**Comment by PeterHuewe** [comment]
I think we already covered the first part :)

**Comment by williamcroberts** [comment]
Seems fixed in: f5275084896ba
