### ISSUE TITLE
Calling C_Sign for size doesn't work reliably for ECDSA

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#201]
Although the basic functionality was implemented/fixed in #133, as per discussion in
https://github.com/PeterHuewe/tpm2-pkcs11/commit/7f5f858581105a17b71f77cdd251b1137032563a
there are cases, where the returned size does not match the length of the signature.

So by calling C_Sign for size might return something like 34+34+2 = 71 bytes,
whereas the real signature is then 35+34+2 bytes.

The ASN1 Encoding of a ECDSA Signature is:
```
SEQUENCE (2 elem)
  INTEGER R 
  INTEGER S
```

If either INTEGER R or S have the highest bit set, an additional `00` byte is prepended in order to ensure a positive number.
(See https://docs.microsoft.com/de-de/windows/desktop/SecCertEnroll/about-integer for explanation).

So the size might change between two calls, which causes the signature operation to fail.

Possible solutions:
* Store the signature already in the first call for size and just return it once a suitable buffer is allocated.
* just add two bytes to the returned required buffer size
* add the leading 00 consistently to the integers

The latter also might be helpful for some applications which expect to have R and S of equal size.

**Comment by williamcroberts** [comment]
just take ((keysize in bytes + hdr + extra) * 2) + seqhdr;

((32 + 2 + 1) * 2) + 2 = 72

Wouldn't that work? Then we don't have to go through the headache of caching and computing off of cache?

**Comment by PeterHuewe** [comment]
Yes - that's the second option.
Would work for me.

**Comment by PeterHuewe** [comment]
Unfortunately the fix does not work in all cases, i.e. if `opdata->do_hash` is set to false i.e. for 'raw' ECDSA (without SHA1)
