### ISSUE TITLE
Add CKA_MODULUS to private keys

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#203]
With the latest changes the CKA_MODULUS attribute was dropped for private keys.
However according to 4.9.1 RSA private key objects they need to have this attribute and others set.

**Comment by williamcroberts** [comment]
Oh crud I missed that, 2.1.3:
http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cos01/pkcs11-curr-v2.40-cos01.html
