### ISSUE TITLE
--disable-hardening in docker script removes gcc warning flags for travis ci

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-pkcs11#211]
The gcc warning flags (`-Wall`, `-Wextra`, `-Werror`, `-Wformat`, ...) are enabled by default and can be switched off using the configure switch `--disable-hardening`. In the docker script for travis, these flags are turnt off for both clang and gcc. As a result, travis does not consider these warnings and may succeed even though there is e.g. an unused function which breaks the standard `./bootstrap`, `./configure`, `make` procedure.

This is what happened with 2308f248 where a gcc warning (error due to `-Werror`) was introduced and not detected by travis.

I suggest removing `--disable-hardening` both [for clang](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/.ci/docker.run#L26) and [for gcc](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/.ci/docker.run#L49).

**Comment by williamcroberts** [comment]
Just gcc should have those enabled. Clang build uses ASAN and needs those disabled.

**Comment by joholl** [comment]
Frankly, I'm not familiar with ASAN. Having the flags enabled for gcc is vital, however.

**Comment by williamcroberts** [comment]
> Frankly, I'm not familiar with ASAN. Having the flags enabled for gcc is vital, however.
> 
> Edit: Travis should at least test the standard `./bootstrap`, `./configure`, `make` procedure under default circumstances.

It was supposed to, looks like my conditional checks on CC == gcc fail, because CC is usually empty implying gcc AFAICT.

**Comment by joholl** [comment]
Your commit fixes the issue I described above. However, I think we missed the test code. The latest change ensures that the following lines are executed for `gcc`:

```bash
    ./configure --enable-esapi-session-manage-flags
    make distcheck
    make distclean
```

As a result, warnings (e.g. `-Werror=unused-function`) in the productive code are detected. The tests however are not built since `--enable-unit` and `--enable-integration` are not passed. This means warnings in the test code remain undetected.

Later, the tests are built with `--disable-hardening`. Hence warnings in the test code still remain undetected:

```bash
../configure --enable-unit --enable-integration --enable-esapi-session-manage-flags --disable-hardening --enable-code-coverage
make -j$(nproc)
make -j check
```

This can lead to travis accepting commits that break the build instructions: `./bootstrap; configure --enable-unit --enable-integretion; make check`
