### ISSUE TITLE
Set (initial) version number

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#224]
In https://github.com/tpm2-software/tpm2-pkcs11/blob/master/configure.ac#L29 we currently set the version number by using the command: `git describe --tags --always --dirty` which is a nice way to set it.

However, since we do not have any tags yet, `VERSION` gets set to only the commit id (and maybe `-dirty` appended). Thus the `dash-version` logic in https://github.com/tpm2-software/tpm2-pkcs11/blob/master/configure.ac#L36 does not trigger (see #218).

Moreover the library call C_GetInfo cannot determine the correct version in https://github.com/tpm2-software/tpm2-pkcs11/blob/master/src/lib/general.c#L42 from the build number, as it does not yet follow any scheme that would fit the pkcs11 spec (`CK_VERSION` `MM.mm`). 

I would suggest we create an initial 0.x tag or hard-set it to a a 0.9-dev version in configure.ac.

Whether we want to indicate '-dev' or '-dirty' somehow in the library description, is open for discussion,

**Comment by williamcroberts** [comment]
Id rather see the issues that are open to get us to release get fixed and then I can just legitimately tag it.

**Comment by williamcroberts** [comment]
Im going to do as yo suggest, ill throw a tag at 0.1 to make sure everything is working, and we can set the library version number here: https://github.com/tpm2-software/tpm2-pkcs11/blob/master/src/lib/general.c#L41
