### ISSUE TITLE
Support CKA_DERIVE

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#242]
If CKA_DERIVE is specified in the public key template, we fail at multiple occurences in the code.(e.g. deep_copy_attr_handlers and tpm_handlers).

**Comment by williamcroberts** [comment]
Isn't that correct, we don't nor can we, support this in the current model. Don't we need access to the key material?

**Comment by PeterHuewe** [comment]
Yes. We cannot support derzeit ve=true.
But we must not fail if derive=false is specified.

**Comment by williamcroberts** [comment]
> Yes. We cannot support derzeit ve=true.
> But we must not fail if derive=false is specified.

Oh good point, totally agree.

**Comment by williamcroberts** [comment]
@PeterHuewe this looks fixed in391d6210dba37, is this still an issue for you?

**Comment by williamcroberts** [comment]
Ahh wasn't fully there though...in progress
