### ISSUE TITLE
tpm2_ptool addkey: Add support to specify mgf/hashalg for oaep

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#249]
Currently any key created using tpm2_ptool addkey has for the OEAP mechanism parameters                     `"hashalg": CKM_SHA256 `and `"mgf": CKG_MGF1_SHA256` set.

However there are use cases where I need hashalg and mgf to be set to SHA_1.

-> Add support to select this as an option.

**Comment by PeterHuewe** [comment]
@williamcroberts  Alternatively, we could just remove the call to `object_CKM_RSA_PKCS_OAEP_params_supported` in _object.c_ 
This would work for me as well.

**Comment by williamcroberts** [comment]
Just populate the mechanism with another entry for sha1. The whole idea is to make things simple, you would just have a cache of all supported mechanisms in the db in a list, find a match, and everything should be ok. This way we don't have to query the TPM for everything which, as we know, is super slow.

**Comment by PeterHuewe** [comment]
I don't think ptool (or the db) can currently handle multiple values for the same keys (correct?)

**Comment by williamcroberts** [comment]
It should be able to, or at least that was the intent. IIRC their's no checking performed on that textual array outside of it being syntactically correct. The values are just used as is and populate the array.

**Comment by PeterHuewe** [comment]
If I add the values as an yaml array, I get the array as yaml into the db.
Do we want this?

A regular entry looks like this:
```
3=
9=hashalg=592,mgf=2
1=
```

If I specify it as an array, to accomodate two values:
```
--- a/tools/tpm2_pkcs11/commandlets_keys.py
+++ b/tools/tpm2_pkcs11/commandlets_keys.py
@@ -129,10 +129,15 @@ class NewKeyCommandBase(Command):
 
             pubmech = [
                 { CKM_RSA_X_509: "" },
-                { CKM_RSA_PKCS_OAEP: {
-                    "hashalg": CKM_SHA256,
-                    "mgf": CKG_MGF1_SHA256
-                  }
+                { CKM_RSA_PKCS_OAEP:
+                    [{
+                        "hashalg": CKM_SHA_1,
+                        "mgf": CKG_MGF1_SHA1
+                    },
+                    {
+                        "hashalg": CKM_SHA256,
+                        "mgf": CKG_MGF1_SHA256
+                    }]
                 },
                 { CKM_RSA_PKCS: "" }
             ]
diff --git a/tools/tpm2_pkcs11/pkcs11t.py b/tools/tpm2_pkcs11/pkcs11t.py
index a462e5e..dd21472 100644
--- a/tools/tpm2_pkcs11/pkcs11t.py
+++ b/tools/tpm2_pkcs11/pkcs11t.py
@@ -16,6 +16,8 @@ CKM_RSA_PKCS_OAEP = 9
 CKM_AES_CBC = 0x1082
 CKM_ECDSA = 0x1041
 
+CKM_SHA_1 = 0x220
+CKG_MGF1_SHA1 = 0x1
 CKM_SHA256 = 0x250
 CKG_MGF1_SHA256 = 0x2
```

The entry looks like this:
```
3=
9=[{'hashalg': 544, 'mgf': 1}, {'hashalg': 592, 'mgf': 2}]
1=
```

Which then means adding a new parser to the db.c logic, to handle yaml structures.

**Comment by williamcroberts** [comment]
No dup the whole thing:
```yaml
[
{ CKM_RSA_PKCS_OAEP: {
    "hashalg": CKM_SHA1,
    "mgf": CKG_MGF1_SHA256
}
{ CKM_RSA_PKCS_OAEP: {
    "hashalg": CKM_SHA256,
    "mgf": CKG_MGF1_SHA256
}
]
```

**Comment by williamcroberts** [comment]
The existing parser should handle that....

**Comment by PeterHuewe** [comment]
This might have been easier than expected. thanks bill.
