### ISSUE TITLE
tpm2_getcap: invalid option -- 'c'\n") when doing tpm2_ptool.py addtoken

### ISSUE THREAD

**Issue by xnandersson** [tpm2-software/tpm2-pkcs11#271]
Hi,

Was doing the tpm2-pkcs11 for SSH auth tutorial from FOSDEM and ran into:

tpm2_getcap: invalid option -- 'c'\n")

..when I did the tpm2_ptool.py addtoken thing.

Seems like the "-c" option is deprecated in newer version of tpm2-tools. Now the capabilities is the only paramater, so -c is superfluous.

Suggested fix:

lineno:161 in https://github.com/tpm2-software/tpm2-pkcs11/blob/master/tools/tpm2_pkcs11/tpm2.py

replace:
 cmd = ['tpm2_getcap', '-c', cap]
with:
 cmd = ['tpm2_getcap', cap]

Using: tool="tpm2_getcap" version="3.0.2-1325-g934328fb" tctis="dynamic" tcti-default=tabrmd dlclose=enabled

That did the trick for me.

Regards,
Niklas

**Comment by joholl** [comment]
Thank you for pointing this out! In fact I already created a PR (#270). Once it is merged, there should be no more problems with changed options.

**Comment by xnandersson** [comment]
Thanks a lot! Had a look at your PR. Looks like quite a few changes has been made :-) Good stuff.

**Comment by williamcroberts** [comment]
Fixed: ada9bb7789b
