### ISSUE TITLE
RuntimeError: ('Could not execute tpm2_encryptdecrypt: %s', "tpm2_encryptdecrypt: invalid option -- 'D'\n")

### ISSUE THREAD

**Issue by xnandersson** [tpm2-software/tpm2-pkcs11#272]
Looks like in newer version of tpm2_encryptdecrypt. The flag to indicate decryption is no longer uppercase 'D', but instead lowercase 'd'.

Using version: tool="tpm2_encryptdecrypt" version="3.0.2-1325-g934328fb" tctis="dynamic" tcti-default=tabrmd dlclose=enabled

..so when I did the tpm2_ptool.py addkey --algorithm=ecc384 --label=mylabel --userpin=myuserpin

I got an: "RuntimeError: ('Could not execute tpm2_encryptdecrypt: %s', "tpm2_encryptdecrypt: invalid option -- 'D'\n")"

changing from:

cmd.extend(['-D'])

..to..

cmd.extend(['-d'])

on lineno 103 in tools/tpm2_pkcs11/tpm2.py made it work with tpm2-tools master branch.

Regards,
Niklas

**Comment by joholl** [comment]
As with #271: You're totally right, the `tpm2-tools` we updated just recently. This will be fixed with PR #270.
