### ISSUE TITLE
FYI: ssh-keygen fails with "C_GetAttributeValue failed: 18" (fix released)

### ISSUE THREAD

**Issue by xnandersson** [tpm2-software/tpm2-pkcs11#273]
I ran into the issue when doing the:

ssh-keygen -D ./src/.libs/libtpm2_pkcs11.so | tee my.pub
C_GetAttributeValue failed: 18
cannot read public key from pkcs11

Just for information. This issue is not related to tpm2_pkcs11, but is a bug in openssh that is fixed in the most current version V_8_0_P1 (https://github.com/openssh/openssh-portable/archive/V_8_0_P1.tar.gz)

To configure openssh you just download the source and run:

autoreconf
./configure
make
make install

**Comment by xnandersson** [comment]
Supposedly this is the fix. Interesting thread https://bugzilla.mindrot.org/show_bug.cgi?id=2474

**Comment by xnandersson** [comment]
Closing this as not related to tpm2-pkcs11, but still interesting for the records.

**Comment by williamcroberts** [comment]
Good info, thank you.
