### ISSUE TITLE
ci: travis does not detect warnings/errors in tests

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-pkcs11#281]
Note: this issue applies to pkcs11 as well as tpm2-software/tpm2-tools. (see tpm2-software/tpm2-tools#1683)

As discussed in #211, if travis builds the code with `--disable-hardening`, most gcc warnings will be disabled. With #279, this issue was fixed for the productive code, but not for the tests.

I created a pull request tpm2-software/tpm2-tools#1682 with a demo: an unused function is introduced and accepted by travis which breaks a standard way of building: `./bootstrap; configure --enable-unit --enable-integration; make check`

**Explanation why the travis misses the error:**

For gcc we execute the following lines:

```bash
    ./configure --enable-esapi-session-manage-flags
    make distcheck
    make distclean
```

As a result, warnings (e.g. `-Werror=unused-function`) in the productive code are detected. The tests however are not built since `--enable-unit` and `--enable-integration` are not passed. This means warnings in the test code remain undetected.

Later, the tests are built with `--disable-hardening`. Hence warnings in the test code still remain undetected:

```bash
../configure --enable-unit --enable-integration --enable-esapi-session-manage-flags --disable-hardening --enable-code-coverage
make -j$(nproc)
make -j check
```

**Comment by williamcroberts** [comment]
fixed 91c376bd4
