### ISSUE TITLE
Allow for configuration via config file

### ISSUE THREAD

**Issue by reanimus** [tpm2-software/tpm2-pkcs11#297]
Currently, the only way to configure the various options for the module are via the environment. This works for most scenarios, but for mine, this breaks. I use the gnome keyring daemon to handle SSH keys, and ideally I'd like to use it to handle my TPM keys as well. However, because the PAM module launches it in a way that doesn't include the environment declared in `/etc/environment.d`, it doesn't load the TCTI configuration correctly. As a result, the module fails to initialize. To work around this for the time being, I've simply patched my local build to fall back to the TCTI setting I normally use. However, as a longer-term solution, it'd be nice to be able to set this (and other stuff, like error level) in a configuration file.

**Comment by wzrdtales** [comment]
@reanimus how did you do an integration with the gnome keyring?

**Comment by reanimus** [comment]
@wzrdtales GNOME keyring (in most distributions) has SSH agent support built in. From there, it's not much different from regular usage. You run `ssh-add` and provide the PKCS11 module to it.

For my usage, I have a script and an associated desktop shortcut to graphically ask for the PIN and add it to the keyring:

```
#!/bin/bash
GDK_BACKEND=x11 SSH_ASKPASS=/usr/lib/seahorse/ssh-askpass ssh-add -s /lib64/pkcs11/libtpm2_pkcs11.so
```

The `GDK_BACKEND` bit is a bit system-specific and mainly for convenience (I use Wayland, and if I let it use the Wayland backend for some reason it won't grab focus and let me immediately begin inputting the PIN. If I use the X11 backend, the scaling isn't as clean looking but the focus is immediately grabbed. Convenience over prettiness!)
