### ISSUE TITLE
C_Initialize 224

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-pkcs11#319]
Here's what I'm getting at the terminal:

```
ssh-keygen -D libtpm2_pkcs11.so
C_Initialize for provider libtpm2_pkcs11.so failed: 224
cannot read public key from pkcs11
```

Any idea where I'd even start troubleshooting this?

**Comment by williamcroberts** [comment]
Increase logging:
```bash
export TPM2_PKCS11_LOG_LEVEL=2
```

Did you export the store?
```bash
TPM2_PKCS11_STORE=/path/to/store
```
Are you following this?
https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/SSH.md

**Comment by williamcroberts** [comment]
Closed no updates
