### ISSUE TITLE
tpm2_ptool addcert error

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#331]
Hi, i am testing addcert functionality, at final step i have error below;

`./tpm2_ptool addcert --label=test1 --key-label=rsakey1 rsakey1cert.pem
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 29, in <module>
    main()
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 25, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 84, in init
    commandlet.get()[d['which']](d)
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_keys.py", line 603, in __call__
    id = AddCert.get_id_by_label(t, keylabel)
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_keys.py", line 622, in get_id_by_label
    attrs = list_dict_from_kvp(tobj['attrs'])
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/utils.py", line 49, in list_dict_from_kvp
    return [ dict_from_kvp(x) for x in lines.split("\n") ]
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/utils.py", line 49, in <listcomp>
    return [ dict_from_kvp(x) for x in lines.split("\n") ]
  File "/prgs/tpm2_test1/tpm2-pkcs11/tools/tpm2_pkcs11/utils.py", line 46, in dict_from_kvp
    return dict(x.split('=') for x in kvp.split('\t '))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
`
More informatin;
1. python -V
Python 3.6.8

2. `cat rsakey1cert.pem 
-----BEGIN CERTIFICATE-----
MIIBmTCCAQICCQD7zwpHIIYtPzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZt
eSBrZXkwHhcNMTkxMTI4MTI1MDMwWhcNMjAxMTI3MTI1MDMwWjARMQ8wDQYDVQQD
DAZteSBrZXkwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOYQBrcAAT5sDSQ5
VGGW45H/+q9cMqAcZTdW4EuBd1Jzq67YUiDvGozGtA6HRvOl0Oo5IkQBj3iOIjWC
im/4mwcLI1nmteGF1I7RCTSZuiTux4sMHPeirN3CkhSy0jHFGkygEZHvYJcQsQxv
xkwfIttyQ2tIVfPrDdJeqjdCs6TrAgMBAAEwDQYJKoZIhvcNAQELBQADgYEAOlQw
RAm4wRsCsYw4y5Nc0Gs0wQSnRXV6lgM/xili2ZQmy0tZ63VjIT+enddhAua9YZb4
Z8M/qJTj8aiWXpaC2PWRl3H8n7NKpxq0rFWQZAn47kMn7XuJopURCO6rUTR1Tmi8
ZvOyKZT6B0iPKCsU+vEAjqirWxrE29dQkB5DNco=
-----END CERTIFICATE-----
`
3. pkcs11-tool --module /usr/lib64/pkcs11/libtpm2_pkcs11.so --slot 1 --login -O 

Private Key Object; RSA 
  label:      rsakey1
  ID:         31653230653439666263373436326462
  Usage:      decrypt, sign
Public Key Object; RSA 1024 bits
  label:      rsakey1
  ID:         31653230653439666263373436326462
  Usage:      encrypt, verify

4. Test with python 2.7 also but error is same.

Thx.

**Comment by williamcroberts** [comment]
No idea. Works for both my python 2 and 3 versions using your pem file.
```bash
$ python3 --version
Python 3.6.8
```
```bash
export TPM2_PKCS11_STORE=$HOME/tmp
PYTHON_INTERPRETER=python3 tpm2_ptool addcert --label=label --key-label=12 --path=$TPM2_PKCS11_STORE ~/pem
Added cert as label: "12"
```
```
-----BEGIN CERTIFICATE-----
MIIBmTCCAQICCQD7zwpHIIYtPzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZt
eSBrZXkwHhcNMTkxMTI4MTI1MDMwWhcNMjAxMTI3MTI1MDMwWjARMQ8wDQYDVQQD
DAZteSBrZXkwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOYQBrcAAT5sDSQ5
VGGW45H/+q9cMqAcZTdW4EuBd1Jzq67YUiDvGozGtA6HRvOl0Oo5IkQBj3iOIjWC
im/4mwcLI1nmteGF1I7RCTSZuiTux4sMHPeirN3CkhSy0jHFGkygEZHvYJcQsQxv
xkwfIttyQ2tIVfPrDdJeqjdCs6TrAgMBAAEwDQYJKoZIhvcNAQELBQADgYEAOlQw
RAm4wRsCsYw4y5Nc0Gs0wQSnRXV6lgM/xili2ZQmy0tZ63VjIT+enddhAua9YZb4
Z8M/qJTj8aiWXpaC2PWRl3H8n7NKpxq0rFWQZAn47kMn7XuJopURCO6rUTR1Tmi8
ZvOyKZT6B0iPKCsU+vEAjqirWxrE29dQkB5DNco=
-----END CERTIFICATE-----
```

**Comment by timdesi** [comment]
I have destroyed current token and recreate it with tpm_ptools and everything works us expected. Looks like i mess up something with generating keys. Thx.
