### ISSUE TITLE
C_SignInit fails for: CKM_RSA_X_509

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#335]
See this thread:
  - https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/AYUBCAFCCXITEVSWA4IFC466LYS6ZIYX/

But we should be  able to reproduce this by adding a test for CKM_RSA_X_509

**Comment by dwmw2** [comment]
There are PKCS#11 integration tests in OpenConnect, which may also be worthwhile using as a test. Or you could use `gnutls-cli` and `openssl s_client  -engine pkcs11` to get testing within the crypto library as part of TLS negotiations.

**Comment by williamcroberts** [comment]
FYI This fails as it should. To use raw rsa go through the C_Encrypt and C_Decrypt interface:
See http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html section 2.1.12. Private key operations are decrypt/unwrap/sign. Public key operations are encrypt/wrap/verify/verify-recover.

**Comment by ijaureguiberry** [comment]
I've added two scripts to reproduce the issue, created a pull request with that. It uses openssl s_server and s_client as suggested by David.

I was reading William comment on failing as supposed to. Do you mean that openssl is using PKCS11 wrong, or that the entire use case is invalid? I'm confused on what that comment actually means.

**Comment by dwmw2** [comment]
Note that OpenSSL doesn't use PKCS#11 directly. There is a PKCS#11 engine.

There is also a *second* implementation of PKCS#11 for OpenSSL in https://github.com/openssl/openssl/pull/8200 which is also worth testing with. If either are Doing It Wrong™ then we should tell them.

**Comment by ijaureguiberry** [comment]
I briefly checked the sources here https://github.com/opensignature/openssl/blob/37d2f71125adae765962b4c9feef2552db8f5c1b/engines/e_pkcs11.c#L62 and it seems it is using a supported mechanism.
I wasn't able to test it tough, as this new engine has been created on top of version 3 of openssl, and when it tries using tpm2-pkcs11, this one uses tpm2-tss that builds against openssl-1.1. tpm2-tss doesn't build against openssl-3, deprecation warnings.

**Comment by williamcroberts** [comment]
> doesn't build against openssl-3, deprecation warnings.

I didn't even know there was an openssl-3. We should probably look at making sure we have support throughout all the projects for that.

**Comment by williamcroberts** [comment]
Looks like it's asking for CKM_RSA_PKCS_PSS but the key object is saying CKR_MECHANISM_INAVLID. This should just be a matter of adding it to the objects list of supported mechanisms if the token supports it.

**Comment by williamcroberts** [comment]
Closed the wrong thing
