### ISSUE TITLE
Could you add CK_KEY_TYPE cert_type = CKC_X_509 attribute if its missing?

### ISSUE THREAD

**Issue by timdesi** [tpm2-software/tpm2-pkcs11#337]
I am testing latest version of library from Java 13 with SunPKCS11Provider.

Java PKCS11 Provider send atributes below to C_FindObjectsInit function.
   [0]	CK_ATTRIBUTE	CKA_TOKEN = true	
   [1]	CK_ATTRIBUTE	CKA_CLASS = CKO_CERTIFICATE

Problem is that provider could not find cert object.

If i add CK_KEY_TYPE cert_type = CKC_X_509 to attributes everything works us expected. 

Found this from integration test, pkcs-crypt.int.c file.

  CK_OBJECT_CLASS obj_class = CKO_CERTIFICATE;
  CK_KEY_TYPE cert_type = CKC_X_509;
  CK_ATTRIBUTE tmpl[] = {
      { CKA_CLASS, &obj_class, sizeof(obj_class)  },
      { CKA_CERTIFICATE_TYPE, &cert_type, sizeof(cert_type) },
};

![Screenshot from 2019-12-03 14-58-59](https://user-images.githubusercontent.com/36303267/70053206-9a5d8f80-15dd-11ea-963a-d8aff747cd6e.png)

![Screenshot from 2019-12-03 13-55-23](https://user-images.githubusercontent.com/36303267/70052861-e1975080-15dc-11ea-8897-f23cb1231284.png)

**Comment by williamcroberts** [comment]
I'm revamping the whole attribute internals, so this should correct that issue as I add it. Glad to know it's loading in Java, that was on my todo list.

**Comment by williamcroberts** [comment]
Should be fixed in:
https://github.com/tpm2-software/tpm2-pkcs11/pull/344

**Comment by timdesi** [comment]
I have checked with #344 and looks Fixed.
