### ISSUE TITLE
Unclear licensing of OASIS PKCS#11 header files

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-pkcs11#338]
As documented in the [LICENSE file](https://github.com/tpm2-software/tpm2-pkcs11/blob/049c596379ced0ce15c5fcc0d0dd55aa9001ad4a/LICENSE#L32-L35), the header files [`src/pkcs11.h`](https://github.com/tpm2-software/tpm2-pkcs11/blob/049c596379ced0ce15c5fcc0d0dd55aa9001ad4a/src/pkcs11.h), [`src/lib/pkcs11f.h`](https://github.com/tpm2-software/tpm2-pkcs11/blob/049c596379ced0ce15c5fcc0d0dd55aa9001ad4a/src/lib/pkcs11f.h) and [`src/lib/pkcs11t.h`](https://github.com/tpm2-software/tpm2-pkcs11/blob/049c596379ced0ce15c5fcc0d0dd55aa9001ad4a/src/lib/pkcs11t.h) have their own licenses:
```
/* Copyright (c) OASIS Open 2016. All Rights Reserved./
 * /Distributed under the terms of the OASIS IPR Policy,
 * [http://www.oasis-open.org/policies-guidelines/ipr], AS-IS, WITHOUT ANY
 * IMPLIED OR EXPRESS WARRANTY; there is no warranty of MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE or NONINFRINGEMENT of the rights of others.
 */
```
```
/*
 * Copyright (C) OASIS Open 2014.  All rights reserved.
 * OASIS trademark, IPR and other policies apply.
 * http://www.oasis-open.org/policies-guidelines/ipr
 */
```
Unfortunately it is not clear what the "terms of the OASIS IPR Policy" actually are. Upstream has [some more information](https://github.com/oasis-tcs/pkcs11/blob/b544ea6da7fabd0959134532d31124d3351c5ff3/LICENSE.md), but it still could not find out whether these files can be freely modified or distributed. This will create problems for distributions intent on packaging tpm2-pkcs11 because it is unclear whether it is legal to distribute compiled binaries that use these headers, see e.g. this [Fedora mailing list thread](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/2QXHMTZ47DMMARJVI6PUMSYUPVFAGLCV/). Other projects like AAF [have switched to PKCS#11 header files with more clear licensing terms](https://jira.onap.org/browse/AAF-594) for this reason.

I noticed tpm2-pkcs11 used to use a different [`pkcs11.h`](https://github.com/tpm2-software/tpm2-pkcs11/blob/48c26c5e1522b68dfc47621a68ef5577c0737952/src/pkcs11.h) licensed under the [FSF Unlimited License](https://spdx.org/licenses/FSFULLR.html). This was changed in https://github.com/tpm2-software/tpm2-pkcs11/pull/72; would it be an option to revert this PR and go back to using the freely licensed header files?

**Comment by williamcroberts** [comment]
Not reading the Fedora thread, but Section 14.1 of the IPR makes it clear:
"distributed, in whole or in part, without restriction of any kind".

https://www.oasis-open.org/policies-guidelines/ipr

**Comment by diabonas** [comment]
I guess the problem is that this policy states "Any OASIS Deliverable shall include the following notices", but the header files don't actually do that, so it's not clear whether the license actually applies to them. Anyway, that's an upstream problem, I'm  now sufficiently convinced that these headers are intended to be able to be freely distributed. Thank you for digging this up!

**Comment by williamcroberts** [comment]
@diabonas the headers have the notice:
```C
/* Copyright (c) OASIS Open 2016. All Rights Reserved./
 * /Distributed under the terms of the OASIS IPR Policy,
 * [http://www.oasis-open.org/policies-guidelines/ipr], AS-IS, WITHOUT ANY
 * IMPLIED OR EXPRESS WARRANTY; there is no warranty of MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE or NONINFRINGEMENT of the rights of others.
 */
```
See:
  - https://github.com/oasis-tcs/pkcs11/blob/master/published/2-40-errata-1/pkcs11.h#L1

**Comment by diabonas** [comment]
It is not clear to me whether this header actually grants the license, since the linked OASIS IPR Policy is not a license document, but a policy that contributors have to follow (that forces them to license the documents appropriately, but there is a difference between "I am contractually obligated to license" and "I hereby license"). The policy itself also depends on the "IPR Mode" the TC uses, which [appears to be RF on RAND for the OASIS PKCS 11 TC](https://github.com/oasis-tcs/pkcs11/blob/5bd69a7d03788c370f5d0309f2593093a1586d9e/LICENSE.md), but this information is not included in the copyright header, so this is hardly enough information to derive the suitable licensing terms.

On the other hand, [Section 14.2](https://www.oasis-open.org/policies-guidelines/ipr#s14.2) states:
>  Other OASIS Deliverables that are primarily intended for machine rather than human consumption and whose format requires terse expression may, as an alternative to Section 14.1, include just the short-form notice as follows replacing [copyright year] with the year or year range of publication:
>
>>    *Copyright © OASIS Open [copyright year]. All Rights Reserved.
    Distributed under the terms of the OASIS IPR Policy, [<http://www.oasis-open.org/policies-guidelines/ipr>], AS-IS, WITHOUT ANY IMPLIED OR EXPRESS WARRANTY; there is no warranty of MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE or NONINFRINGEMENT of the rights of others.*

I will take this to mean that the copyright notice is intended as a shorthand for the complete license in [Section 14.1](https://www.oasis-open.org/policies-guidelines/ipr#s14.1) and grants the same distribution rights.

**Comment by diabonas** [comment]
Note that this only allows using and distributing the PKCS#11 headers files, modifying them is still not permitted by the license:

> However, this document itself may not be modified in any way, including by removing the copyright notice or references to OASIS, except as needed for the purpose of developing any document or deliverable produced by an OASIS Technical Committee (in which case the rules applicable to copyrights, as set forth in the OASIS IPR Policy, must be followed) or as required to translate it into languages other than English.

This should probably be documented somewhere in tpm2-pkcs11.
