### ISSUE TITLE
tpm2_ptool is out of date with the latest tpm2-tools

### ISSUE THREAD

**Issue by Arvanaghi** [tpm2-software/tpm2-pkcs11#343]
Things like `-p` vs. `-P` flag for `tpm2_createprimary`. Is there anything in the works to update this?

**Comment by williamcroberts** [comment]
tpm2_createprimary takes both -P and -p options. -P refers to the auth for the hiearchy and -p refers to the to be created objects auth value.

I have been testing tpm2-pkcs11 against tpm2-tools tag 4.1 which is the newest release. AFAIK, anything tpm2-tools 4.0+ should works. So I am assuming you're tools are too old. You can get the version of the tools by running any command with the --version option.

**Comment by Arvanaghi** [comment]
@williamcroberts Sorry to hijack this thread, but do you know why the tpm2_ptool.py file would return an error that `--pobj-pin=123456` is not recognized as an argument when trying to initialize a token/slot?

It seems like something is out of date here. I'm using Python 2.7 per the instructions.

**Comment by williamcroberts** [comment]
> @williamcroberts Sorry to hijack this thread, but do you know why the tpm2_ptool.py file would return an error that `--pobj-pin=123456` is not recognized as an argument when trying to initialize a token/slot?
> 
> It seems like something is out of date here. I'm using Python 2.7 per the instructions.

I need to update the docs, but that option went away and it not supported. We couldn't safely hag on to  We do have python3 support too.

Can I close this relating to the tools versions or can you reproduce something?

**Comment by Arvanaghi** [comment]
Yes, but I’m not sure how to initialize a slot/token and create a key at this point. Do you mind making a quick summary?
