### ISSUE TITLE
Support C_InitToken

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-pkcs11#364]
This would have to do the same thing as `tpm2_ptool.py addtoken`.
The difference would be that you can use it from token manager programs, such as `pkcs11-tool` or `p11-tool`.

See here for examples
https://github.com/AndreasFuchsSIT/tpm2-pkcs11/blob/fapi-wip/test/integration/pkcstool.int
https://github.com/AndreasFuchsSIT/tpm2-pkcs11/blob/fapi-wip/test/integration/p11tool.int

**Comment by williamcroberts** [comment]
I have questions around defaults:

The current code calls a tpm2_ptool init --path=<path> where <path> is a store, then calls tpm2_ptool addtoken. tpm2_ptool init just initializes a db and adds a primary key. There is some search logic based to figure out what <path> should be when not specified, so thats easy enought. But what to do when a DB is found with more than one primary object or when a DB isn't found and we need a primary object.

If it has primary keys where N > 1, do we just pick the first one and use it? Do we look for an ESYS_TR that points to one of the specified SRKs (isn't it expected at some handle if you follow the pc client guide?), if present then use it.

If it has 0 primary keys do we look at the TPM and use the SRK outlined in the provisioning spec?
If no SRK then do we just create our own primary key? If so how do we specify OWNER auth if it's not empty? Just ENV var? Technically it would be a complex token if it requires anything not through the pkcs11 interface...

**Comment by williamcroberts** [comment]
FYI this seems to be working, relatively stable AFAIK on my branch over at:
https://github.com/williamcroberts/tpm2-pkcs11/tree/C_InitToken-support

FYI I may rebase/squash commits on that branch at any time... you've been warned.
