### ISSUE TITLE
tools directory is missing from release tarball rc0

### ISSUE THREAD

**Issue by Jakuje** [tpm2-software/tpm2-pkcs11#367]
When trying to build the tpm2-pkcs11 for fedora, which packaged also some of the tools to be able to set up the tpm, I noticed that the tools directory is not in the release tarball.

I assume this is just an omission. As the python tools are useful.

**Comment by williamcroberts** [comment]
Yeah, didn't add them to the dist, great catch thanks!

**Comment by williamcroberts** [comment]
Fixed:
https://github.com/tpm2-software/tpm2-pkcs11/pull/366/commits/253affcf70ccf96d8df4da780e3ec01d50a49ac9

**Comment by Jakuje** [comment]
The 1.0.1-RC0 release looks good. Thanks.
