### ISSUE TITLE
Character-Strings must be padded correctly and should not/must not be NULL terminated

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#37]
All character-strings in pkcs#11 must be padded with the blank character ' '.
In most cases the character string SHOULD NOT be NULL terminated.
or in some cases it MUST not be NULL terminated.

-> Fix by applying the correct padding without NULL termination (for all cases).
Luckily pcks11t.h already includes comments which members should be padded.
-> Check all occurrences and fix them as necessary.

**Comment by williamcroberts** [comment]
@PeterHuewe is this fixed in #36 ?

**Comment by PeterHuewe** [comment]
No, #36 fixes two important instances, but basically almost every string, label, id, attribute should be handles this way.
We still have many many many occurrences for this.
(E.g. manufacturer label)
Basically everything thats simply assigned (e.g. to a struct member) is part of this bug.

**Comment by williamcroberts** [comment]
Strings should be formatted per: https://www.ietf.org/rfc/rfc2279.txt

**Comment by williamcroberts** [comment]
Looks fixed in linked commits. However, I did have some cleanups to reduce duplicate code and multiple copies.
