### ISSUE TITLE
Stored certificate leads to hangups in other tools

### ISSUE THREAD

**Issue by steschuser** [tpm2-software/tpm2-pkcs11#389]
Hello,

as discussed in the mailing list
https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/message/N66Z6QMZAFSNM6GIY3QJXDY67E2KBE3L/

I managed to store a certificate via addcert

`./tpm2_ptool addcert --label
soveryimportant /home/steffenschwebel/Projects/PKI_network/hardware.crt --key-label
soveryimportant
action: add
cert:
  CKA_ID: f2bed0abc381728ab5406931d138288c9dbbee9e`

But I cannot actually use this. Trying to access it will lead to hangups, no matter if its Networkmanager or p11tool.

I'm not sure how to debug this further. Is there a way to log whats happening?

regards,
Steffen

**Comment by williamcroberts** [comment]
```
export TPM2_PKCS11_LOG_LEVEL=2
```
I wonder if I screwed up some lock or something

**Comment by williamcroberts** [comment]
@steschuser did you ever capture logs for this?

**Comment by williamcroberts** [comment]
No update and I have yet to see/hear of any other related issues or steps on how to reproduce. Closing.
