### ISSUE TITLE
Contradicting SPDX License Information

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#42]
E.g. 
https://github.com/tpm2-software/tpm2-pkcs11/blob/master/test/integration/pkcs-find-objects.int.c
shows:
```
/* SPDX-License-Identifier: BSD-2 */
/*
 * Copyright (c) 2018, Intel Corporation
 * All rights reserved.
 */
/* SPDX-License-Identifier: BSD-2 */
/***********************************************************************
 * Copyright (c) 2017-2018, Intel Corporation
 *
 * All rights reserved.
 ***********************************************************************/
```

--> Are we BSD 2 or 3?

**Comment by williamcroberts** [comment]
BSD-2. Looks like an instance of 'scripts gone wild'. But the header and LICENSE file seem to be correct at calling out the general BSD-2 clause and explicitly listing what isn't BSD-2.
