### ISSUE TITLE
1.1 RC0 fails to build on 32 bit arches (i686, ARMv7)

### ISSUE THREAD

**Issue by nullr0ute** [tpm2-software/tpm2-pkcs11#420]
Testing 1.1.0 RC0 on Fedora 33 (gcc10) and it fails to build on 32 bit arches:

<pre>
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./src/lib    -I./src -I./src/lib -Wall -Wextra -Werror -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wstrict-overflow=5 -O2 -fPIC -fPIE       -pthread   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -g -c -o src/lib/sign.lo src/lib/sign.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src/lib -I./src -I./src/lib -Wall -Wextra -Werror -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wstrict-overflow=5 -O2 -fPIC -pthread -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -g -c src/lib/sign.c  -fPIC -DPIC -o src/lib/.libs/sign.o
src/lib/sign.c: In function 'sign_final_ex':
src/lib/sign.c:231:83: error: passing argument 4 of 'digest_final_op' from incompatible pointer type [-Werror=incompatible-pointer-types]
  231 |         rv = digest_final_op(ctx, opdata->digest_opdata, (CK_BYTE_PTR)digest_buf, &hash_len);
      |                                                                                   ^~~~~~~~~
      |                                                                                   |
      |                                                                                   size_t * {aka unsigned int *}
In file included from src/lib/sign.c:9:
src/lib/digest.h:35:107: note: expected 'CK_ULONG_PTR' {aka 'long unsigned int *'} but argument is of type 'size_t *' {aka 'unsigned int *'}
   35 | CK_RV digest_final_op(session_ctx *ctx, digest_op_data *supplied_opdata, CK_BYTE_PTR digest, CK_ULONG_PTR digest_len);
      |                                                                                              ~~~~~~~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:1513: src/lib/sign.lo] Error 1
</pre>

**Comment by williamcroberts** [comment]
Staged on 1.1.X for RC1 as commit: 22ef1726d0
