### ISSUE TITLE
make PSS signature configurable/smarter

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#445]
Currently we test if the FIPS_140_2 bit is set in TPMA_MODES, and if it's set, we know that we can use PSS signatures natively with the TPM. The problem,  is that *MOST* TPM's running the 1.38 firmware PSS signature support works, out of the box. We could make the "support pss natively" code a little smarter through two methods:
1. FW check, which might be wrong.
2. A PSS signature check.

I think the PSS signature check and set the config would be the best way. BUMP the DB VERSION to get execution just once per store.

We could also make the store initialization code create an RSA key and perform a PSS signature and try RSA_verify_PKCS1_PSS_mgf1() with:
-1 slen == hlen
-3 slen is maximized

We can add a config flag in the STORE LEVEL config to override this detection in case we get it wrong.

**Comment by williamcroberts** [comment]
Not really sure how to do this in python though:

Constructing RSA Public Key:
https://www.dlitz.net/software/pycrypto/api/current/Crypto.PublicKey.RSA-module.html
```
construct(tup) Construct an RSA key object from a tuple of valid RSA components.See RSAImplementation.construct.Parameters:tup (tuple) - A tuple of long integers, with at least 2 and no more than 6 items. The items come in the following order:RSA modulus (n).Public exponent (e).Private exponent (d). Only required if the key is private.First factor of n (p). Optional.Second factor of n (q). Optional.CRT coefficient, (1/p) mod q (u). Optional.Returns:An RSA key object (_RSAobj). | construct(tup) |  
-- | -- | --
construct(tup) |  
```

Looks like for verifying:
```
>>> key = RSA.importKey(open('pubkey.der').read())
>>> h = SHA.new()
>>> h.update(message)
>>> verifier = PKCS1_PSS.new(key)
>>> if verifier.verify(h, signature):
>>>     print "The signature is authentic."
>>> else:
>>>     print "The signature is not authentic."
```
```
new(key, mgfunc=None, saltLen=None) Return a signature scheme object PSS_SigScheme that can be used to perform PKCS#1 PSS signature or verification. | new(key, mgfunc=None, saltLen=None) |  
-- | -- | --
new(key, mgfunc=None, saltLen=None) |  
```

**Comment by williamcroberts** [comment]
In the PYTHON code, we can check for maximized slen by:
```
saltLen = key_size_bytes - hash_size_bytes - 2;
```

**Comment by williamcroberts** [comment]
Started working on this at:
  - https://github.com/williamcroberts/tpm2-pkcs11/tree/store-config-pss-sig-detection

**Comment by williamcroberts** [comment]
Darn, I have to redesign this. I have this in a global store config, and it needs to be in the per-token config. Which makes it a lot harder. Each token, will need to refresh this state on token init, which could take a long time.

**Comment by AndreasFuchsSIT** [comment]
When you redesign, how about starting off of the FAPI-PR, so we have less merge problems.
Given your ok, I'd add the commit messages and have you merge the FAPI-PR.

**Comment by williamcroberts** [comment]
> When you redesign, how about starting off of the FAPI-PR, so we have less merge problems.
> Given your ok, I'd add the commit messages and have you merge the FAPI-PR.

It still shows as broken

**Comment by AndreasFuchsSIT** [comment]
I see you restarted the 2 jobs... :-)

**Comment by williamcroberts** [comment]
> I see you restarted the 2 jobs... :-)

Yep, merged. Those damn nss tests, issue #444. In the future, it also helps if you take things out of draft status indicating you expect some feedback. I just saw draft/failing nor never got a ping until just now, so I never re-looked at it.
