### ISSUE TITLE
Test certs in repo have expired

### ISSUE THREAD

**Issue by dkobras** [tpm2-software/tpm2-pkcs11#464]
The server and CA certificates checked into `test/integration/fixtures` have expired in December last year:
```
% openssl x509 -in test/integration/fixtures/ca.pem -noout -enddate
notAfter=Dec 29 14:07:18 2019 GMT
% openssl x509 -in test/integration/fixtures/server.pem -noout -enddate
notAfter=Dec 29 14:07:18 2019 GMT
```

The TLS tests don't seem to care, but the (fixed) NSS tests now fail with:
```
Testing if S/MIME certificate in NSS DB is valid for mail signing
+ pinentry certutil -V -d . -n import-keys:smimetest -u S
+ cat
+ expect
spawn certutil -V -d . -n import-keys:smimetest -u S^M
Enter Password or Pin for "import-keys":^M
certutil: certificate is invalid: The certificate issuer's certificate has expired.  Check your system date and time.^M
++ onerror
++ echo 'expect on line 34 failed: 255'
expect on line 34 failed: 255
++ exit 1
```
Given that this actually is an error, I'd rather not work around it in the NSS tests themselves. Would you prefer to upload new test certs (with longer validity), or what about generating the certs from `create_pkcs_store.sh` (re-using the existing keys)?

**Comment by williamcroberts** [comment]
@dkobras I guess we can just generate the keys at initialization time, so we never hit this issue again.
