### ISSUE TITLE
SunPKCS11 Provider Initialization error using libtpm2_pkcs11.so

### ISSUE THREAD

**Issue by Koerk123** [tpm2-software/tpm2-pkcs11#480]
Hi All,
i am facing an Initialization failed exception when executing keytool:<br/>
```
sudo keytool -v -keystore NONE -storetype PKCS11 -list

ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:209:Fapi_List_Finish() Path not found: (null)
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:78:Fapi_List() ErrorCode (0x00060024) Entities_List
ERROR: Listing FAPI token objects failed.
ERROR: Getting tokens from fapi backend failed.
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:209:Fapi_List_Finish() Path not found: (null)
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:78:Fapi_List() ErrorCode (0x00060024) Entities_List
ERROR: Listing FAPI token objects failed.
ERROR: Getting tokens from fapi backend failed.
java.security.ProviderException: Initialization failed
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:387)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
	at sun.security.jca.ProviderList.getService(ProviderList.java:331)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	at sun.security.tools.keytool.Main.doCommands(Main.java:794)
	at sun.security.tools.keytool.Main.run(Main.java:366)
	at sun.security.tools.keytool.Main.main(Main.java:359)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_GENERAL_ERROR
	at sun.security.pkcs11.wrapper.PKCS11.C_Initialize(Native Method)
	at sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Initialize(PKCS11.java:1545)
	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:157)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:341)
	... 18 more
```
I use the keytool from java-8-openjdk-armhf where i also modified the java.security file
```
which keytool

/usr/lib/jvm/java-8-openjdk-armhf/bin/keytool

cat /usr/lib/jvm/java-8-openjdk-armhf/jre/lib/security/java.security | grep security.provider

security.provider.1=sun.security.provider.Sun
security.provider.2=sun.security.rsa.SunRsaSign
security.provider.3=sun.security.ec.SunEC
security.provider.4=com.sun.net.ssl.internal.ssl.Provider
security.provider.5=com.sun.crypto.provider.SunJCE
security.provider.6=sun.security.jgss.SunProvider
security.provider.7=com.sun.security.sasl.Provider
security.provider.8=org.jcp.xml.dsig.internal.dom.XMLDSigRI
security.provider.9=sun.security.smartcardio.SunPCSC
security.provider.10=sun.security.pkcs11.SunPKCS11 ${java.home}/lib/security/pkcs11.cfg 

cat /usr/lib/jvm/java-8-openjdk-armhf/jre/lib/security/pkcs11.cfg 

name = Tpm2Pkcs11
library = /usr/local/lib/libtpm2_pkcs11.so
description = PKCS11 based on TCG TPM2 implementation
slot = 1
```
I use the resulting slot when the tpm2 store was created.
```
ls -la /home/pi/tmp/

total 48
drwxr-xr-x  2 pi   pi    4096 Apr 16 08:46 .
drwxr-xr-x 19 pi   pi    4096 Apr 16 07:49 ..
-rw-r--r--  1 root root 36864 Apr 14 09:44 tpm2_pkcs11.sqlite3

sudo ./tpm2_ptool.py listprimaries --path /home/pi/tmp/

- id: 1

sudo ./tpm2_ptool.py listtokens --pid 1 --path /home/pi/tmp/
- id: 1
  label: ****

sudo ./tpm2_ptool.py listobjects --label ***** --path /home/pi/tmp/

- CKA_CLASS: CKO_PRIVATE_KEY
  CKA_ID: '*****
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: ''
  id: 1
- CKA_CLASS: CKO_PUBLIC_KEY
  CKA_ID: '*****'
  CKA_KEY_TYPE: CKK_RSA
  CKA_LABEL: ''
  id: 2
```

My env looks like this:
```
...
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-armhf/jre
JAVA_HOME_BIN=/usr/lib/jvm/java-8-openjdk-armhf
TPM2_PKCS11_TCTI=tabrmd:
TPM2_PKCS11_LOG_LEVEL=2
TSS2_LOG=fapi+TRACE
TPM2_PKCS11_STORE=/home/pi/tmp
PATH=/usr/lib/jvm/java-8-openjdk-armhf/bin:/usr/lib/jvm/java-1.8.0-openjdk-armhf/jre/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
```

Could you provide me with some insight regarding this.
Thank you.

**Comment by williamcroberts** [comment]
What is your tpm2-pkcs11 version, FAPI stuff hasn't been released, so it might be as simple as updating to the latest code on the master branch. Im pretty sure we fixed these errors.

**Comment by Koerk123** [comment]
This is the version i got from the config.log:
`1.1.0-132-g46e7a18`

**Comment by AndreasFuchsSIT** [comment]
Did you export `FAPI_PREVIEW=true` ?

**Comment by williamcroberts** [comment]
If you look at the logs it was in `backend_get_tokens()`, and the variable `fapi_ini`t was set to `true`. That probably shouldn't die fatally there unless `FAPI_PREVIEW is true. Right now init and list always occur, and if init succeeds but list fails, you'll hit this issue.

`FAPI_PREVIEW` is only affecting `backend_create_token_seal()` We may wish to make all fapi integration errors fatal or not based on that (for now, until we have time to stablize it), so we can cut from master soon.

**Comment by williamcroberts** [comment]
Also the logic in backend_destroy() for picking the bad `rv` seems wrong at first glance.

**Comment by williamcroberts** [comment]
@Koerk123 I have attached a patch file [0001-RFC-fix-fapi-backend-errors-into-warnings.patch.txt](https://github.com/tpm2-software/tpm2-tools/files/4494151/0001-RFC-fix-fapi-backend-errors-into-warnings.patch.txt)
, can you apply that to the `tpm2-pkcs11` directory using the `git am` command, like so:
```bash
git am 0001-RFC-fix-fapi-backend-errors-into-warnings.patch.txt
```
**Note: You must be in the tpm2-pkcs11 directory for git to work**

Can you apply it and let me know if prevents your issues?

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts The thing that triggered me was `Listing FAPI token objects failed.` which only occurs in the `backend_fapi_add_tokens()` which in turn is only called if FAPI_PREVIEW is set, right ?

Or did I miss something ?

**Comment by williamcroberts** [comment]
> @williamcroberts The thing that triggered me was `Listing FAPI token objects failed.` which only occurs in the `backend_fapi_add_tokens()` which in turn is only called if FAPI_PREVIEW is set, right ?
> 
> Or did I miss something ?

No backend list tokens depends on fapi_init being true. FAPI_PREVIEW is only controlling the init_token command.

**Comment by Koerk123** [comment]
Hi,
sorry for not replying earlier.
@williamcroberts I applied your patch file and re-compiled / installed tpm2-pkcs11. Now keytool was successful.
```
pi@raspberrypi:~/TPM/tpm2-pkcs11 $ sudo keytool -v -keystore NONE -storetype PKCS11 -list
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:209:Fapi_List_Finish() Path not found: (null) 
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:78:Fapi_List() ErrorCode (0x00060024) Entities_List 
ERROR: Listing FAPI token objects failed.
Enter keystore password:  
Keystore type: PKCS11
Keystore provider: SunPKCS11-Tpm2Pkcs11

Your keystore contains 0 entries

pi@raspberrypi:~/TPM/tpm2-pkcs11 $ 
```
There are still some error messages, are these critical or can they be ignored?
The patch you gave me is part of the master and I should update my local to the newest state, or is it a separate fix?

**Comment by AndreasFuchsSIT** [comment]
> No backend list tokens depends on fapi_init being true. FAPI_PREVIEW is only controlling the init_token command.

FAPI_PREVIEW controls the init_token.
The token's config controls the init_tobject.
That's why I don't get it... Corrupted Token-Data ?

**Comment by Koerk123** [comment]
@AndreasFuchsSIT I have not set FAPI_PREVIEW myself. I listed all tpm related env vars which I set.

**Comment by williamcroberts** [comment]
> > No backend list tokens depends on fapi_init being true. FAPI_PREVIEW is only controlling the init_token command.
> 
> FAPI_PREVIEW controls the init_token.
> The token's config controls the init_tobject.
> So unless a token was inited with FAPI_PREVIEW, the tobjects for this token should never be in fapi...
> That's why I don't get it... Corrupted Token-Data ?

@AndreasFuchsSIT 
It's hitting "ERROR: Listing FAPI token objects failed.", so rc is not success or IO error. The error code is fapi:The path was not found, (0x00060024), which I think is `TSS2_FAPI_RC_PATH_NOT_FOUND` Which is being printed after you free and reseat the pointer to null.

```C
CK_RV backend_fapi_add_tokens(token *tok, size_t *len) {
    CK_RV rv = CKR_GENERAL_ERROR;
    TSS2_RC rc;
    char *pathlist;

    rc = Fapi_List(fctx, "/HS/SRK", &pathlist);
    if (rc == TSS2_FAPI_RC_IO_ERROR) {
        /* If no token seals were found, we're done here. */
        LOGV("No FAPI token seals found.");
        return CKR_OK;
    }
    if (rc) {
        LOGE("Listing FAPI token objects failed.");
        return CKR_GENERAL_ERROR;
    }
```


```C
TSS2_RC
Fapi_List_Finish(
    FAPI_CONTEXT *context,
    char        **pathList)
{
....
cleanup:
    /* Cleanup any intermediate results and state stored in the context. */
    SAFE_FREE(command->searchPath);
    if (numPaths == 0 && (r == TSS2_RC_SUCCESS)) {
        LOG_ERROR("Path not found: %s", command->searchPath);
        r = TSS2_FAPI_RC_PATH_NOT_FOUND;
    }
    if (numPaths > 0) {
        for (size_t i = 0; i < numPaths; i++){
            SAFE_FREE(pathArray[i]);
        }
    }
    SAFE_FREE(pathArray);
    return r;
}
```

**Comment by williamcroberts** [comment]
> Hi,
> sorry for not replying earlier.
> @williamcroberts I applied your patch file and re-compiled / installed tpm2-pkcs11. Now keytool was successful.
> 
> ```
> pi@raspberrypi:~/TPM/tpm2-pkcs11 $ sudo keytool -v -keystore NONE -storetype PKCS11 -list
> ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:209:Fapi_List_Finish() Path not found: (null) 
> ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:78:Fapi_List() ErrorCode (0x00060024) Entities_List 
> ERROR: Listing FAPI token objects failed.
> Enter keystore password:  
> Keystore type: PKCS11
> Keystore provider: SunPKCS11-Tpm2Pkcs11
> 
> Your keystore contains 0 entries
> 
> pi@raspberrypi:~/TPM/tpm2-pkcs11 $ 
> ```
> 
> There are still some error messages, are these critical or can they be ignored?
> The patch you gave me is part of the master and I should update my local to the newest state, or is it a separate fix?

You can ignore those for now, FAPI is still having issues but they shouldn't be affecting you. I have to clean up this patch and open a PR.
