### ISSUE TITLE
Error while generate a certificate signing request - PKCS11_get_private_key  

### ISSUE THREAD

**Issue by Darsh-Dev** [tpm2-software/tpm2-pkcs11#484]
Hi,

I am following the steps as mentioned
https://aws.amazon.com/blogs/iot/using-a-trusted-platform-module-for-endpoint-device-security-in-aws-iot-greengrass/

I am facing issue while **Generate a certificate signing request** the below command is used,

> openssl req -engine pkcs11 -new -key "pkcs11:model=SLI9670;manufacturer=Infineon;token=greengrass;object=greenkey;type=private;pin-value=123456" -keyform engine -out /tmp/req.csr

> ```
> OpenSSL> engine dynamic -pre SO_PATH:/usr/lib/engines-1.1/libpkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib/opensc-pkcs11.so
>     (dynamic) Dynamic engine loading support
>     [Success]: SO_PATH:/usr/lib/engines-1.1/libpkcs11.so
>     [Success]: ID:pkcs11
>     [Success]: LIST_ADD:1
>     [Success]: LOAD
>     [Success]: MODULE_PATH:/usr/lib/opensc-pkcs11.so
>     Loaded: (pkcs11) pkcs11 engine
> 
> ```
> 

> **openssl req -verbose -engine pkcs11 -new -key "pkcs11:model=SLI9670;manufacturer=Infineon;token=greengrass;object=greenkey;type=private;pin-value=1**
> 23456" -keyform engine -out /tmp/req.csr
> engine "pkcs11" set.
> Using configuration from /usr/lib/ssl-1.1/openssl.cnf
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> **Specified object not found
> PKCS11_get_private_key returned NULL
> cannot load Private Key from engine
> 3070050320:error:80067065:pkcs11 engine:ctx_load_privkey:object not found:eng_back.c:862:
> 3070050320:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../openssl-1.1.1b/crypto/engine/eng_pkey.c:78:
> unable to load Private Key**
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> root@stm32mp1-av96:~#

**Comment by PeterHuewe** [comment]
Please increase logging of pkcs11, steps provided e.g. in the other issue

**Comment by PeterHuewe** [comment]
Also what is the output of
`p11tool --list-privkeys pkcs11:manufacturer=Infineon`

**Comment by Darsh-Dev** [comment]
Sure, I will share the logs after increase logging of pkcs11 @PeterHuewe 

Pl see below output of,
> root@stm32mp1-av96:~# p11tool --list-privkeys pkcs11:manufacturer=Infineon
> Object 0:
>         URL: pkcs11:model=SLB9670;manufacturer=Infineon;serial=0000000000000000;token=greengrass;id=%34%66%38%63%37%64%35%31%39%39%35%66%30%35%61%61;object=greenkey;type
> =private
> Token 'greengrass' with URL 'pkcs11:model=SLB9670;manufacturer=Infineon;serial=0000000000000000;token=greengrass' requires user PIN
> Enter PIN: 
>         Type: Private key (RSA-2048)
>         Label: greenkey
>         Flags: CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
>         ID: 34:66:38:63:37:64:35:31:39:39:35:66:30:35:61:61

**Comment by PeterHuewe** [comment]
You have a SLB, but specified SLI in the url for the csr.

**Comment by Darsh-Dev** [comment]
Hi @PeterHuewe , I have tried with SLB as well, same error seen. 

Now I get some update, Error reported as 
3070050320:error:80067065:pkcs11 engine:ctx_load_privkey:**object not found**:eng_back.c:862:


I changed the commands  **like Object=greenkey to lable-greenkey** and tried it again.

> OpenSSL> req -engine pkcs11 -new -key "pkcs11:model=SLB9670;manufacturer=Infineon;token=greengrass;label=greenkey;type=private;pin-value=123456" -keyform engine -out /tm
> p/req.csr
> engine "pkcs11" set.
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> The key ID is not a valid PKCS#11 URI
> The PKCS#11 URI format is defined by RFC7512
> The key ID is not a valid PKCS#11 URI
> The PKCS#11 URI format is defined by RFC7512
> PKCS11_get_private_key returned NULL
> cannot load Private Key from engine
> 3069468688:error:80065064:pkcs11 engine:ctx_load_key:**invalid id:eng_back.c:636:**
> 3069468688:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../openssl-1.1.1b/crypto/engine/eng_pkey.c:78:
> unable to load Private Key
> error in req
> OpenSSL> 
> 

Now Its give us **invalid id:eng_back.c:636:**.

**Comment by Darsh-Dev** [comment]
also tried with `export TPM2_PKCS11_LOG_LEVEL=2` No additional log seen.

**Comment by PeterHuewe** [comment]
`openssl req -engine pkcs11 -new -key "pkcs11:model=SLB9670;manufacturer=Infineon;token=greengrass;object=greenkey;type=private;pin-value=123456"  -keyform engine -out /tmp/req.csr`

**Comment by Darsh-Dev** [comment]
> OpenSSL> engine dynamic -pre SO_PATH:/usr/lib/engines-1.1/libpkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib/opensc-pkcs11.so
> (dynamic) Dynamic engine loading support
> [Success]: SO_PATH:/usr/lib/engines-1.1/libpkcs11.so
> [Success]: ID:pkcs11
> [Success]: LIST_ADD:1
> [Success]: LOAD
> [Success]: MODULE_PATH:/usr/lib/opensc-pkcs11.so
> Loaded: (pkcs11) pkcs11 engine
> 

> OpenSSL> req -engine pkcs11 -new -key "pkcs11:model=SLB9670;manufacturer=Infineon;token=greengrass;object=greenkey;type=private;pin-value=123456" -keyform engine -out /t
> mp/req.csr
> engine "pkcs11" set.
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> Specified object not found
> PKCS11_get_private_key returned NULL
> cannot load Private Key from engine
> 3069653008:error:80067065:pkcs11 engine:ctx_load_privkey:object not found:eng_back.c:858:
> 3069653008:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../openssl-1.1.1b/crypto/engine/eng_pkey.c:78:
> unable to load Private Key
> error in req
> OpenSSL> 

Same error seen with suggested command.

**Comment by PeterHuewe** [comment]
Hi, what's the output of `openssl engine -t -tt pkcs11 -c`

**Comment by Darsh-Dev** [comment]
Hi, @PeterHuewe 

> OpenSSL> engine -t -tt pkcs11 -c
> engine: Cannot mix flags and engine names.
> engine: Use -help for summary.
> error in engine
> OpenSSL>

**Comment by Darsh-Dev** [comment]
Is there any simple command to just validate the pkcs and openssl ?

**Comment by PeterHuewe** [comment]
`openssl engine -t -tt -c pkcs11 `

**Comment by Darsh-Dev** [comment]
```
openssl engine -t -tt -c pkcs11
(pkcs11) pkcs11 engine
 [RSA, rsaEncryption, id-ecPublicKey]
     [ available ]
```

**Comment by PeterHuewe** [comment]
```
export TPM2_PKCS11_LOG_LEVEL=2
openssl req -engine pkcs11 -new -key "pkcs11:model=SLB9670;manufacturer=Infineon;token=greengrass;object=greenkey;type=private;pin-value=123456" -keyform engine -out /tmp/req.csr
```

**Comment by Darsh-Dev** [comment]
@PeterHuewe ,

> root@stm32mp1-av96:~# export TPM2_PKCS11_LOG_LEVEL=2
> root@stm32mp1-av96:~# openssl req -engine pkcs11 -new -key "pkcs11:model=SLB9670;manufacturer=Infineon;token=greengrass;object=greenkey;type=private;pin-value=123456" -k
> eyform engine -out /tmp/req.csr
> engine "pkcs11" set.
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> Specified object not found
> PKCS11_get_private_key returned NULL
> cannot load Private Key from engine
> 3069763600:error:80067065:pkcs11 engine:ctx_load_privkey:object not found:eng_back.c:858:
> 3069763600:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../openssl-1.1.1b/crypto/engine/eng_pkey.c:78:
> unable to load Private Key
> Error: can't open /var/run/openct/status: No such file or directory
> Error: can't open /var/run/openct/status: No such file or directory
> root@stm32mp1-av96:~#

**Comment by PeterHuewe** [comment]
Then the connection between pkcs11 engine and tpm2-pkcs11 seems to be broken.
Please run with strace
```
strace  openssl req -engine pkcs11 -new -key "pkcs11:model=SLB9670;manufacturer=Infineon;token=greengrass;object=greenkey;type=private;pin-value=123456" -k
eyform engine -out /tmp/req.csr
```

Which version of libp11 do you use? 
Output of  
`ls -lah /usr/share/p11-kit/modules/`

**Comment by Darsh-Dev** [comment]
libp11 version used : **0.4.10**, tried with 0.4.9 as well.


```
root@stm32mp1-av96:~# ls -lah /usr/share/p11-kit/modules/
total 16K
drwxr-xr-x 2 root root 4.0K Mar  9  2018 .
drwxr-xr-x 3 root root 4.0K Mar  9  2018 ..
-rw-r--r-- 1 root root  776 Mar  9  2018 p11-kit-trust.module
-rw-r--r-- 1 root root   40 Mar  9  2018 tpm2_pkcs11.module
root@stm32mp1-av96:~#
```

Will share the strace as well

**Comment by PeterHuewe** [comment]
and maybe also share your openssl version

**Comment by Darsh-Dev** [comment]
**OpenSSL 1.1.1b**

Please find the strace result,
[strace_openssl_log.zip](https://github.com/tpm2-software/tpm2-pkcs11/files/4493048/strace_openssl_log.zip)

**Comment by PeterHuewe** [comment]
`cat /etc/opensc.conf`

**Comment by Darsh-Dev** [comment]
Sure, I will share, 

Meanwhile Please let know below command is Okay 

OPENSSL > ` engine dynamic -pre SO_PATH:/usr/lib/engines-1.1/libpkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib/opensc-pkcs11.so`

**Comment by Darsh-Dev** [comment]
Hey @PeterHuewe ,

Issue is resolved 
Wrong Module is Loaded

Changed to 
OPENSSL > `engine dynamic -pre SO_PATH:/usr/lib/engines-1.1/libpkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib/pkcs11/libtpm2_pkcs11.so`

**Comment by PeterHuewe** [comment]
I do not have to set anything like this on my system.
why` /usr/lib/opensc-pkcs11.so `?
I think here the path to` libtpm2_pkcs11.so` should be

**Comment by PeterHuewe** [comment]
Great - as said, I did not have to specify this on my system but okay.
Can we close this ?

**Comment by Darsh-Dev** [comment]
Yes @PeterHuewe Thanks for support Again
