### ISSUE TITLE
Session State

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#5]
Session State is currently not global and it should be. Once a C_Login occurs, all sessions are logged in. Correct this in the implementation and test.

**Comment by robby-cornelissen** [comment]
I'm looking into trying to take this on, but have the following question: when you say "global", what do you mean exactly?

In the Cryptoki specification, I find the following:

> Call **C_Login** to log the user into the token.  Since all sessions an application has with a token have a shared login state, **C_Login** only needs to be called for one of the sessions.

If I read that correctly, that would mean that a minimal implementation would have to:

1. Add the `application` to the `session_ctx` struct.
2. In `session_login()`, after `session_ctx_login()` returns, walk through the `session_table` and update the state for all other sessions with the same application/token.
3. Do the same for `session_logout()`.

Am I on the right track here?

**Comment by williamcroberts** [comment]
2 and 3 seem correct, I'm not sure why you need 1.
