### ISSUE TITLE
Support C_CreateObject pf class CKO_DATA

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#512]
Support seal and unseal

**Comment by pchand20** [comment]
Hi Bill, any update on this ticket ?

**Comment by williamcroberts** [comment]
> Hi Bill, any update on this ticket ?

Nothing yet

**Comment by williamcroberts** [comment]
Fixed on master:
  - https://github.com/tpm2-software/tpm2-pkcs11/commit/c000a19d18fc53888092346914e5ab8407629413#diff-25d902c24283ab8cfbac54dfa101ad31

And on release 1.3.0:
  - https://github.com/tpm2-software/tpm2-pkcs11/releases/tag/1.3.0
