### ISSUE TITLE
Spurious error and warning messages upon SSH connection attempt

### ISSUE THREAD

**Issue by gouttegd** [tpm2-software/tpm2-pkcs11#515]
Hi,

I am using tpm2-pkcs11 to authenticate to a SSH server, following the instructions in the `doc/SSH.md` file. This used to work without any warning or error messages with tpm2-pkc11 v1.0, tpm2-tools v4.1, tpm2-abrmd v2.3.0, and tpm2-tss v2.3.2.

After upgrading to the last released version of all projects (tpm2-pkcs11 v1.20, tpm2-tools v4.2, tpm2-abrmd v2.3.2, and tpm2-tss v2.4.1), it still works (I can still connect successfully to the server) *but* I have the following warning and error messages upon each connection attempt, right after I enter the PIN:

> WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
> ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
> WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
> ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
> WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
> ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
> WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
> ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
> WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
> ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
> WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
> ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6)

I attach a log obtained with `TPM2_PKCS11_LOG_LEVEL=2`: [tpm2-pkcs11-log.txt](https://github.com/tpm2-software/tpm2-pkcs11/files/4673257/tpm2-pkcs11-log.txt)

The key on the token is a ECDSA P-256 key, but I also get exactly the same messages with a RSA-2048 key. I can try providing more informations if needed, just let me know.

**Comment by williamcroberts** [comment]
Yeah these are expected errors. The Esys_TestParams function will return an error if the requested algorithm is not supported. So when probing for support with this interface, the tpm2-tss library just logs anything that is not a TSS2_RC_SUCCESS (0) error code. So it's just a bit noisy. If you upgrade.

It's been fixed on this commit in the tpm2-tss project:
  - https://github.com/tpm2-software/tpm2-tss/commit/6eb5a49a1f55325accb46b51e775857a3ea6ec57

But doesn't look like it's found its way into a release. You could update to the master branch of tpm2-tss if tolerable, or back port that patch if needed.

But these error's are harmless.

If everything working as expected? Are you still able to ssh and everything?

**Comment by gouttegd** [comment]
Yes, apart from those warnings everything is working just as fine as before.
And I have just back ported the commit you mention to tpm2-tss-2.4.1, and indeed the warnings are now gone.

I guess I should have tested the master branch before reporting, sorry about that. Closing now, unless you want to add anything.

**Comment by PeterHuewe** [comment]
@gouttegd  - do you care to post a PR for your backport to 2.4.x ?

**Comment by gouttegd** [comment]
Sure, will do. It was the simplest backport ever anyway, since commit tpm2-software/tpm2-tss@9296201c209e0857b1ccd5e28b801559918266b9 in master applies cleanly to the 2.4.x branch.
