### ISSUE TITLE
Libyaml linking errors

### ISSUE THREAD

**Issue by crapster-goh** [tpm2-software/tpm2-pkcs11#517]
Hi, I'm getting a linking warning/error from libyaml when trying to call make. 

```
warning: /home/udl/TPM_and_MQTT_examples/src/libs/libyaml/include: linker input file unused because linking not done
CC       src/lib/attrs.lo
CC       src/lib/backend.lo
CC       src/lib/backend_esysdb.lo
```

Can I check if you know what's the problem? I am using libyaml 0.2.4. Is that the correct version of libyaml?

Thanks for your help!

**Comment by williamcroberts** [comment]
Is their any other errors or is that it? A full build log and the result of configure (config.log) would be helpful. But the fact that warning print statement has a path that isn't any part of the project is suspect.

**Comment by williamcroberts** [comment]
No updates in almost 2 months, closing.
