### ISSUE TITLE
Use existing secondary tpm keys

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#518]
Hi,
at `init` you can specify an existing primary handle which is nice.
You can add new (secondary) keys using the `addkey `feature of tpm2_ptool
You can import externally generated rsa keys using the `import `feature.

-> (How) can we (re)use secondary keys that have been already created with the tpm? (not created with pkcs11)

**Comment by williamcroberts** [comment]
This is what this ticket is for: https://github.com/tpm2-software/tpm2-pkcs11/issues/485

I want to add "link" to tpm2_ptool so you can just give it a pub/priv blob and will start using it. Same thing with tss-engine blobs
