### ISSUE TITLE
Could not parse token config

### ISSUE THREAD

**Issue by clem844** [tpm2-software/tpm2-pkcs11#523]
Tested with tpm2-pkcs11 v1.1.0 and v1.2.0. The database is created with tpm2_ptool.py 
Looks like a compatibility problem
Database schema version is 3

```
root@raspberrypi3:/home/root/tpm2-pkcs11/tools# tpm2pkcs11-tool --list-token-slots
ERROR: Could not parse token config, got: "---
!!map"
error: PKCS11 function C_Initialize failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```

**Comment by williamcroberts** [comment]
What version of tpm2_ptool are you using to create the db and what version of the C library are you running?

I have a test that starts with the first release version and does an upgrade to master, and that's never triggered this, so I'd like to be able to reproduce and add the test as well.

Versions 1.1.0 and 1.2.0 had no DB schema change, they were all `DB_SCHEMA 3`

Version 1.1 bumped the DB Schema to 3 in commits:
  - DB v1 to v2: aacb06e5e64e0c5eade71c7871ca0b1b456a2e01
  - DB v2 to v3: 3376b4b8c5b8fa2db92c89b416d58ab280afbf14

But I would imagine you would hit:
  - https://github.com/tpm2-software/tpm2-pkcs11/blame/master/src/lib/db.c#L1820

Which I brought in in this commit:
  - https://github.com/tpm2-software/tpm2-pkcs11/commit/fdeef2bc71cfd9d2dcc4e731a1b88cafbfcb8858

Which was in for 1.1.0 release. I also don't see any deltas between the parser.c or db.c file between 1.1.0 and 1.2.0:
- `git diff 1.1.0..1.2.0 -- src/lib/db.c`
- `git diff 1.1.0..1.2.0 -- src/lib/parser.c`

I'm not really sure how you got in this state.... unless your running a version 1.0 or 1.0.X release in your tpm2pkcs11-tool. Whats the configuration look like for that? Are you sure you're opening the right library? Maybe you got some old stuff floating around?

**Comment by clem844** [comment]
I'm using Yocto to build Linux and tpm2-pkcs11 included in "meta-tpm". The original version used was 0.9.9
I'm trying to build v1.2.0 but I got some compilation errors. Trying to figure that out

**Comment by williamcroberts** [comment]
It looks like they were on commit 6de3f6f9c6e0a4983f3fb90e35feb34906f8aea7 if I understand the build stuff they got going on http://git.yoctoproject.org/cgit/cgit.cgi/meta-security/tree/meta-tpm/recipes-tpm2/tpm2-pkcs11/tpm2-pkcs11_0.9.9.bb.

That's not on a release, it was still considered pre-production. I wonder if that's the version of the C library your invoking, because that code does no schema check, so it would just try and do something and fail.

**Comment by clem844** [comment]
Trying to use tpm2-pkcs11 v1.2.0
```
ERROR: tpm2-pkcs11-1.2.0-r0 do_configure: Execution of '/home/tce/yocto_dist/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/tpm2-pkcs11/1.2.0-r0/temp/run.do_configure.6066' failed with exit code 1:
Generating file lists: src_vars.mk
automake: error: cannot open < aminclude_static.am: No such file or directory
autoreconf: automake failed with exit status: 1
```

They had this issue on tpm2-software/tpm2-tss#1256
But "configure.ac" already includes the `AX_ADD_AM_MACRO_STATIC([])`
What am I missing?

**Comment by williamcroberts** [comment]
Maybe your autoconf macro package is out of date. Not really sure, never seen this one before. If you're using a local m4 install, you need to pass it as -I i think to bootstrap or copy it to the m4 directory in the root of the project.

See this bug for another project that had a similar issue:
https://github.com/openbmc/sdbusplus/issues/29

Looks like they installed the proper version system wide. But if you can build the tss, i doubt that's your issue.

**Comment by williamcroberts** [comment]
AFAICT, Yocto packaged a pre-release version of tpm2-pkcs11 which means the project has no official upgrade path for the db. You'll have to do it yourself or delete and recreate the store.

**Comment by clem844** [comment]
Ok, I think this was because I created the token with tpm2_ptool (from master) so pkcs11-tool wasn't able to read it properly.
This time I created a new store DB and the fist token with pkcs11-tool. It now reads it without problem. Thanks for your help!

**Comment by williamcroberts** [comment]
> Ok, I think this was because I created the token with tpm2_ptool (from master) so pkcs11-tool wasn't able to read it properly.
> This time I created a new store DB and the fist token with pkcs11-tool. It now reads it without problem. Thanks for your help!

Yep that'll do it.
