### ISSUE TITLE
 Loading certificate inside TPM

### ISSUE THREAD

**Issue by clem844** [tpm2-software/tpm2-pkcs11#544]
I am trying to load a certificate in the TPM through this command:
tpm2pkcs11-tool -l --pin $PIN --write-object "$device_dir/client.der" --type
cert --id 01 --label devicecert

I have tried with both .pem and .der format but it triggers the following error:
```
Using slot 0 with a present token (0x1)
ERROR: Expected attribute CKA_KEY_TYPE
error: PKCS11 function C_CreateObject failed: rv = CKR_TEMPLATE_INCOMPLETE (0xd0)
Aborting.
```

pkcs11-tool: v1.2.0

**Comment by williamcroberts** [comment]
What version is your pkcs11 library?
```
pkg-config --modversion tpm2-pkcs11
```
If you don't have it installed, you can either:
```bash
# this is the lib directory of the source tree if you check it out
export PKG_CONFIG_PATH="path/to/tpm2-pkcs11.pc"
```
or you can just give me git describe
```bash
git describe --always --dirty
```

**Comment by clem844** [comment]
I can't check it directly from the device as neither pkg-config nor git is installed. But from the sources downloaded by yocto I get
```
➜  tpm2-pkcs11 git:(master) ✗ git describe --always --dirty
5f26744-dirty
```

**Comment by williamcroberts** [comment]
Ok thanks. Ill look into the exact bug, I can probably reproduce off of master.
