### ISSUE TITLE
make install does not install tpm2_ptool

### ISSUE THREAD

**Issue by bnevis-i** [tpm2-software/tpm2-pkcs11#561]
Self explanatory.  `make install` doesn't install `tpm2_ptool`

**Comment by williamcroberts** [comment]
by design. Duplicate of #531. The [BUILDING.md](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/BUILDING.md#installing-tpm2_ptoolpy)  (on master) describes the steps for installing using something like pip.

Looks like it should have been added to INSTALLING.md
