### ISSUE TITLE
pkcs11-tools RSA keypair gen fails

### ISSUE THREAD

**Issue by bnevis-i** [tpm2-software/tpm2-pkcs11#565]
## Environment

Board: APL UPSquared with PTT
OS: Ubuntu 20.04 (opensc 0.20.0-3)
tpm2-tss: 4.2.1 (tarball)
tpm2-pkcs11: 1.3.1 (tarball)
tpm2-tools: 4.1.3 (tarball)
tpm2-abrmd: Not installed
Token initialized with tpm2_ptool with label tpmhsm

## Error message
```
id=`uuidgen | tr -d -`
pkcs11-tool --module /usr/lib/libtpm2_pkcs11.so --token-label tpmhsm --login --pin (redacted) --key-type rsa:2048 --id "$id" --keypairgen --mechanism RSA-PKCS-KEY-PAIR-GEN --label rsakey
ERROR: CKA_DERIVE=true not supported
ERROR: Failed checking private attrs
error: PKCS11 function C_GenerateKeyPair failed: rv = CKR_ATTRIBUTE_VALUE_INVALID (0x13)
Aborting.

```

Equivalent functionality works on softhsm and nitrokey hsm

**Comment by bnevis-i** [comment]
> I don't think the TPM can support derive. What version of pkcs11-tool are you using, CKA_DERIVE seems to be absent from the template on all the versions we have tested on. It seems to be opt-in via the `--derive` option.

pkcs11-tool is the version from opensc 0.20.0-3 in Ubuntu 20.04.  I have also tried setting OPENSC_DEBUG=9 and passing in --verbose flags, to no avail.  The first two ERROR lines are in libtpm2_pkcs11.so and the "error:" and "Aborting" match strings in /usr/bin/pkcs11-tool.

**Comment by williamcroberts** [comment]
We run our CI on ubuntu 20.04 and the pkcs11-tool seems to be creating RSA keys just fine... im not sure why it's adding derive flag... For example: https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/712261942#L3176

We use the below for generating rsa keys:
`pkcs11-tool -m <module> --slot-index=0 --label="myrsakey" --login --pin=mynewuserpin --keypairgen`

I wonder if it's becuase of the different key specifiers or mechanism.... they're fickle tools at times.

**Comment by bnevis-i** [comment]
With update TSS library and command line above, with a firmware TPM, I get:

```
Using slot 0 with a present token (0x1)
ERROR: Mechanism not supported, got: 0xd405600
Using signature algorithm RSA-X-509
```

(it seems to hang here)

**Comment by williamcroberts** [comment]
> With update TSS library and command line above, with a firmware TPM, I get:
> 
> ```
> Using slot 0 with a present token (0x1)
> ERROR: Mechanism not supported, got: 0xd405600

That's a weird mechanism... CKM_'s don't currently go that high. The highest I see is:
```C
#define CKM_EDDSA			(0x1057UL)
```
> Using signature algorithm RSA-X-509

If you're generating a key, why would it fall back to RSA-X-509.... The mechanism should be `CKM_RSA_PKCS_KEY_PAIR_GEN`
> ```
> 
> (it seems to hang here)

Weird... any way you can trace to the hang point?

**Comment by bnevis-i** [comment]
I learned something new.  This works:

```
/usr/bin/pkcs11-tool --module /usr/lib/libtpm2_pkcs11.so --token-label tpmhsm --login --pin (redacted) --mechanism RSA-PKCS-KEY-PAIR-GEN  --id (someid) --keypairgen --label rsakey3
Key pair generated:
Private Key Object; RSA 
  label:      rsakey3
  Usage:      decrypt, sign
  Access:     sensitive, always sensitive, never extractable, local
  Allowed mechanisms: RSA-X-509,RSA-PKCS-OAEP,RSA-PKCS,SHA1-RSA-PKCS,SHA256-RSA-PKCS,SHA384-RSA-PKCS,SHA512-RSA-PKCS,RSA-PKCS-PSS
Public Key Object; RSA 2048 bits
  label:      rsakey3
  Usage:      encrypt, verify
  Access:     local
```

Note that it seems to choose a 2048-bit key by default.

The problem seems to be when the --key-type flag is passed.

What syntax would I use to generate a 1024-bit RSA key?

Also, there is a disconnect between the supported mechanism for the key:
RSA-X-509,RSA-PKCS-OAEP,RSA-PKCS,SHA1-RSA-PKCS,SHA256-RSA-PKCS,SHA384-RSA-PKCS,SHA512-RSA-PKCS,RSA-PKCS-PSS

And what the token claims to support (pkcs11-tool -M)
```
  RIPEMD128-RSA-PKCS
  RSA-PKCS-KEY-PAIR-GEN, keySize={1024,2048}, hw, generate_key_pair
  RSA-X-509, keySize={1024,2048}, hw, encrypt, decrypt, sign, verify
  RSA-PKCS, keySize={1024,2048}, hw, encrypt, decrypt, sign, verify
  RSA-PKCS-OAEP, keySize={1024,2048}, hw, encrypt, decrypt
  SHA1-RSA-PKCS, keySize={1024,2048}, hw, sign, verify
  SHA256-RSA-PKCS, keySize={1024,2048}, hw, sign, verify
  ECDSA-KEY-PAIR-GEN, keySize={256,256}, hw, generate_key_pair
  ECDSA, keySize={256,256}, hw, sign, verify
  ECDSA-SHA1, keySize={256,256}, hw, sign, verify
  AES-KEY-GEN, keySize={16,16}, hw, generate
  AES-CBC, keySize={16,16}, hw, encrypt, decrypt
  mechtype-0x2107, keySize={16,16}, hw, encrypt, decrypt
  AES-ECB, keySize={16,16}, hw, encrypt, decrypt
  SHA-1, digest
  SHA256, digest
  SHA384, digest
```

**Comment by williamcroberts** [comment]
# First Half - Specifying option --key-type and setting key bit size
I'm looking through this more, looks like CKA_DERIVE=true is not what's set. Its an error in the output logging. After fixing that, we get something like:
```ERROR on line: "73" in file: "src/lib/key.c": Attribute 0x107=true not supported```

It seems that the tpm2-pkcs11 tool, adds wrap and unwrap implicitly:
```C
FILL_ATTR(publicKeyTemplate[n_pubkey_attr], CKA_WRAP, &_true, sizeof(_true));
n_pubkey_attr++;
FILL_ATTR(privateKeyTemplate[n_privkey_attr], CKA_UNWRAP, &_true, sizeof(_true));
n_privkey_attr++;
```

Applying the patch below allows the keygen --key-type option to work, but you create a key that doesn't really support `CKA_WRAP/UNWRAP` features... so technically its wrong. This is a sever limitation in the pkcs11-tool. You could try p11tool, i think it has better flexibility.

```diff
diff --git a/src/lib/key.c b/src/lib/key.c
index 2990c9030546..f1d85faabe16 100644
--- a/src/lib/key.c
+++ b/src/lib/key.c
@@ -70,7 +70,7 @@ static CK_RV handle_expect_false(CK_ATTRIBUTE_PTR attr,void *udata) {
     }
 
     if (value) {
-        LOGE("Attribute 0x%X=true not supported");
+        LOGE("Attribute 0x%X=true not supported", attr->type);
         return CKR_ATTRIBUTE_VALUE_INVALID;
     }
 
@@ -87,8 +87,8 @@ CK_RV check_common_attrs(
         { CKA_DERIVE,            handle_expect_false  },
         { CKA_SIGN_RECOVER,      handle_expect_false  },
         { CKA_VERIFY_RECOVER,    handle_expect_false  },
-        { CKA_UNWRAP,            handle_expect_false  },
-        { CKA_WRAP,              handle_expect_false  },
+//        { CKA_UNWRAP,            handle_expect_false  },
+//        { CKA_WRAP,              handle_expect_false  },
         { CKA_WRAP_WITH_TRUSTED, handle_expect_false  },
         { CKA_TRUSTED,           handle_expect_false  },
         { CKA_ALWAYS_AUTHENTICATE, handle_always_auth },
diff --git a/src/lib/tpm.c b/src/lib/tpm.c
index 8a2318c7750a..efbafe32fe6b 100644
--- a/src/lib/tpm.c
+++ b/src/lib/tpm.c
@@ -2533,9 +2533,9 @@ static const attr_handler tpm_handlers[] = {
     { CKA_EC_PARAMS,       handle_ecparams       },
     { CKA_KEY_TYPE,        handle_key_type       },
     { CKA_TRUSTED,           generic_bbool_false },
-    { CKA_WRAP_WITH_TRUSTED, generic_bbool_false },
-    { CKA_WRAP,              generic_bbool_false },
-    { CKA_UNWRAP,            generic_bbool_false },
+//    { CKA_WRAP_WITH_TRUSTED, generic_bbool_false },
+//    { CKA_WRAP,              generic_bbool_false },
+//    { CKA_UNWRAP,            generic_bbool_false },
     { CKA_SIGN_RECOVER,      generic_bbool_false },
     { CKA_VERIFY_RECOVER,    generic_bbool_false },
     { CKA_DERIVE,            generic_bbool_false },
```

You could try p11tool.... 

# Second Half - Mechanisms not matching

Theirs two parts to this, the first part is what I need to fix:
I need to fix a hardcode... 
https://github.com/tpm2-software/tpm2-pkcs11/blob/50d2a1563b3dadc1dc7e175f17d55f6951b963cd/src/lib/attrs.c#L874-L888

The second part of this is that the code just prints the algorithm without checking to see if it works...
```C
static void list_mechs(CK_SLOT_ID slot)
{
	CK_MECHANISM_TYPE	*mechs = NULL;
	CK_ULONG		n, num_mechs = 0;
	CK_RV			rv;

	num_mechs = get_mechanisms(slot, &mechs, -1);

	printf("Supported mechanisms:\n");
	for (n = 0; n < num_mechs; n++) {
		CK_MECHANISM_INFO info;

		printf("  %s", p11_mechanism_to_name(mechs[n]));
		rv = p11->C_GetMechanismInfo(slot, mechs[n], &info);
		if (rv == CKR_OK) {
			if (info.ulMinKeySize || info.ulMaxKeySize)   {
				printf(", keySize={");
				if (info.ulMinKeySize)
					printf("%li", info.ulMinKeySize);
				printf(",");
				if (info.ulMaxKeySize)
					printf("%li", info.ulMaxKeySize);
				printf("}");
			}
			if (info.flags & CKF_HW) {
				printf(", hw");
				info.flags &= ~CKF_HW;
			}
			if (info.flags & CKF_ENCRYPT) {
				printf(", encrypt");
				info.flags &= ~CKF_ENCRYPT;
			}
			if (info.flags & CKF_DECRYPT) {
				printf(", decrypt");
				info.flags &= ~CKF_DECRYPT;
			}
			if (info.flags & CKF_DIGEST) {
				printf(", digest");
				info.flags &= ~CKF_DIGEST;
			}
			if (info.flags & CKF_SIGN) {
				printf(", sign");
				info.flags &= ~CKF_SIGN;
			}
			if (info.flags & CKF_SIGN_RECOVER) {
				printf(", sign_recover");
				info.flags &= ~CKF_SIGN_RECOVER;
			}
			if (info.flags & CKF_VERIFY) {
				printf(", verify");
				info.flags &= ~CKF_VERIFY;
			}
			if (info.flags & CKF_VERIFY_RECOVER) {
				printf(", verify_recover");
				info.flags &= ~CKF_VERIFY_RECOVER;
			}
			if (info.flags & CKF_GENERATE) {
				printf(", generate");
				info.flags &= ~CKF_GENERATE;
			}
			if (info.flags & CKF_GENERATE_KEY_PAIR) {
				printf(", generate_key_pair");
				info.flags &= ~CKF_GENERATE_KEY_PAIR;
			}
			if (info.flags & CKF_WRAP) {
				printf(", wrap");
				info.flags &= ~CKF_WRAP;
			}
			if (info.flags & CKF_UNWRAP) {
				printf(", unwrap");
				info.flags &= ~CKF_UNWRAP;
			}
			if (info.flags & CKF_DERIVE) {
				printf(", derive");
				info.flags &= ~CKF_DERIVE;
			}
			if (info.flags)
				printf(", other flags=0x%x", (unsigned int) info.flags);
		}
		printf("\n");
	}

	if (mechs)
		free(mechs);
}
```

The remaining questions is, what do I do with CKA_WRAP and CKA_UNWRAP. We can just print a warning, but the code currently doesn't support WRAP and UNWRAP functionality, so I am not sure what to do here completely.

**Comment by williamcroberts** [comment]
@bnevis-i I'm looking through, is their anything left for me to do here?

**Comment by bnevis-i** [comment]
@williamcroberts 

Here is what I see as outstanding:

1. "I need to fix a hardcode..." -- was that done?
2. "The remaining questions is, what do I do with CKA_WRAP and CKA_UNWRAP. We can just print a warning, but the code currently doesn't support WRAP and UNWRAP functionality, so I am not sure what to do here completely." -- I don't know.  In order to comment I would need some deeper understanding on what the implications are of this, which I don't have.  I am looking to you.
3. Is this PKCS11 implementation supposed to be compatible enough that I can use pkcs11-tool to create an RSA key of specified length?   -- If so, I can try this again and post the command line that worked (or failed).
4. Is this PKCS11 implementation supposed to be compatible enough that I can use p11tool to create an RSA key of specified length?   -- If so, I can try this again and post the command line that worked (or failed).
5. If neither of above work, we should at least document the tpm pkcs11 utility that does it to wrap this up.

**Comment by williamcroberts** [comment]
> @williamcroberts
> 
> Here is what I see as outstanding:
> 
> 1. "I need to fix a hardcode..." -- was that done?

No, not yet. But it's unrelated to creating a key.

> 2. "The remaining questions is, what do I do with CKA_WRAP and CKA_UNWRAP. We can just print a warning, but the code currently doesn't support WRAP and UNWRAP functionality, so I am not sure what to do here completely." -- I don't know.  In order to comment I would need some deeper understanding on what the implications are of this, which I don't have.  I am looking to you.

I think we should fail loudly, considering the semantics of WRAP and UNWRAP. But I have a spec author in house @intel let me ask them.

> 3. Is this PKCS11 implementation supposed to be compatible enough that I can use pkcs11-tool to create an RSA key of specified length?   -- If so, I can try this again and post the command line that worked (or failed).

I don't have control over that tool, perhaps their is a way to do it, but I don't see how to get it to avoid adding in those CKA_WRAP and CKA_UNWRAP attributes. You could ask the OpenSC group that makes the tool.

> 4. Is this PKCS11 implementation supposed to be compatible enough that I can use p11tool to create an RSA key of specified length?   -- If so, I can try this again and post the command line that worked (or failed).

p11 works

```bash
p11tool --list-tokens
URL: pkcs11:model=SW%20%20%20TPM;manufacturer=IBM;serial=0000000000000000;token=label

token_url='pkcs11:model=SW%20%20%20TPM;manufacturer=IBM;serial=0000000000000000;token=label'
p11tool --generate-rsa --bits 2048 --login --label="myrsakey" --outfile=pubkey.pem "$token_url"
p11tool --generate-rsa --bits 1024 --login --label="myrsakey1" --outfile=pubkey1.pem "$token_url"

# Dump details to verify modulus is proper length
openssl pkey -inform PEM -pubin -text -in pubkey.pem
openssl pkey -inform PEM -pubin -text -in pubkey1.pem
```

You could also check out the link article where you can create things with the tpm directly and link it in.
https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/INTEROPERABILITY.md

This needs version 1.4.0+

> 5. If neither of above work, we should at least document the tpm pkcs11 utility that does it to wrap this up.

Outside of linking, their is also tpm2_ptool. We should add an option there as well to do it. 

### Conclusion
I think I need to follow up with:
- [ ] Can we ignore WRAP/UNWRAP
- [ ] Ensure a bug exists for the task getting tpm values into CKA_ALLOWED_MECHANISMS (future fix)

Then I can close this.

**Comment by bnevis-i** [comment]
I confirmed p11tool works and also tpm2_tool has addkey already which does the job too.  Plan of action looks good.

**Comment by williamcroberts** [comment]
> I confirmed p11tool works and also tpm2_tool has addkey already which does the job too. Plan of action looks good.

Oh yeah, my "keysize to tpm2_ptool" comment above is nonsense, the keysize is built into the algorithm selector:
  `--algorithm {rsa1024,rsa2048,aes128,aes256,ecc224,ecc256,ecc384,ecc521}`
So that's ready to go.

**Comment by williamcroberts** [comment]
So the follow up on what to do with the flags, it appears we can safely ignore them, but I will warn.

Per the knowledgeable person:
```
The spec describes the usage attributes as indicated whether a key supports (is allowed to be used for) something, not whether the token can implement all of the usages for which the key is supported. Seems to me there's room for a key to have a usage attribute value that will never be used since the API isn't supported.
```

So I will follow up with a LOGV/ignore on those flags

**Comment by williamcroberts** [comment]
@bnevis-i this PR should fix your usages with pkc11-tool (see example command in PR):
https://github.com/tpm2-software/tpm2-pkcs11/pull/598
