### ISSUE TITLE
Could not execute tpm2_createprimary: tpm2_createprimary: invalid option -- 'p'

### ISSUE THREAD

**Issue by oscarcreativeshop** [tpm2-software/tpm2-pkcs11#59]
Any advise? Looks like tpm2-tools for  tpm2_createprimary  does not have option -p but -P instead?..

$ tpm2_ptool.py init --pobj-pin=mypobjpin --path=~/tmp
Traceback (most recent call last):
  File "/home/user/Documents/tpm2-software/tpm2-pkcs11/tools/tpm2_ptool.py", line 686, in __call__
    ctx = tpm2.createprimary(ownerauth, pobjauth)
  File "/home/user/Documents/tpm2-software/tpm2-pkcs11/tools/tpm2_ptool.py", line 146, in createprimary
    raise RuntimeError("Could not execute tpm2_createprimary: %s" % stderr)
RuntimeError: Could not execute tpm2_createprimary: tpm2_createprimary: invalid option -- 'p'

Could not execute tpm2_createprimary: tpm2_createprimary: invalid option -- 'p'

$ tpm2_createprimary 
Usage: tpm2_createprimary [<options>]
Where <options> are:
    [ -H | --hierarchy=<value>] [ -P | --pwdp=<value>] [ -K | --pwdk=<value>] [ -g | --halg=<value>]
    [ -G | --kalg=<value>] [ -C | --context=<value>] [ -L | --policy-file=<value>] [ -A | --object-attributes=<value>]
    [ -S | --input-session-handle=<value>] [ - | --(null)]

**Comment by oscarcreativeshop** [comment]
Thanks..
Sorry for the confusion..

For tpm2-tools im using /master
For tpm2-pkc11 im also in master..

tpm2-tools$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

tpm2-pkcs11$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

Should I be using another branch?

Thanks
Oscar

**Comment by williamcroberts** [comment]
Fetch the projects and check status. Perhaps some of these were fixed.

**Comment by williamcroberts** [comment]
Oh and make sure you don't have tools installed, ie
```
which tpm2_create
```
Should be pointing to the ones you have in the tpm2-tools repo or if you installed them, to something like /usr/bin. You want to make sure that if you have 2 versions installed side-by-side that `PATH` when running the tpm2_ptool.py tool is using the master version.

Have you fixed this yet?
