### ISSUE TITLE
OpenSSL LOAD failed

### ISSUE THREAD

**Issue by clem844** [tpm2-software/tpm2-pkcs11#604]
I'm not sure if this issue belongs here.
In openssl engines documentation, there is this example ([source](https://github.com/openssl/openssl/blob/1dc1ea182be183d8a393fdce4494360aee059cd2/README-Engine.md)):
```
 ENGINE *e = ENGINE_by_id("dynamic");
 ENGINE_ctrl_cmd_string(e, "SO_PATH", "/lib/libfoo.so", 0);
 ENGINE_ctrl_cmd_string(e, "ID", "foo", 0);
 ENGINE_ctrl_cmd_string(e, "LOAD", NULL, 0);
 ENGINE_ctrl_cmd_string(e, "CMD_FOO", "some input data", 0);
```
For testing, the "openssl engine" utility can be useful for this sort of thing. For example the above code excerpt would achieve much the same result as;
```
 openssl engine dynamic \
           -pre SO_PATH:/lib/libfoo.so \
           -pre ID:foo \
           -pre LOAD \
           -pre "CMD_FOO:some input data"
```

If I use the 2nd example in the terminal it works
```
root@raspberrypi3:~# openssl engine dynamic \
                                    -pre SO_PATH:/usr/lib/engines-1.1/pkcs11.so \
                                    -pre ID:pkcs11 \
                                    -pre LIST_ADD:1 \
                                    -pre LOAD \
                                    -pre MODULE_PATH:/usr/lib/libtpm2_pkcs11.so.0
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/usr/lib/engines-1.1/pkcs11.so
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
[Success]: MODULE_PATH:/usr/lib/libtpm2_pkcs11.so.0
Loaded: (pkcs11) pkcs11 engine
```
However the code looks like the 1st example and tests the result for each call. The problem is that "LOAD" command is not working if called individually. The ` ENGINE_ctrl_cmd_string(e, "LOAD", NULL, 0);` returns an error. However the 2 examples are supposed to achieve the same result. Is it due to pkcs11 engine?

**Comment by williamcroberts** [comment]
This isn't an openssl engine. The pkcs11-engine, a separate project is what loads this up. Which I think is why the 2nd example works, you use that engine and point the MODULE_PATH to it.

**Comment by clem844** [comment]
Yes, from what I understand, it uses OpenSC libp11 (pkcs11-engine) to load the tpm2-pkcs11 module. As it works in command line, it should also in the code. Here is the code with the returned status:
```
 try {
    const boost::filesystem::path pkcs11Path = findPkcsLibrary();
    LOG_INFO << "Loading PKCS#11 engine library: " << pkcs11Path.string();
    if (ENGINE_ctrl_cmd_string(engine, "SO_PATH", pkcs11Path.c_str(), 0) == 0) {
      throw std::runtime_error(std::string("Engine command failed: SO_PATH ") + pkcs11Path.string());
    }

    if (ENGINE_ctrl_cmd_string(engine, "ID", "pkcs11", 0) == 0) {          // >> SUCESS
      throw std::runtime_error("Engine command failed: ID pksc11");   
    }

    if (ENGINE_ctrl_cmd_string(engine, "LIST_ADD", "1", 0) == 0) {        // >> SUCESS
      throw std::runtime_error("Engine command failed: LIST_ADD 1");    
    }

    if (ENGINE_ctrl_cmd_string(engine, "LOAD", nullptr, 0) == 0) {        // >> ERROR
      throw std::runtime_error("Engine command failed: LOAD");  
    }

    if (ENGINE_ctrl_cmd_string(engine, "MODULE_PATH", config_.module.c_str(), 0) == 0) {       // >> SUCCESS
      throw std::runtime_error(std::string("Engine command failed: MODULE_PATH ") + config_.module.string());
    }

    if (ENGINE_ctrl_cmd_string(engine, "PIN", config_.pass.c_str(), 0) == 0) {    // >> ERROR
      throw std::runtime_error(std::string("Engine command failed: PIN"));
    }

    if (ENGINE_init(engine) == 0) {
      throw std::runtime_error("Engine initialization failed");
    }
```
With:
`pkcs11Path.c_str()`= /usr/lib/engines-1.1/pkcs11.so
` config_.module.c_str()`= /usr/lib/libtpm2_pkcs11.so.0

It throws the error at LOAD but I tried them individually with GDB, hence the result for the next ones.

**Comment by williamcroberts** [comment]
> Yes, from what I understand, it uses OpenSC libp11 (pkcs11-engine) to load the tpm2-pkcs11 module. As it works in command line, it should also in the code. Here is the code with the returned status:
> 
> ```
>  try {
>     const boost::filesystem::path pkcs11Path = findPkcsLibrary();
>     LOG_INFO << "Loading PKCS#11 engine library: " << pkcs11Path.string();
>     if (ENGINE_ctrl_cmd_string(engine, "SO_PATH", pkcs11Path.c_str(), 0) == 0) {
>       throw std::runtime_error(std::string("Engine command failed: SO_PATH ") + pkcs11Path.string());
>     }
> 
>     if (ENGINE_ctrl_cmd_string(engine, "ID", "pkcs11", 0) == 0) {          // >> SUCESS
>       throw std::runtime_error("Engine command failed: ID pksc11");   
>     }
> 
>     if (ENGINE_ctrl_cmd_string(engine, "LIST_ADD", "1", 0) == 0) {        // >> SUCESS
>       throw std::runtime_error("Engine command failed: LIST_ADD 1");    
>     }
> 
>     if (ENGINE_ctrl_cmd_string(engine, "LOAD", nullptr, 0) == 0) {        // >> ERROR
>       throw std::runtime_error("Engine command failed: LOAD");  
>     }
> 
>     if (ENGINE_ctrl_cmd_string(engine, "MODULE_PATH", config_.module.c_str(), 0) == 0) {       // >> SUCCESS
>       throw std::runtime_error(std::string("Engine command failed: MODULE_PATH ") + config_.module.string());
>     }
> 
>     if (ENGINE_ctrl_cmd_string(engine, "PIN", config_.pass.c_str(), 0) == 0) {    // >> ERROR
>       throw std::runtime_error(std::string("Engine command failed: PIN"));
>     }
> 
>     if (ENGINE_init(engine) == 0) {
>       throw std::runtime_error("Engine initialization failed");
>     }
> ```
> 
> With:
> `pkcs11Path.c_str()`= /usr/lib/engines-1.1/pkcs11.so
> ` config_.module.c_str()`= /usr/lib/libtpm2_pkcs11.so.0
> 
> It throws the error at LOAD but I tried them individually with GDB, hence the result for the next ones.

Their are two parts to loading the tpm2-pkcs11 (this project) into OpenSSL. The first, you need the proxy loader that goes from the OpenSSL ENGINE interface to something that understands pkcs11. Next, you need a pkcs11 module. This project only provides the pkcs11 module. libp11 provides the proxy loader.

So you need the C code to load the openssl pkcs11-engine (provided by p11 https://github.com/OpenSC/libp11) and then configure that to load the tpm2-pkcs11 engine.
