### ISSUE TITLE
Recreating deleted DB

### ISSUE THREAD

**Issue by matthewbauer** [tpm2-software/tpm2-pkcs11#607]
Is it possible to recreate the tpm2_pkcs11.sqlite3 database?

My use case is a computer with no non-volatile memory. It boots from PXE on each startup, and loads everything in tmpfs. I'd like to be able to recover the TPM2 RSA key configured in https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/SSH.md after rebooting. My understanding is I should be able to just record a URL that looks like pkcs11:id=30383265376161663534326237313035;type=private;pin-value=userpin and recover the TPM2 key.

I don't see a way to do this though (at least in the format expected by tpm2-pkcs11 db). Ideally the flow would be something like:

```
tpm2_ptool init --url pkcs11:id=30383265376161663534326237313035;type=private;pin-value=userpin
```

It would be nice if the value was independent of machine, so I could put something like this in my bashrc for all machines:

```
[ -d $HOME/.tpm2_pkcs11 ] || tpm2_ptool init --url pkcs11:id=30383265376161663534326237313035;type=private;pin-value=userpin
```

(with different ssh keys for each machine of course)

**Comment by williamcroberts** [comment]
I created #611 to capture the feature request, closing this ticket.
