### ISSUE TITLE
Creating SSH keys without a PIN

### ISSUE THREAD

**Issue by mjj29** [tpm2-software/tpm2-pkcs11#629]
Hi, I'm trying to use this as an option to secure SSH keys that would be passwordless - for automated tasks. Binding to the machine in the TPM so they can't be unsealed is better than not. However, I still need to be able to use them in an automated context, so I need SSH not to prompt for a PIN. Looking at the SSH source that should be possible. I _think_ I need to create a token without a userpin, but I don't think I can currently do this. Can you please advise?

Thanks,
Matt

**Comment by williamcroberts** [comment]
We'll theirs two things here. If you bind a key to a PCR value, you still need to satisfy that policy during use. We do not have support for satisfying policies this currently. This deficiency is captured as bug #301.

For a passwordless pin, you might be able to:
- Use expect command in a script to send the empty pin when prompted.
- set up ssh to get all the data it needs from the config file perhaps, like (not sure if this is possible):
  - https://ruimarinho.gitbooks.io/yubikey-handbook/content/ssh/authenticating-ssh-with-piv-and-pkcs11-client/

**Comment by mjj29** [comment]
On Mon Dec 07 10:59, William Roberts wrote:
> We'll theirs two things here. If you bind a key to a PCR value, you still need to satisfy that policy during use. We do not have support for satisfying policies this currently. This deficiency is captured as bug #301.
> 
> For a passwordless pin, you might be able to:
> - Use expect command in a script to send the empty pin when prompted.
> - set up ssh to get all the data it needs from the config file perhaps, like (not sure if this is possible):
>   - https://ruimarinho.gitbooks.io/yubikey-handbook/content/ssh/authenticating-ssh-with-piv-and-pkcs11-client/

Ah, expect was the name I was forgetting.

When I looked at the openssh source it seems to check if a PIN exists
and then always prompt for the password if it does, no way to provide it
via config etc. That did suggest it was possible to create one without a
PIN though, but your tool didn't allow that. I did try and work out if I
could come up with the underlying tool commands to do so, but it's so
frigging complicated.

Matt

**Comment by diabonas** [comment]
The [PKCS#11 specification](https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html) has `CKF_PROTECTED_AUTHENTICATION_PATH`, which could be used to achieve passwordless logins:
> If the token has a “protected authentication path”, as indicated by the **CKF_PROTECTED_AUTHENTICATION_PATH** flag in its **CK_TOKEN_INFO** being set, then that means that there is some way for a user to be authenticated to the token without having to send a PIN through the Cryptoki library.  One such possibility is that the user enters a PIN on a PIN pad on the token itself, or on the slot device.  Or the user might not even use a PIN—authentication could be achieved by some fingerprint-reading device, for example.  To log into a token with a protected authentication path, the *pPin* parameter to **C_Login** should be NULL_PTR.  When **C_Login** returns, whatever authentication method supported by the token will have been performed; a return value of CKR_OK means that the user was successfully authenticated, and a return value of **CKR_PIN_INCORRECT** means that the user was denied access.

It is possible to extend tpm2-pkcs11 to set this flag, probably guarded by a per-token option. Conforming software will then skip asking for the PIN, passing a null pointer instead (which tpm2-pkcs11 would have to modified to interpret as an empty PIN). This works e.g. for the [`ssh` executable](https://github.com/openssh/openssh-portable/blob/19af04e2231155d513e24fdc81fbec2217ae36a6/ssh-pkcs11.c#L260-L273), but *not* when [using `ssh-add`](https://github.com/openssh/openssh-portable/blob/816036f142ecd284c12bb3685ae316a68d2ef190/ssh-add.c#L453-L457) for working with an SSH agent. Also keep in mind that `CKF_PROTECTED_AUTHENTICATION_PATH` means that both user and SO PIN need to be empty, the PKCS#11 specification does not have any distinction between these two regarding authentication.

**Comment by williamcroberts** [comment]
> On Mon Dec 07 10:59, William Roberts wrote: We'll theirs two things here. If you bind a key to a PCR value, you still need to satisfy that policy during use. We do not have support for satisfying policies this currently. This deficiency is captured as bug #301. For a passwordless pin, you might be able to: - Use expect command in a script to send the empty pin when prompted. - set up ssh to get all the data it needs from the config file perhaps, like (not sure if this is possible): - https://ruimarinho.gitbooks.io/yubikey-handbook/content/ssh/authenticating-ssh-with-piv-and-pkcs11-client/
> Ah, expect was the name I was forgetting. When I looked at the openssh source it seems to check if a PIN exists and then always prompt for the password if it does, no way to provide it via config etc. That did suggest it was possible to create one without a PIN though, but your tool didn't allow that. I did try and work out if I could come up with the underlying tool commands to do so, but it's so frigging complicated. Matt

Isn't empty the same as hardcoding 1234 in the expect script?

**Comment by williamcroberts** [comment]
> CKF_PROTECTED_AUTHENTICATION_PATH

Interesting, yeah we could probably do something like this as well as allow tpm2_ptool to allow empty pin's. I would imagine that pkcs11-tool would already allow an empty pin, but getting the prompt to skip would be nice.

**Comment by williamcroberts** [comment]
So lets keep this ticket open as a feature request for:
1. tpm2_ptool to allow empty pins
2. tpm2_ptool to allow setting the CKF_PROTECTED_PATH
  * Question, is their an interface for changing this attribute via PKCS11 or is it "baked into the card".
3. testing the CKF_PROTECTED_PATH scenario.

**Comment by diabonas** [comment]
> Question, is their an interface for changing this attribute via PKCS11 or is it "baked into the card".

As far as I am aware there is no PKCS#11 interface for changing the flag, so we'd have to use `tpm2_ptool config` for that.

**Comment by niooss-ledger** [comment]
Hello,
I am interested in this feature, in order to advocate using TPM to store SSH keys :)

As using `CKF_PROTECTED_PATH` felt a bit too hackish to me (OpenSSH would display "Deferring PIN entry to reader keypad." for example, https://github.com/openssh/openssh-portable/blob/V_8_6_P1/ssh-pkcs11.c#L260-L261), I explored using `!CKF_LOGIN_REQUIRED` instead. This felt cleaner because this really means "this token can be used without login", and OpenSSH does not invoke `C_Login` in the first place (https://github.com/openssh/openssh-portable/blob/V_8_6_P1/ssh-pkcs11.c#L367).

Here is a work-in-progress patch on current master (commit 2b693a16cdfb34f623f984b09006b3fe07e963b9) which:

* adds a config option `empty-user-pin` to the token configuration, which is set when `tpm2_ptool addtoken` is used with `--userpin=""`,
* only sets `CKF_LOGIN_REQUIRED` when this option is false,
* enables using private keys and `C_SignInit` without login.

With this, OpenSSH works fine: I am able to log in without any prompt, and with a key used by the TPM. Before submitting a proper Pull Request, more works need to be done (`empty-user-pin` needs to be set/reset in more places, the version of the database would likely need to be bumped, the tests need to be run...).

Before starting such work, I would like some feedback on my approach. What do you think? Should I continue working on this or would you prefer another way?

The patch:
```patch
From 6b78743e4e1f2c98957c6d4590db15b9a8ae2fa9 Mon Sep 17 00:00:00 2001
From: Nicolas Iooss <nicolas.iooss@ledger.fr>
Date: Thu, 20 May 2021 18:42:00 +0200
Subject: [PATCH 1/1] token: enable using objetcs with no user PIN

Signed-off-by: Nicolas Iooss <nicolas.iooss@ledger.fr>
---
 src/lib/emitter.c                      | 20 ++++++++++++++++++++
 src/lib/object.c                       |  4 ++--
 src/lib/parser.c                       |  3 +++
 src/lib/token.c                        | 25 +++++++++++++++++++++----
 src/lib/token.h                        |  1 +
 src/pkcs11.c                           |  6 ++++++
 tools/tpm2_pkcs11/commandlets_keys.py  | 10 +++++++++-
 tools/tpm2_pkcs11/commandlets_token.py |  2 ++
 8 files changed, 64 insertions(+), 7 deletions(-)

diff --git a/src/lib/emitter.c b/src/lib/emitter.c
index 60cb508e986b..33ba964241d5 100644
--- a/src/lib/emitter.c
+++ b/src/lib/emitter.c
@@ -328,6 +328,26 @@ WEAK char *emit_config_to_string(token *t) {
         }
     }
 
+    /* add config value empty user PIN, if set */
+    if (t->config.empty_user_pin) {
+        key = yaml_document_add_scalar(&doc, (yaml_char_t *)YAML_STR_TAG,
+             (yaml_char_t *)"empty-user-pin", -1, YAML_ANY_SCALAR_STYLE);
+        if (!key) {
+            LOGE("yaml_document_add_scalar for key failed");
+            goto doc_delete;
+        }
+
+        int node = yaml_document_add_scalar(&doc, (yaml_char_t *)YAML_BOOL_TAG,
+             (yaml_char_t *)"true", -1, YAML_ANY_SCALAR_STYLE);
+
+        rc = yaml_document_append_mapping_pair(&doc,
+                root, key, node);
+        if (!rc) {
+            LOGE("yaml_document_append_mapping_pair failed");
+            goto doc_delete;
+        }
+    }
+
     yaml_emitter_t emitter = { 0 };
 
     /* dummy dump the yaml to get size */
diff --git a/src/lib/object.c b/src/lib/object.c
index 7fa7f11dc213..4a190c149508 100644
--- a/src/lib/object.c
+++ b/src/lib/object.c
@@ -393,8 +393,8 @@ CK_RV object_find(session_ctx *ctx, CK_OBJECT_HANDLE *object, CK_ULONG max_objec
         // Get the current object, and grab it's id for the object handle
         CK_OBJECT_HANDLE handle = opdata->cur->tobj_handle;
 
-        // filter out CKA_PRIVATE set to CK_TRUE if not logged in
-        if (opdata->cur->cka_private && !token_is_user_logged_in(tok)) {
+        // filter out CKA_PRIVATE set to CK_TRUE if not logged in and PIN is needed
+        if (opdata->cur->cka_private && !token_is_user_logged_in(tok) && !tok->config.empty_user_pin) {
             opdata->cur = opdata->cur->next;
             continue;
         }
diff --git a/src/lib/parser.c b/src/lib/parser.c
index 229e51b89a3b..5985dc1e14e6 100644
--- a/src/lib/parser.c
+++ b/src/lib/parser.c
@@ -436,6 +436,9 @@ bool handle_token_config_event(yaml_event_t *e,
             } else if(!strcmp(state->key, "pss-sigs-good")) {
                 config->pss_sigs_good = !strcmp((const char *)e->data.scalar.value, "true")
                         ? pss_config_state_good : pss_config_state_bad;
+            } else if(!strcmp(state->key, "empty-user-pin")) {
+                config->empty_user_pin = !strcmp((const char *)e->data.scalar.value, "true")
+                        ? true : false;
             } else {
                 LOGE("Unknown key, got: \"%s\"\n",
                         state->key);
diff --git a/src/lib/token.c b/src/lib/token.c
index 63a9a71b2882..298cc788f2b5 100644
--- a/src/lib/token.c
+++ b/src/lib/token.c
@@ -310,8 +310,11 @@ CK_RV token_get_info (token *t, CK_TOKEN_INFO *info) {
     }
 
     // Support Flags
-    info->flags = CKF_RNG
-        | CKF_LOGIN_REQUIRED;
+    info->flags = CKF_RNG;
+
+    if (!t->config.empty_user_pin) {
+        info->flags |= CKF_LOGIN_REQUIRED;
+    }
 
     if (t->config.is_initialized) {
         info->flags |= CKF_TOKEN_INITIALIZED;
@@ -536,10 +539,24 @@ out:
 }
 
 CK_RV token_load_object(token *tok, CK_OBJECT_HANDLE key, tobject **loaded_tobj) {
-
+    CK_RV rv;
     tpm_ctx *tpm = tok->tctx;
 
-    CK_RV rv = token_find_tobject(tok, key, loaded_tobj);
+    /* Unseal the wrapping key, if the user PIN is empty */
+    if (!tok->wrappingkey && tok->config.empty_user_pin) {
+        twist tpin = twistbin_new("", 0);
+        if (!tpin) {
+            return CKR_HOST_MEMORY;
+        }
+        rv = backend_token_unseal_wrapping_key(tok, true, tpin);
+        twist_free(tpin);
+        if (rv != CKR_OK) {
+            LOGE("Error unsealing wrapping key");
+            return rv;
+        }
+    }
+
+    rv = token_find_tobject(tok, key, loaded_tobj);
     if (rv != CKR_OK) {
         return rv;
     }
diff --git a/src/lib/token.h b/src/lib/token.h
index d5d9386e5079..e7f813dc5857 100644
--- a/src/lib/token.h
+++ b/src/lib/token.h
@@ -22,6 +22,7 @@ struct token_config {
     bool is_initialized;  /* token initialization state */
     char *tcti;           /* token specific tcti config */
     pss_config_state pss_sigs_good;
+    bool empty_user_pin;  /* user PIN of the token is empty */
 };
 
 typedef struct session_table session_table;
diff --git a/src/pkcs11.c b/src/pkcs11.c
index 89d9b8687a91..bbf5581dfb49 100644
--- a/src/pkcs11.c
+++ b/src/pkcs11.c
@@ -272,6 +272,12 @@ static inline CK_RV auth_min_ro_user(session_ctx *ctx) {
         /* no default */
     }
 
+    /* If the token does not require a PIN, allow calling the function */
+    token *t = session_ctx_get_token(ctx);
+    if (t && t->config.empty_user_pin) {
+        fprintf(stderr, "auth_min_ro_user: bypass because empty PIN\n");
+        return CKR_OK;
+    }
     return CKR_USER_NOT_LOGGED_IN;
 }
 
diff --git a/tools/tpm2_pkcs11/commandlets_keys.py b/tools/tpm2_pkcs11/commandlets_keys.py
index 980fa78927fa..2ef10387fc3d 100644
--- a/tools/tpm2_pkcs11/commandlets_keys.py
+++ b/tools/tpm2_pkcs11/commandlets_keys.py
@@ -54,7 +54,7 @@ class NewKeyCommandBase(Command):
             '--hierarchy-auth',
             help='The hierarchyauth, required for transient pobjects.\n',
             default='')
-        pinopts = group_parser.add_mutually_exclusive_group(required=True)
+        pinopts = group_parser.add_mutually_exclusive_group()
         pinopts.add_argument('--sopin', help='The Administrator pin.\n'),
         pinopts.add_argument('--userpin', help='The User pin.\n'),
 
@@ -178,6 +178,14 @@ class NewKeyCommandBase(Command):
                 pobjectid = token['pid']
                 pobj = db.getprimary(pobjectid)
 
+                if userpin is None and sopin is None:
+                    # Use empty PIN if the token has an empty user PIN
+                    token_config = yaml.safe_load(io.StringIO(token['config']))
+                    if token_config.get('empty-user-pin'):
+                        userpin = ''
+                    else:
+                        sys.exit('error: one of the arguments --sopin --userpin is required')
+
                 sealobjects = db.getsealobject(token['id'])
 
                 encobjauth, objauth = self.new_key_init(
diff --git a/tools/tpm2_pkcs11/commandlets_token.py b/tools/tpm2_pkcs11/commandlets_token.py
index febaaf85d93e..917a914d78f4 100644
--- a/tools/tpm2_pkcs11/commandlets_token.py
+++ b/tools/tpm2_pkcs11/commandlets_token.py
@@ -263,6 +263,8 @@ class AddTokenCommand(Command):
                 'token-init': True,
                 'pss-sigs-good' : pss_sig_good
             }
+            if userpin == '':
+                config['empty-user-pin'] = True
             tokid = db.addtoken(pobject['id'], config, label=label)
 
             # now we update the sealobject table with the tokid to seal objects mapping
-- 
2.30.2
```

**Comment by diabonas** [comment]
I like this approach! I'm afraid `ssh-add` [will still always ask for password](https://github.com/tpm2-software/tpm2-pkcs11/issues/629#issuecomment-740623188) (though I haven't tested it), but that is certainly not the fault of your approach: using `CKF_LOGIN_REQUIRED` instead of `CKF_PROTECTED_AUTHENTICATION_PATH` seems indeed like the cleaner solution.

**Comment by williamcroberts** [comment]
LGTM
