### ISSUE TITLE
twist.c is not automatically recompiled when enabling unit tests

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-pkcs11#63]
Currently, if unit tests are not enabled during the initial configure run, but activated later, [`src/lib/twist.c`](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/src/lib/twist.c) is not recompiled automatically by `make` or `make check`. This causes the unit tests to fail because the necessary [`#ifdef UNIT_TESTING` block](https://github.com/tpm2-software/tpm2-pkcs11/blob/1c2dee607ac2a39971a9530940ffcc92761bb4ba/src/lib/twist.c#L18) is not included in the compiled file. For example, a sequence like

```
git clone https://github.com/tpm2-software/tpm2-pkcs11.git
cd tpm2-pkcs11
./bootstrap
./configure
make
./configure --enable-unit
make
make check
```

fails with the error

```
make   test/unit/test_twist
make[1]: Entering directory '/home/jonas/tpm2-pkcs11'
  CC       test/unit/test_twist-test_twist.o
  CCLD     test/unit/test_twist
/usr/bin/ld: test/unit/test_twist-test_twist.o: in function `test_twist_new_bad_alloc':
test_twist.c:(.text.test_twist_new_bad_alloc+0x15): undefined reference to `twist_next_alloc_fails'
/usr/bin/ld: test/unit/test_twist-test_twist.o: in function `test_twist_append_bad_alloc':
test_twist.c:(.text.test_twist_append_bad_alloc+0x40): undefined reference to `twist_next_alloc_fails'
/usr/bin/ld: test/unit/test_twist-test_twist.o: in function `test_twist_truncate_bigger_bad_alloc':
test_twist.c:(.text.test_twist_truncate_bigger_bad_alloc+0x4c): undefined reference to `twist_next_alloc_fails'
/usr/bin/ld: test/unit/test_twist-test_twist.o: in function `test_twist_unhexlify_failed_alloc':
test_twist.c:(.text.test_twist_unhexlify_failed_alloc+0x15): undefined reference to `twist_next_alloc_fails'
/usr/bin/ld: test/unit/test_twist-test_twist.o: in function `test_twist_hexlify_alloc_fail':
test_twist.c:(.text.test_twist_hexlify_alloc_fail+0x34): undefined reference to `twist_next_alloc_fails'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1196: test/unit/test_twist] Error 1
make[1]: Leaving directory '/home/jonas/tpm2-pkcs11'
make: *** [Makefile:1929: check-am] Error 2
```

You need to e.g. `touch src/lib/twist.c` after the second `configure` to force recompilation, afterwards `make check` passes.

I do not know whether there is a good way to achieve automatic recompilation when this configure option changes using Autotools, but I at least wanted to document this behaviour.

**Comment by williamcroberts** [comment]
Good to know, I am not sure of a way to do that either. I always do a make distclean when I switch configure options.

Maybe add it to a markdown file in docs, maybe https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/BUILDING.md?
