### ISSUE TITLE
Cannot use certificate imported in tpm

### ISSUE THREAD

**Issue by HumanoidPhantom** [tpm2-software/tpm2-pkcs11#631]
Hi!

I have tpm2-pkcs11-1.2.0 installed on Ubuntu 20.04. It is not possible to use certificate, imported in tpm. The following command fails:
```
openssl s_client -engine pkcs11 -keyform engine -key "pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=private" -cert "pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=cert" -connect example.com:443 -servername example.com -state -debug
engine "pkcs11" set.

Can't open pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=cert for reading, No such file or directory
139743449638208:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=cert','r')
139743449638208:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load certificate
```

When I specify path to the certificate on file system, everything works as expected:
```
openssl s_client -engine pkcs11 -keyform engine -key "pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=private" -cert test.crt -connect example.com:443 -servername example.com -state -debug
```

The same happens if I test with openconnect, curl or any other application.

Certificate was imported the following way:
```
$ tpm2_ptool addcert --label test --key-label=test-RSA2048-keypair --path=${TPM2_PKCS11_STORE} test.crt
```
tpm2pkcs11-tool shows imported certificate:
```
tpm2pkcs11-tool --list-objects --slot 1
...
Certificate Object; type = X.509 cert
  label:      test-RSA2048-keypair
  subject:    DN: O=Example, CN=Test$
  ID:         3031
```

Can you please advise what might be the problem?

**Comment by williamcroberts** [comment]
Well it says it cant open the certificate, which I think it's trying to open it as a file and not use it as a pkcs11 url. Looking at the manpage:
```bash
openssl help s_client 2>&1 | grep -- -cert
 -cert infile               Certificate file to use, PEM format assumed
```

It says *certificate file*, so I don't think OpenSSL knows how to get at it through pkcs11, only via files.

**Comment by HumanoidPhantom** [comment]
My bad, looks like you are right regarding openssl, there is no -certform "engine".

However, certificate imported in tpm still does not work in case of openconnect or curl. In both tools I can use certificate located on filesystem, but cannot use certificate in tpm. I also tested with Yubikey, and in both tools it is okay to specify pkcs11 URI parameter for certificate parameter. 

For example curl, it works fine with certificate on filesystem and key in tpm:
```
$ curl --key "pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=private" --cert ~/test.crt -I https://test.example.com
```

It does not work if just certificate located in tpm provided:
```
$ curl --cert "pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=cert" https://test.example.com
```

To make sure that `curl` "--cert" parameter works with pkcs11 URI, I've tested the same with Yubikey:
```
$ curl --cert "pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;token=test;id=%01;object=Certificate%20for%20PIV%20Authentication;type=cert" https://test.example.com
```

**Comment by williamcroberts** [comment]
Whats the error curl issues?

**Comment by HumanoidPhantom** [comment]
After reviewing logs on server side (where I'm connecting via curl), I've seen the following:
```
client SSL certificate verify error: (7:certificate signature failure) while reading client request headers,
```
I've also noticed the difference between client certificates - the original one, located on filesystem, and the certificate that was imported in TPM.

The steps are the following:
1. Import test.crt certificate via the following command:
```
$ tpm2_ptool addcert --label test --key-label=test-RSA2048-keypair --path=${TPM2_PKCS11_STORE} test.crt
```
2. I did not find a way to export certificate from TPM directly, so I used Nginx and logged ssl_client_escaped_cert
3. Send request using curl to this server with imported certificate
```
$ curl --cert "pkcs11:model=NPCT75x;manufacturer=Nuvoton;serial=0000000000000000;token=test;id=%30%31;object=test-RSA2048-keypair;type=cert" -v -I https://test.example.com 
``` 
4. URL-decode the certificate, that was logged on Nginx
5. Compare certificate from step (4) and original test.crt certificate

For me the difference was the following:
* \n instead of \r\n in the original - does not look like an issue
* difference in two bytes:
```
index TPM test.crt      
1688  81  102
1689  69  56
``` 

Unfortunately, I cannot post the certificate here, but it looks like the difference in these two bytes was caused by certificate import in TPM.

**Comment by HumanoidPhantom** [comment]
I found the way to export certificate from TPM, so the steps are the following:
1. Import test.crt certificate via the following command:
```
$ tpm2_ptool addcert --label test --key-label=test-RSA2048-keypair --path=${TPM2_PKCS11_STORE} test.crt
```
2. Export certificate from TPM and convert it to PEM format:
```
$ tpm2_ptool objmod --id 3 --key 17 | cut -d " " -f2 | xxd -r -p | openssl x509 -inform DER -out fromtpm.crt
```
3. Compare certificates. For me the difference is the same as described in the previous comment

**Comment by HumanoidPhantom** [comment]
Can you please clarify why the certificate is different after TPM import-export round trip? I believe this difference eventually makes it impossible for Nginx to verify the certificate

**Comment by williamcroberts** [comment]
> Can you please clarify why the certificate is different after TPM import-export round trip? I believe this difference eventually makes it impossible for Nginx to verify the certificate

I dunno, haven't had time to look into it. But I would have OpenSSL dump the public key info and verify that all that is the same. Because the error is "certificate signature failure". Which, I would imagine, would mean the key used for sign != cert. Perhaps you have different certs in the PKCS11_STORE that the URL is mapping to. I would also try a sign and verify with openssl using the respective private and public key PKCS11 URL's and just make sure that works.

**Comment by HumanoidPhantom** [comment]
I'm sure that the URL maps to the correct certificate, since the difference between certificates on file system and in TPM is only two bytes, and in Nginx logs I see that the same certificate was used.

I've just repeated the steps with self-signed certificate, so it would be more clear:
```
$ tpm2pkcs11-tool --label="test-keypair" --login --keypairgen
$ openssl req -engine pkcs11 -keyform engine -key "pkcs11:token=test;object=test-keypair;type=private" -new -x509 -days 365 -out test.crt -nodes -subj '/CN=test'
$ tpm2_ptool addcert --label test --key-label=test-keypair test.crt
action: add
cert:
  CKA_ID: ''
$ tpm2pkcs11-tool --list-objects --slot 1
Public Key Object; RSA 2048 bits
  label:      test-keypair
  Usage:      encrypt, verify
  Access:     local
Certificate Object; type = X.509 cert
  label:      test-keypair
  subject:    DN: CN=test
$ tpm2_ptool objmod --id 6 --key 17 | cut -d " " -f2 | xxd -r -p | openssl x509 -inform DER -out fromtpm.crt
$ diff test.crt fromtpm.crt
12c12
< BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCjNCFoOeC766Vcxvmr
---
> BgNVHRMBAQEEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCjNCFoOeC766Vcxvmr
```
You can see, that in test.crt (original) there is BgNVHRMBA**f8**.. and in fromtpm.crt there is BgNVHRMBA**QE**..

**Comment by williamcroberts** [comment]
I just did it with no diff output, so you're getting different things, likely have multiple stores. I attached my script so you can run it.

[test.sh.txt](https://github.com/tpm2-software/tpm2-pkcs11/files/5618825/test.sh.txt)

The search logic can be tricky, because by default it puts a store in ~/.tpm2_pkcs11. So one can run awry if you're not careful with env var TPM2_PKCS11_STORE and tpm2_ptool using --path. If you don't have a $HOME it will default to $(CWD).

At one point in time I remember a bug in the search logic, so that could also be affecting you.

**Comment by HumanoidPhantom** [comment]
As far as I can see, it is not related to store location, and I have TPM2_PKCS11_STORE var set. 

As a workaround I found that it is possible to change key value manually and set the correct one:
```
$ tpm_cert=$(cat "test.crt" | openssl x509 -inform PEM -outform DER | xxd -p | tr -d \\n)
$ tpm2_ptool objmod --key 17 --id 3 --value "${tpm_cert}" --type raw
```
After this I am able to use certificate from TPM with openconnect, curl, etc. 

However, it still does not work in browsers (tested in Firefox, Chrome). I prompted by browser to provide TPM PIN, but certificate is not sent to the server, as per Nginx logs. I'm trying to figure out what might be the reason. Has this setup with client certificate in TPM been tested with browsers?

**Comment by williamcroberts** [comment]
> As far as I can see, it is not related to store location, and I have TPM2_PKCS11_STORE var set.

How do you verify that?

> 
> As a workaround I found that it is possible to change key value manually and set the correct one:
> 
> ```
> $ tpm_cert=$(cat "test.crt" | openssl x509 -inform PEM -outform DER | xxd -p | tr -d \\n)
> $ tpm2_ptool objmod --key 17 --id 3 --value "${tpm_cert}" --type raw
> ```
> 
> After this I am able to use certificate from TPM with openconnect, curl, etc.
> 
> However, it still does not work in browsers (tested in Firefox, Chrome). I prompted by browser to provide TPM PIN, but certificate is not sent to the server, as per Nginx logs. I'm trying to figure out what might be the reason. Has this setup with client certificate in TPM been tested with browsers?

I personally have not tested it in browsers, but I have had successful reports.

**Comment by williamcroberts** [comment]
But this has been used for SSL connections, NSS in our integration tests. We have also had successful VPN deployments. I don't think any of that would work if their was an issue with certificates getting mangled. I guess I could add that script I wrote the other day and make sure it's in the integration tests just to make sure when I deploy across all of the docker images, it works. Just to rule that the bug manifests on a different platform.

**Comment by HumanoidPhantom** [comment]
I've updated to tpm2-pkcs11-1.5.0. There are still issues with certificate import, but with the steps described [previously](https://github.com/tpm2-software/tpm2-pkcs11/issues/631#issuecomment-736596060) browsers started to work. 

> I don't think any of that would work if their was an issue with certificates getting mangled. 

Certificate was issued by Windows CA (containing UPN extension), probably it is somehow related.

Closing this issue since everything works fine now with the [workaround](https://github.com/tpm2-software/tpm2-pkcs11/issues/631#issuecomment-736596060). 

Thanks for your help

**Comment by h3po** [comment]
@williamcroberts  I currently have the same issue with the certificate getting mangled in v1.6.0 - please consider retesting this. In my case one byte in the signed part of the cert is being flipped from 0x01 to 0xff.

**Comment by williamcroberts** [comment]
The problem is we need to go from PEM to DER IIUC, I guess I can just b64decode IIRC and not use the libraries except for extracting things.

**Comment by niooss-ledger** [comment]
> ```
> $ diff test.crt fromtpm.crt
> 12c12
> < BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCjNCFoOeC766Vcxvmr
> ---
> > BgNVHRMBAQEEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCjNCFoOeC766Vcxvmr
> ```
> You can see, that in test.crt (original) there is BgNVHRMBAf8.. and in fromtpm.crt there is BgNVHRMBAQE..

The hexadecimal dump of the first bytes are:
```
< 06 03 55 1d 13 01 01 ff 04 05 30 03 01 01 ff 30 ...
> 06 03 55 1d 13 01 01 01 04 05 30 03 01 01 ff 30 ...
```

A boolean value got trans-coded from `01 01 ff` to `01 01 01`. Both encoding actually mean "true". In pyasn1 (the library used by tpm2-pkcs11 to decode and encode certificates), the BER encoding uses `1` (https://github.com/etingof/pyasn1/blob/db8f1a7930c6b5826357646746337dafc983f953/pyasn1/codec/ber/encoder.py#L163-L164) while the DER one uses `0xff` (https://github.com/etingof/pyasn1/blob/db8f1a7930c6b5826357646746337dafc983f953/pyasn1/codec/cer/encoder.py#L16-L22). So the issue is that `tpm2_ptool addcert` re-encodes the certificates in https://github.com/tpm2-software/tpm2-pkcs11/blob/c5533e68eb3b6c1285b3eccfddfcd01833dce6c2/tools/tpm2_pkcs11/utils.py#L261-L264

> The problem is we need to go from PEM to DER IIUC, I guess I can just b64decode IIRC and not use the libraries except for extracting things.

This is already what function `pemcert_to_attrs` does in https://github.com/tpm2-software/tpm2-pkcs11/blob/c5533e68eb3b6c1285b3eccfddfcd01833dce6c2/tools/tpm2_pkcs11/utils.py#L252-L253

The variable `substrate` contains the DER-encoded certificate, base64-decoded from the PEM file. Could you please take a look at PR https://github.com/tpm2-software/tpm2-pkcs11/pull/729 which fixes this issue? This PR also provides a test case, which creates certificates with booleans (the ones generated through `openssl req` do not include booleans by default but some fields can be added when using an OpenSSL configuration file)

**Comment by kuhlmannmarkus** [comment]
> As far as I can see, it is not related to store location, and I have TPM2_PKCS11_STORE var set.
> 
> As a workaround I found that it is possible to change key value manually and set the correct one:
> 
> ```
> $ tpm_cert=$(cat "test.crt" | openssl x509 -inform PEM -outform DER | xxd -p | tr -d \\n)
> $ tpm2_ptool objmod --key 17 --id 3 --value "${tpm_cert}" --type raw
> ```
> 
> After this I am able to use certificate from TPM with openconnect, curl, etc.
> 
> However, it still does not work in browsers (tested in Firefox, Chrome). I prompted by browser to provide TPM PIN, but certificate is not sent to the server, as per Nginx logs. I'm trying to figure out what might be the reason. Has this setup with client certificate in TPM been tested with browsers?

Hi there, Im having the same issue when using a certificate in browsers that contain a UPN in the SAN. Did you find any solution to this? Would be nice if you could share something.
Thanks in advance!

**Comment by HumanoidPhantom** [comment]
> > As far as I can see, it is not related to store location, and I have TPM2_PKCS11_STORE var set.
> > 
> > As a workaround I found that it is possible to change key value manually and set the correct one:
> > 
> > ```
> > $ tpm_cert=$(cat "test.crt" | openssl x509 -inform PEM -outform DER | xxd -p | tr -d \\n)
> > $ tpm2_ptool objmod --key 17 --id 3 --value "${tpm_cert}" --type raw
> > ```
> > 
> > After this I am able to use certificate from TPM with openconnect, curl, etc.
> > 
> > However, it still does not work in browsers (tested in Firefox, Chrome). I prompted by browser to provide TPM PIN, but certificate is not sent to the server, as per Nginx logs. I'm trying to figure out what might be the reason. Has this setup with client certificate in TPM been tested with browsers?
> 
> Hi there, Im having the same issue when using a certificate in browsers that contain a UPN in the SAN. Did you find any solution to this? Would be nice if you could share something.
> Thanks in advance!

I used described workaround. From what I can see there was a fix for this issue, though I didn't have a chance to check if it works for me

**Comment by kuhlmannmarkus** [comment]
OK, thanks anyways! Will try to dig deeper.
