### ISSUE TITLE
C_OpenSession & C_Login Issue: "Esys called in bad sequence"

### ISSUE THREAD

**Issue by heobu** [tpm2-software/tpm2-pkcs11#637]
Hello,

I open a session and login for some operations and usually there is no problem.
This is how I call these functions:
C_OpenSession(slot_number, CKF_SERIAL_SESSION | CKF_RW_SESSION, NULL, NULL, session);
C_Login(*session, CKU_USER, user_pin, strlen(user_pin));

But after some changes now at one point when the application tries to login, I get an error:

`ERROR:esys:src/tss2-esys/esys_iutil.c:1149:iesys_check_sequence_async() Esys called in bad sequence. 
ERROR:esys:src/tss2-esys/api/Esys_Load.c:89:Esys_Load() Error in async function ErrorCode (0x00070007) 
ERROR: Esys_Load: esapi:Function called in the wrong order:
ERROR: Error unsealing wrapping key`

This does not happen elsewhere in the program when the same function opening the session and logging in is called. But this step is always an issue and i can replicate it at the same point. I checked the slot number, open session return value, user pin value etc, and they all seem fine. Moreover, I can just restart the application and this time around everything works just fine.

What might be the problem?

I've seen that maybe open session might be doing something asynchronous but waiting did not seem to help either and i couldn't make the callback work either anyway, but i guess that might be an issue.

**Comment by heobu** [comment]
Does anyone have a clue on why this might be happening?

**Comment by williamcroberts** [comment]
No idea, do you have the program or script that replicates this issue? I can't replicate it. But maybe it's related to this:
  - https://github.com/tpm2-software/tpm2-tss/issues/1498

The patches seem applied since tpm2-tss version 2.4.0, what does the command:
```bash
pkg-config --modversion tss2-esys
```
show?
