### ISSUE TITLE
Feature request: import SSH private key using tpm2_ptool

### ISSUE THREAD

**Issue by fishilico** [tpm2-software/tpm2-pkcs11#659]
Hello,

It is currently possible to use keys from `tpm2-pkcs11` in OpenSSH thanks to the great documentation in <https://github.com/tpm2-software/tpm2-pkcs11/blob/1.5.0/docs/SSH.md>. Moreover:

* Users are able to quickly create new SSH keys using `tpm2_ptool.py addkey --algorithm=rsa2048 --label=label --userpin=myuserpin ...` (or `--algorithm=ecc256`)
* Users are able to quickly import RSA and EC private keys stored in PEM format using `tpm2_ptool.py import ...`

However users are not able to quickly import RSA and EC private keys stored in OpenSSH format, because OpenSSH uses a custom format to store its keys.

Thankfully, <https://cryptography.io> supports loading such private keys: <https://cryptography.io/en/3.4.6/hazmat/primitives/asymmetric/serialization.html#cryptography.hazmat.primitives.serialization.load_ssh_private_key>. It is possible to convert an OpenSSH key to an usual PEM format compatible with `tpm2_import` (and therefore with `tpm2_ptool.py import`) with something such as:
```python
from cryptography.hazmat.primitives import serialization

with open('.ssh/id_rsa', 'rb') as f:
    ssh_key = serialization.load_ssh_private_key(f.read(), password='mypassword')

pem_key = ssh_key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.TraditionalOpenSSL,
    encryption_algorithm=serialization.NoEncryption())

with open('privatekey_as_pem', 'wb') as f:
    f.write(pem_key)
```

Such code works with at least both RSA keys (`ssh-keygen -t rsa -b 2048`) and NIST P-256 keys (`ssh-keygen -t ecdsa -b 256`).

It would be nice if `tpm2_ptool` provided an `importssh` command which expects as parameters a path to an OpenSSH private key, an optional passphrase to read the key file, and usual arguments (`--label`, `--userpin`...). This command would convert the private key to PEM (with `serialization.load_ssh_private_key`) and call `tpm2.importkey` (like `tpm2_ptool import ...`), while detecting the used algorithm (RSA or ECC) "magically". I believe this would make migrating from "using SSH with private keys stored in files" to "using SSH with private keys in the TPM" much much easier.

What do you think of such a feature?

If it suits you, I can work on some patches and submit a PR which would implement this feature.

**Comment by williamcroberts** [comment]
I think this is a great feature. You could just make tpm2_ptool import smart enough [here](https://github.com/tpm2-software/tpm2-pkcs11/blob/63a5f554cc73114d024ba1e093b70fe557a65fc7/tools/tpm2_pkcs11/tpm2.py#L253) to do something like:
```python
try:
    # You might want a separate auth value over -p... since you might want to use -p only for the
    # tpm side password and not for the local file password.
    ssh_key = serialization.load_ssh_private_key(privkey.read(), password=objauth)
    pem_key = ssh_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption())
    
    # Re use the priv temp file as both the input file and output file (I think this works).
    priv.write(pem_key)
    privkey = priv
catch:
    pass

# existing code
        parent_path = str(phandle)
        cmd = [
            'tpm2_import', '-V', '-C', parent_path, '-i', privkey, '-u', pub,
            '-r', priv
        ]

        if pauth and len(pauth) > 0:
            cmd.extend(['-P', pauth])
...
```
