### ISSUE TITLE
Authorization model using NV/Transient objects 

### ISSUE THREAD

**Issue by wenxinleong** [tpm2-software/tpm2-pkcs11#675]
Is the following statements correct?
- To date the authorization model mentioned in [tpm2-pkcs11_object_auth_model.md](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/tpm2-pkcs11_object_auth_model.md) is not implemented yet. Is there a plan on when this will be ready?
- The current implementation is based on [ARCHITECTURE.md](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/ARCHITECTURE.md)

**Comment by williamcroberts** [comment]
> Is the following statements correct?
> 
> * To date the authorization model mentioned in [tpm2-pkcs11_object_auth_model.md](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/tpm2-pkcs11_object_auth_model.md) is not implemented yet. Is there a plan on when this will be ready?

Correct, it is not done. I don't know. Its something we need to revisit.

> * The current implementation is based on [ARCHITECTURE.md](https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/ARCHITECTURE.md)

That's correct.
