### ISSUE TITLE
Build failure with gcc11

### ISSUE THREAD

**Issue by akuster** [tpm2-software/tpm2-pkcs11#676]
I build these sources in the context of OpenEmbedded framework and they just updated to gcc 11. I am now seeing this error.

cc1: all warnings being treated as errors
| make: *** [Makefile:1953: src/lib/slot.lo] Error 1
| make: *** Waiting for unfinished jobs....
| In file included from src/lib/mutex.h:10,
|                  from src/lib/session_ctx.h:6,
|                  from src/lib/digest.h:13,
|                  from src/lib/tpm.c:28:
| In function 'str_padded_copy',
|     inlined from 'tpm_get_token_info' at src/lib/tpm.c:742:5:
| src/lib/utils.h:42:5: error: 'strnlen' specified bound 32 exceeds source size 5 [-Werror=stringop-overread]
|    42 |     memcpy(dst, src, strnlen((char *)(src), dst_len));
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| src/lib/utils.h: In function 'tpm_get_token_info':
| src/lib/tpm.c:739:19: note: source object declared here
|   739 |     unsigned char manufacturerID[sizeof(UINT32)+1] = {0}; // 4 bytes + '\0' as temp storage
|       |                   ^~~~~~~~~~~~~~
| cc1: all warnings being treated as errors
| make: *** [Makefile:1953: src/lib/tpm.lo] Error 1
| WARNING: exit code 1 from a shell command.

**Comment by williamcroberts** [comment]
> I build these sources in the context of OpenEmbedded framework and they just updated to gcc 11. I am now seeing this error.
> 
> cc1: all warnings being treated as errors
> | make: *** [Makefile:1953: src/lib/slot.lo] Error 1
> | make: *** Waiting for unfinished jobs....
> | In file included from src/lib/mutex.h:10,
> | from src/lib/session_ctx.h:6,
> | from src/lib/digest.h:13,
> | from src/lib/tpm.c:28:
> | In function 'str_padded_copy',
> | inlined from 'tpm_get_token_info' at src/lib/tpm.c:742:5:
> | src/lib/utils.h:42:5: error: 'strnlen' specified bound 32 exceeds source size 5 [-Werror=stringop-overread]
> | 42 | memcpy(dst, src, strnlen((char *)(src), dst_len));
> | | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> | src/lib/utils.h: In function 'tpm_get_token_info':
> | src/lib/tpm.c:739:19: note: source object declared here
> | 739 | unsigned char manufacturerID[sizeof(UINT32)+1] = {0}; // 4 bytes + '\0' as temp storage
> | | ^~~~~~~~~~~~~~
> | cc1: all warnings being treated as errors
> | make: *** [Makefile:1953: src/lib/tpm.lo] Error 1
> | WARNING: exit code 1 from a shell command.

If i'm reading this right, gcc is complaining the code is putting 5 bytes into a 32 byte buffer. Yeah, whats the problem? This seems like a gcc bug. you can disable that warning with `--disable-hardening` during configure time.

**Comment by williamcroberts** [comment]
Oh I think I see it now, i think gcc is right

**Comment by williamcroberts** [comment]
I think PR https://github.com/tpm2-software/tpm2-pkcs11/pull/677 fixes it, @akuster can you give it a try?

**Comment by akuster** [comment]
Same error

**Comment by williamcroberts** [comment]
> Same error

Ahh I got it duped locally now, had to go get gcc-11, fix commencing.

**Comment by williamcroberts** [comment]
@akuster I think I got it. I grabbed gcc-11, reproduced it locally, built and tested and everything seems ok. Can you confirm that the most recent push fixes it (HEAD 7bbfd22).

**Comment by akuster** [comment]
Awesome. That works.

Thanks
