### ISSUE TITLE
rsaKey null in Java example

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-pkcs11#699]
In my java example the Key property rsaKey is returning null

I created the token and private key with the command below:

tpm2_ptool init --path=/etc/tpm2_pkcs11
tpm2_ptool addtoken --pid=1 --sopin=testpin --userpin=testpin --label=label --path=/etc/tpm2_pkcs11
tpm2_ptool addkey --algorithm=rsa2048 --label="label" --key-label="rsa1" --userpin=testpin --path=/etc/tpm2_pkcs11
tpm2_ptool config --key tcti --value "device:/dev/tpmrm0" --label=label

and this is my java code:

`
public class Main {
	static final String PIN = "testpin";
	static final String KEY_ALIAS = "rsa1";
	static Provider provider;

	public static void beforeAllTestMethods() throws Exception {
		Path libPath = Paths.get("/usr/local/lib/libtpm2_pkcs11.so.0.0.0");

		String version = System.getProperty("java.version");
		/* Parse for example "11.0.11" or "17-ea" */
		String [] chunks = version.split("[\\.-]");
		int major = Integer.parseInt(chunks[0]);
		if (major >= 9) {
			/* Java >= 9 */
			Method configure = Provider.class.getMethod("configure", String.class);
			String pkcs11Config = "--name = TPM2\nlibrary = " + libPath;
			provider = Security.getProvider("SunPKCS11");
			provider = (Provider) configure.invoke(provider, pkcs11Config);
		} else {
			/* Java <= 8 */
			Constructor SunPKCS11 = Class.forName("sun.security.pkcs11.SunPKCS11").getConstructor(InputStream.class);
			String pkcs11Config = "name = TPM2\nlibrary = " + libPath;
			ByteArrayInputStream confStream = new ByteArrayInputStream(pkcs11Config.getBytes());
			provider = (Provider) SunPKCS11.newInstance(confStream);
		}

		/* add the provider */
		Security.addProvider(provider);
	}

	public static void main(String[] args) {
		try {
			beforeAllTestMethods();

			KeyStore keyStore = KeyStore.getInstance("PKCS11-TPM2");
			KeyStore.PasswordProtection pp = new KeyStore.PasswordProtection(PIN.toCharArray());
			keyStore.load(null, pp.getPassword());

			System.out.println("KeyStore Type : " + keyStore.getType());
			System.out.println("KeyStore Size : " + keyStore.size());

			Provider prov = keyStore.getProvider();
			System.out.println("Provider Name : " + prov.getName());
			System.out.println("Provider Info : " + prov.getInfo());
			System.out.println("Provider Version : " + prov.getVersionStr());

			Enumeration<String> aliases = keyStore.aliases();

			while (aliases.hasMoreElements()) {
				String alias = aliases.nextElement();
			}

			Key rsaKey = keyStore.getKey(KEY_ALIAS, null); 
                        **//HERE IS THE PROBLEM rsaKey IS RETURNING NULL**

			X509Certificate certificate = (X509Certificate) keyStore.getCertificate(KEY_ALIAS);

			Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding", provider);

			String plaintext = "mysecretdata";
			byte[] plainData = plaintext.getBytes("UTF-8");

			cipher.init(Cipher.ENCRYPT_MODE, rsaKey);
			byte[] encryptedData = cipher.doFinal(plainData);

		} catch (Exception e) {
			e.printStackTrace();
		}

	}`

What am I doing wrong?

**Comment by roberto497** [comment]
The error was that the KeyStore does not identify the key that only has the private key, it also needs to have the certificate.

**Comment by williamcroberts** [comment]
Yep, we've bumped into that before, it's quite confusing. Glad you sorted it out.

**Comment by roberto497** [comment]
When I create my token I can run the command below without root permission.
**p11tool --list-token-urls | grep "token=label"**
e retorna a informação sem nenhum erro.

However after running the
**tpm2_ptool config --key tcti --value "device:/dev/tpmrm0" --label=label**

The same command above (**p11tool --list-token-urls | grep "token=label"**) returns the following error:
**Failed to open specified TCTI device file /dev/tpmrm0: Permission denied**

The strange thing is that I have 70-tpm-udev.rules

What am I doing wrong?
