### ISSUE TITLE
tpm2_ptool: ASN1 reparsing might introduces errors

### ISSUE THREAD

**Issue by commial** [tpm2-software/tpm2-pkcs11#700]
Hello,

In `pemcert_to_attrs`: https://github.com/tpm2-software/tpm2-pkcs11/blob/8f7b51adeda5b19888e7ad965bd95d0472969cb5/tools/tpm2_pkcs11/utils.py#L264

The code recreates the certificate data from a parsed version, ie: `original -> parsed -> certificate`.

Problem is, **this transformation is not a bijection**. For instance, the ASN1 boolean `True` should be encoded as a not-null value (`1`, `0xFF`, ... are then valid).

As a result, one of the certificate I import is not the same when given back, leading to a broken certificate chain:
```sh
# Parse the certificate
$ openssl asn1parse -in /tmp/cert_only.pem -inform pem
...
  611:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Key Usage
  616:d=5  hl=2 l=   1 prim: BOOLEAN           :255
  619:d=5  hl=2 l=   4 prim: OCTET STRING      [HEX DUMP]:030205A0
...
# Import it
$ tpm2_ptool addcert --label label --key-id 64616637633462616464393630326431 /tmp/cert_only.pem
# Get it back
$ tpm2_ptool objmod --id 3 --key 17
CKA_VALUE: 3082...
$ python
>>> open("/tmp/cert_out.der", "wb").write(b"3082...")
# Parse it back
$ openssl asn1parse -in /tmp/cert_out.der -inform der
...
  611:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Key Usage
  616:d=5  hl=2 l=   1 prim: BOOLEAN           :1
  619:d=5  hl=2 l=   4 prim: OCTET STRING      [HEX DUMP]:030205A0
...
# Check the certificate chain
## Original
$ openssl verify -CAfile ~/CA.pem /tmp/cert_only.pem 
/tmp/cert_only.pem: OK
## Outputed
$ openssl x509 -in /tmp/cert_out.der -inform der -out /tmp/cert_out.pem -outform pem
$ openssl verify -CAfile ~/CA.pem /tmp/cert_out.pem
CN = client@WINDOMAIN.LOCAL
error 7 at 0 depth lookup: certificate signature failure
error /tmp/cert_out.pem: verification failed
140560000189824:error:04091068:rsa routines:int_rsa_verify:bad signature:crypto/rsa/rsa_sign.c:220:
140560000189824:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto/asn1/a_verify.c:170:
```

I can PR a fix, but I'm not sure what is the better way to fix that problem. Ideas?
Anyway, the PR should also include regression tests with different encoded value of ASN.1 Boolean.

**Comment by williamcroberts** [comment]
Sure ill take a PR, I'm not really sure the best way to fix this, as the CKA_VALUE field needs to be DER encoded cert...
