### ISSUE TITLE
Permission denied after tpm2_ptool config

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-pkcs11#704]
When I create my token I can run the command below without root.
**p11tool --list-token-urls | grep "token=label"**
returns without any problem.

However after running the
**tpm2_ptool config --key tcti --value "device:/dev/tpmrm0" --label=label**

The same command above (**p11tool --list-token-urls | grep "token=label"**) returns the following error:
**Failed to open specified TCTI device file /dev/tpmrm0: Permission denied**

The strange thing is that I have **70-tpm-udev.rules**

What am I doing wrong?

**Comment by niooss-ledger** [comment]
Hello,
Could you provide the output of commands `ls -l /dev/tpmrm0` and `id`, and maybe `getfacl /dev/tpmrm0` too, to check that your user has access to the TPM device?

For example on my system:
```console
$ ls -l /dev/tpmrm0
crw-rw---- 1 tss tss 253, 65536 Jul 23 6:08 /dev/tpmrm0

$ id
uid=1000(user) gid=1000(user) groups=1000(user),...,37(tss)
```

So my user is in group `tss` which has read-write access to `/dev/tpmrm0`.

**Comment by roberto497** [comment]
the user I was using was not in the tss group, I added it and the problem was solved
