### ISSUE TITLE
tpm2-pkcs11 build on centos7

### ISSUE THREAD

**Issue by celebgnu** [tpm2-software/tpm2-pkcs11#706]
I have the following packages built on my centos7
 tpm2-abrmd
tpm2-pkcs11
tpm2-tools
tpm2-tss
tpm2-tss-engine

I am facing an issue while building tpm2-pkcs11 package on centos7
checking for tpm2_createprimary... yes
checking for tpm2_create... yes
checking for tpm2_evictcontrol... yes
checking for tpm2_readpublic... yes
checking for tpm2_load... yes
checking for tpm2_loadexternal... yes
checking for tpm2_unseal... yes
checking for tpm2_encryptdecrypt... yes
checking for tpm2_sign... yes
checking for tpm2_getcap... yes
checking for tpm2_import... yes
checking for tpm2_changeauth... yes
checking for P11KIT... no
./configure: line 16536: syntax error near unexpected token `P11_MODULE_PATH,'
./configure: line 16536: `    PKG_CHECK_VAR(P11_MODULE_PATH, p11-kit-1, p11_module_path)'

[pkg-config --version
0.27.1

I am on the master branch as of now
git status
# On branch master

I wanted install this package on centos 7, can someone please confirm if this could done from master branch if not then which branch supports this configuration.

**Comment by williamcroberts** [comment]
You need to install p11-kit development edition, I think the package name is p11-kit-devel

**Comment by celebgnu** [comment]
So as per suggestion i had installed the p11-kit-devel
$ rpm -q p11-kit-devel
p11-kit-devel-0.23.5-3.el7.x86_64


$ rpm -q p11-kit
p11-kit-0.23.5-3.el7.x86_64

But still i am observing the same issue
checking for tpm2_createprimary... yes
checking for tpm2_create... yes
checking for tpm2_evictcontrol... yes
checking for tpm2_readpublic... yes
checking for tpm2_load... yes
checking for tpm2_loadexternal... yes
checking for tpm2_unseal... yes
checking for tpm2_encryptdecrypt... yes
checking for tpm2_sign... yes
checking for tpm2_getcap... yes
checking for tpm2_import... yes
checking for tpm2_changeauth... yes
checking for P11KIT... yes
./configure: line 16536: syntax error near unexpected token `P11_MODULE_PATH,'
./configure: line 16536: `    PKG_CHECK_VAR(P11_MODULE_PATH, p11-kit-1, p11_module_path)'

**Comment by williamcroberts** [comment]
Oh I see the issue, you need to update pkg-config from version 0.27 to 0.28+. Same bug as:
https://wiki.strongswan.org/issues/3406

**Comment by williamcroberts** [comment]
Might also be an autoconf update as well....

**Comment by celebgnu** [comment]
As per the advise upgraded the pkgconfig to the following
[csp@lhtg05d1 tpm2-pkcs11]$ pkg-config --version
0.28

Command line: ./configure PKG_CONFIG_PATH=<path_to_tpm2_tss_dir>:/usr/lib64/pkgconfig:$PKG_CONFIG_PATH  CFLAGS=-I/<path_to_tpm2_tss>include LDFLAGS=-L<path_to_tpm2_tss>/src/tss2-{tcti,mu,sys,esys}/.libs  --with-p11kitmoduledir=/usr/lib64/pkcs11  --with-p11kitconfigdir=/usr/share/p11-kit/

But still observing the same error
checking for tpm2_load... yes
checking for tpm2_loadexternal... yes
checking for tpm2_unseal... yes
checking for tpm2_encryptdecrypt... yes
checking for tpm2_sign... yes
checking for tpm2_getcap... yes
checking for tpm2_import... yes
checking for tpm2_changeauth... yes
checking for P11KIT... yes
./configure: line 16536: syntax error near unexpected token `P11_MODULE_PATH,'
./configure: line 16536: `    PKG_CHECK_VAR(P11_MODULE_PATH, p11-kit-1, p11_module_path)'

**Comment by celebgnu** [comment]
As per this document https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/INITIALIZING.md

My end goal is to generate libtpm2_pkcs11.so.0.0.0 file and use it along with pkcs11-tool

Something like this 
pkcs11-tool --module $HOME/workspace/tpm2-pkcs11/src/.libs/libtpm2_pkcs11.so.0.0.0

But i am facing issues in generating the file libtpm2_pkcs11.so.0.0.0 as the configure script is failing with error above
I am building this utility on a centos 7 with following kernel
3.10.0-1062.el7.x86_64

Any inputs in terms of overcoming this error or an rpm link that would provide the mentioned (libtpm2_pkcs11.so)  file would
be a great. 
.

**Comment by niooss-ledger** [comment]
> `./configure: line 16536: syntax error near unexpected token P11_MODULE_PATH,' ./configure: line 16536: PKG_CHECK_VAR(P11_MODULE_PATH, p11-kit-1, p11_module_path)'`

This looks like you did not regenerate the `./configure` file. Anyway, I have just tested building `tpm2-pkcs11` in a CentsOS 7 container and faced the same issue (with `pkgconfig` 0.27.1). A possible work-around consists in:

* commenting the two lines with `PKG_CHECK_VAR` in `./configure`:
```diff
--- configure	2021-08-14 20:42:37.303110121 +0000
+++ /host/configure	2021-08-14 20:43:17.043510791 +0000
@@ -16533,7 +16533,7 @@
 
   if test -z "$p11kitmoduledir"; then :
 
-    PKG_CHECK_VAR(P11_MODULE_PATH, p11-kit-1, p11_module_path)
+#    PKG_CHECK_VAR(P11_MODULE_PATH, p11-kit-1, p11_module_path)
     { $as_echo "$as_me:${as_lineno-$LINENO}: checking p11 module path" >&5
 $as_echo_n "checking p11 module path... " >&6; }
     if test "x$P11_MODULE_PATH" = "x"; then :
@@ -16556,7 +16556,7 @@
 
   if test -z "$p11kitconfigdir"; then :
 
-    PKG_CHECK_VAR(P11_CONFIGS_PATH, p11-kit-1, p11_module_configs)
+#    PKG_CHECK_VAR(P11_CONFIGS_PATH, p11-kit-1, p11_module_configs)
     { $as_echo "$as_me:${as_lineno-$LINENO}: checking p11 configs path" >&5
 $as_echo_n "checking p11 configs path... " >&6; }
     if test "x$P11_CONFIGS_PATH" = "x"; then :
```

* and adding the paths to p11-kit directories to the `./configure` command-line: `./configure  --with-p11kitconfigdir=/usr/share/p11-kit/modules --with-p11kitmoduledir=/usr/lib64/pkcs11`.

Then, `./configure ...` succeeds but `make` fails because the compiler is too old (gcc 4.8.5 does not support `__builtin_add_overflow` and `__builtin_mul_overflow`, which are important to detect integer overflow issues, cf. https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html). So you would also need a more recent compiler to build tpm2-pkcs11.

**Comment by williamcroberts** [comment]
You can disable overflow via configure time option `--disable-overflow`, but I **really don't recommend it** as it's crucial to detecting overflow errors in the code. I highly recommend updating to a newer compiler which should be simple enough.
