### ISSUE TITLE
DB upgrade function performs out-of-bound array read and might insert mechanism 0

### ISSUE THREAD

**Issue by niooss-ledger** [tpm2-software/tpm2-pkcs11#710]
Hello,

Currently in `master` branch, functions `handle_ECDSA_5_to_6` and `handle_AES_5_to_6` of [`src/lib/db.c`](https://github.com/tpm2-software/tpm2-pkcs11/blob/e45e1275d44ae39b9f1badcdc914527a1473be87/src/lib/db.c) might perform out-of-bound array read and introduce a "zero" mechanism in attribute `CKA_ALLOWED_MECHANISMS`.

More precisely, for `handle_ECDSA_5_to_6`, the code does: https://github.com/tpm2-software/tpm2-pkcs11/blob/e45e1275d44ae39b9f1badcdc914527a1473be87/src/lib/db.c#L1855-L1873

As `mech_num` was increased by 3, the `for` loop should use `i < mech_num - 3` instead. Currently, the loop reads `a->pValue[mech_num - 3]` and `a->pValue[mech_num - 2]`, which are right after the higher bound of the array `a->pValue`.

Moreover `handle_ECDSA_5_to_6` continues by adding the 3 new mechanisms at `new_mechs[mech_num - 3]`, `new_mechs[mech_num - 2]` and `new_mechs[mech_num - 1]` and by updating the attribute using `mech_num`: https://github.com/tpm2-software/tpm2-pkcs11/blob/e45e1275d44ae39b9f1badcdc914527a1473be87/src/lib/db.c#L1880-L1884

Therefore if `CKA_ALLOWED_MECHANISMS` already contained `CKM_ECDSA_SHA{256,384,512}`, zeros are inserted in the array. This value maps to `CKM_RSA_PKCS_KEY_PAIR_GEN` (according to <https://github.com/oasis-tcs/pkcs11/blob/0c3ecef6c90dcd8249ba64cc99d50d9f8f73124e/working/identifier_db/raw_ids.db#L342>), which is not what is intended.

For `handle_AES_5_to_6`, the for-loop directly inserts zeros, in: https://github.com/tpm2-software/tpm2-pkcs11/blob/e45e1275d44ae39b9f1badcdc914527a1473be87/src/lib/db.c#L1931-L1947

... because when `if (old_mech == CKM_AES_CBC_PAD || old_mech == CKM_AES_CTR)` happens, the `continue;` increments `i`. This is exactly like what I reported in a previous comment https://github.com/tpm2-software/tpm2-pkcs11/pull/689/files#discussion_r648715640.

Moreover `handle_AES_5_to_6` also has the out-of-bound array access issue, because `mech_num` is incremented by 2 and the `for` loop uses `for (i=0; i < mech_num - 1; i++)`.

I suggest fixing the bounds of the `for` loops, replacing the assignments such as `new_mechs[mech_num - 3] = CKM_ECDSA_SHA256;` with `new_mechs[pos++] = CKM_ECDSA_SHA256;` and then computing `safe_mul(total_bytes, pos, sizeof(CK_MECHANISM_TYPE));`. What do you think?

By the way I did not try the Python code of the 5->6 update path, but the condition for EC keys seem to be inverted, in https://github.com/tpm2-software/tpm2-pkcs11/blob/e45e1275d44ae39b9f1badcdc914527a1473be87/tools/tpm2_pkcs11/db.py#L477-L483

This code seems to be a copy-paste from `_update_on_5`, but there, the condition was for a `continue` statement. As this is now for the "private EC key" case, the code seems wrong (though I have not tested it). Did I miss something?

**Comment by niooss-ledger** [comment]
Hello @williamcroberts, I bumped into this code again while looking at the output of clang's static analyzer, and it seems it is still wrong. The latest release (1.7.0) contains: https://github.com/tpm2-software/tpm2-pkcs11/blob/7a04ae8d3b4b2e2b8a7036607928db765dd33333/src/lib/db.c#L1715-L1729

I believe that the for loop should instead be `for (i=0; i < mech_num - 2; i++) {`. (and `for (i=0; i < mech_num - 3; i++) ` in function `handle_ECDSA_5_to_6`). What do you think?

For information, clang's static analyzer reported a NULL pointer dereference when `CK_ATTRIBUTE_PTR a = attr_get_attribute_by_type(tobj->attrs, CKA_ALLOWED_MECHANISMS);` returns `NULL` because the for loop accesses the first two items of `((CK_MECHANISM_TYPE_PTR)(a->pValue))[i]` while `a` is `NULL`...

**Comment by williamcroberts** [comment]
What version of scan-build are you using? I am not seeing it report anything.

**Comment by niooss-ledger** [comment]
> What version of scan-build are you using? I am not seeing it report anything.

I am using version 12.0.0 with some options to enable extra checkers:

```sh
scan-build --force-analyze-debug-code -enable-checker security -enable-checker unix -enable-checker valist -enable-checker alpha.core.BoolAssignment -enable-checker alpha.core.CastSize -enable-checker alpha.core.CastToStruct -enable-checker alpha.core.DynamicTypeChecker -enable-checker alpha.core.FixedAddr -enable-checker alpha.core.IdenticalExpr -enable-checker alpha.core.PointerArithm -enable-checker alpha.core.PointerSub -enable-checker alpha.core.SizeofPtr -enable-checker alpha.core.TestAfterDivZero -enable-checker alpha.security.ArrayBoundV2 -enable-checker alpha.security.MallocOverflow -enable-checker alpha.security.ReturnPtrRange -enable-checker alpha.security.taint.TaintPropagation -enable-checker alpha.unix.PthreadLock -enable-checker alpha.unix.SimpleStream -enable-checker alpha.unix.Stream -enable-checker alpha.unix.cstring.BufferOverlap -enable-checker alpha.unix.cstring.OutOfBounds -enable-checker alpha.unix.cstring.NotNullTerminated -maxloop 257 -analyze-headers -o scan-build-output make
```

This reports many false positive issues, and for `db.c` this reports:

```text
src/lib/db.c:1729:62: warning: Access to field 'pValue' results in a dereference of a null pointer (loaded from variable 'a') [core.NullDereference]
        CK_MECHANISM_TYPE old_mech = ((CK_MECHANISM_TYPE_PTR)(a->pValue))[i];
                                                             ^~~~~~~~~~~
src/lib/db.c:1879:62: warning: Access to field 'pValue' results in a dereference of a null pointer (loaded from variable 'a') [core.NullDereference]
        CK_MECHANISM_TYPE old_mech = ((CK_MECHANISM_TYPE_PTR)(a->pValue))[i];
                                                             ^~~~~~~~~~~
```
