### ISSUE TITLE
C_Encrypt() doesn't always work with CKM_AES_CBC_PAD

### ISSUE THREAD

**Issue by rgerganov** [tpm2-software/tpm2-pkcs11#730]
I have the following code:
```
    rv = pP11Functions->C_EncryptInit(hSession, pMech, hSymKey);
    if(rv != CKR_OK) {
        goto doneEnc;
    }

    // Get the size of the encrypted data.
    rv = pP11Functions->C_Encrypt(hSession, pData, cbData, NULL, pcbEncrypted);
    if(rv != CKR_OK) {
        goto doneEnc;
    }
    printf("Size of encrypted data: %d\n", *pcbEncrypted);

    // Allocate the encypted data buffer.
    *ppEncrypted = (CK_BYTE_PTR)calloc(*pcbEncrypted, 1);
    if(NULL == *ppEncrypted) {
        goto doneEnc;
    }

    // Encrypt the data.
    rv = pP11Functions->C_Encrypt(hSession, pData, cbData, *ppEncrypted, pcbEncrypted);
    if(rv != CKR_OK) {
        goto doneEnc;
    }
```

When I try to encrypt the message `Hello World!` with AES key and `CKM_AES_CBC_PAD` mechanism, I am getting `CKR_BUFFER_TOO_SMALL` error on the second call of `C_Encrypt`. The first call of `C_Encrypt` is successful and it returns the correct size of the encrypted data which is 16. If I do only one call to `C_Encrypt` with the correct buffer size, then it succeeds.

**Comment by niooss-ledger** [comment]
Hello,
I am not familiar with PKCS#11 symmetric encryption use-cases. When reading your code, I am wondering whether you are using correctly the PKCS#11 functions. According to the documentation of `C_EncryptInit` (http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959744):

> After calling C_EncryptInit, the application can either call C_Encrypt to encrypt data in a single part; or call C_EncryptUpdate zero or more times, followed by C_EncryptFinal, to encrypt data in multiple parts.  The encryption operation is active until the application uses a call to C_Encrypt or C_EncryptFinal to actually obtain the final piece of ciphertext.  To process additional data (in single or multiple parts), the application MUST call C_EncryptInit again.

So it seems that calling `C_Encrypt` twice, like your code does, is not valid. Did you try calling `rv = pP11Functions->C_EncryptInit(hSession, pMech, hSymKey);` again before the second `C_Encrypt`?

**Comment by williamcroberts** [comment]
> Hello,
> I am not familiar with PKCS#11 symmetric encryption use-cases. When reading your code, I am wondering whether you are using correctly the PKCS#11 functions. According to the documentation of `C_EncryptInit` (http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959744):
> 
> > After calling C_EncryptInit, the application can either call C_Encrypt to encrypt data in a single part; or call C_EncryptUpdate zero or more times, followed by C_EncryptFinal, to encrypt data in multiple parts.  The encryption operation is active until the application uses a call to C_Encrypt or C_EncryptFinal to actually obtain the final piece of ciphertext.  To process additional data (in single or multiple parts), the application MUST call C_EncryptInit again.
> 
> So it seems that calling `C_Encrypt` twice, like your code does, is not valid. Did you try calling `rv = pP11Functions->C_EncryptInit(hSession, pMech, hSymKey);` again before the second `C_Encrypt`?

They use the conventions described in section 5.2:
  - http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959738

If the pointer on the first call for output buffer is NULL, the size is returned and the state isn't reset so the caller can allocate the buffer and call again.

**Comment by williamcroberts** [comment]
> I have the following code:
> 
> ```
>     rv = pP11Functions->C_EncryptInit(hSession, pMech, hSymKey);
>     if(rv != CKR_OK) {
>         goto doneEnc;
>     }
> 
>     // Get the size of the encrypted data.
>     rv = pP11Functions->C_Encrypt(hSession, pData, cbData, NULL, pcbEncrypted);
>     if(rv != CKR_OK) {
>         goto doneEnc;
>     }
>     printf("Size of encrypted data: %d\n", *pcbEncrypted);
> 
>     // Allocate the encypted data buffer.
>     *ppEncrypted = (CK_BYTE_PTR)calloc(*pcbEncrypted, 1);
>     if(NULL == *ppEncrypted) {
>         goto doneEnc;
>     }
> 
>     // Encrypt the data.
>     rv = pP11Functions->C_Encrypt(hSession, pData, cbData, *ppEncrypted, pcbEncrypted);
>     if(rv != CKR_OK) {
>         goto doneEnc;
>     }
> ```
> 
> When I try to encrypt the message `Hello World!` with AES key and `CKM_AES_CBC_PAD` mechanism, I am getting `CKR_BUFFER_TOO_SMALL` error on the second call of `C_Encrypt`. The first call of `C_Encrypt` is successful and it returns the correct size of the encrypted data which is 16. If I do only one call to `C_Encrypt` with the correct buffer size, then it succeeds.

What is the size of your input so I can test this exact scenario?

**Comment by rgerganov** [comment]
> 
> What is the size of your input so I can test this exact scenario?

The input is the string "Hello World!" which is 12 bytes. Tomorrow I will paste the full source.

**Comment by williamcroberts** [comment]
> > What is the size of your input so I can test this exact scenario?
> 
> The input is the string "Hello World!" which is 12 bytes. Tomorrow I will paste the full source.

Oh duh, you said that. Ill take a look most likely tomorrow.

**Comment by rgerganov** [comment]
Here is the full source code:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include "cryptoki.h"

CK_FUNCTION_LIST* pP11Functions = NULL;

CK_BBOOL LoadP11Functions(void *libHandle)
{
    CK_BBOOL myRC = CK_FALSE;
    CK_C_GetFunctionList C_GetFunctionList = NULL;
    CK_RV rv = CKR_TOKEN_NOT_PRESENT;

    if (!libHandle) {
        return CK_FALSE;
    }

    C_GetFunctionList = (CK_C_GetFunctionList)dlsym(libHandle, "C_GetFunctionList");

    if (C_GetFunctionList) {
        rv = C_GetFunctionList(&pP11Functions);
    }
    if (pP11Functions) {
        rv = pP11Functions->C_Initialize(NULL_PTR);
    }
    if (rv == CKR_OK) {
        myRC = CK_TRUE;
    }
    return myRC;
}

CK_RV FindFirstSlot(CK_SLOT_ID *pckSlot)
{
    CK_SLOT_ID_PTR pSlotList = NULL;
    CK_ULONG ulCount = 0;
    CK_RV retCode = CKR_OK;

    // Get the number of slots.
    retCode = pP11Functions->C_GetSlotList(CK_TRUE, NULL, &ulCount);
    if(retCode != CKR_OK) {
        printf("C_GetSlotList failed. \n");
        goto findSlot;
    }

    if(ulCount == 0) {
        printf("No slots found. \n");
        goto findSlot;
    }
    printf("%lu slots found\n", ulCount);
    fflush(stdout);
    // Allocate an array for the slots.
    pSlotList = (CK_SLOT_ID_PTR)calloc(ulCount, sizeof(CK_SLOT_ID));
    if(pSlotList == NULL) {
        printf("calloc failed. \n");
        goto findSlot;
    }

    // Get the slots.
    retCode = pP11Functions->C_GetSlotList(CK_TRUE, pSlotList, &ulCount);
    if(retCode != CKR_OK) {
        printf("C_GetSlotList failed, retCode=%lu, ulCount=%lu\n", retCode, ulCount);
        goto findSlot;
    }

    // Return the first slot.
    *pckSlot = pSlotList[0];
    printf("First slot: %lu\n", *pckSlot);

findSlot:
    if(pSlotList) {
        free(pSlotList);
    }
    return retCode;
}

CK_RV EncryptData(CK_SESSION_HANDLE hSession,
                  CK_OBJECT_HANDLE hSymKey,
                  CK_MECHANISM_PTR pMech,
                  CK_BYTE_PTR pData,
                  CK_ULONG cbData,
                  CK_BYTE_PTR* ppEncrypted,
                  CK_ULONG_PTR pcbEncrypted)
{
    CK_RV rv = CKR_OK;

    rv = pP11Functions->C_EncryptInit(hSession, pMech, hSymKey);
    if(rv != CKR_OK) {
        goto doneEnc;
    }

    // Get the size of the encrypted data.
    rv = pP11Functions->C_Encrypt(hSession, pData, cbData, NULL, pcbEncrypted);
    if(rv != CKR_OK) {
        goto doneEnc;
    }

    printf("Ciphertext length: %d\n", *pcbEncrypted);
    // Allocate the encypted data buffer.
    *ppEncrypted = (CK_BYTE_PTR)calloc(*pcbEncrypted, 1);
    if(NULL == *ppEncrypted) {
        goto doneEnc;
    }

    // Encrypt the data.
    rv = pP11Functions->C_Encrypt(hSession, pData, cbData, *ppEncrypted, pcbEncrypted);
    if(rv != CKR_OK) {
        goto doneEnc;
    }

doneEnc:
    return rv;
}

CK_RV FindKey(CK_SESSION_HANDLE hSession, CK_ATTRIBUTE *template, CK_ULONG attr_count, CK_ULONG *count, CK_OBJECT_HANDLE_PTR hObject)
{
    CK_RV rv = CKR_OK;
    if (NULL == hObject || NULL == template || NULL == count) {
        return CKR_ARGUMENTS_BAD;
    }

    rv = pP11Functions->C_FindObjectsInit(hSession, template, attr_count);
    if (rv != CKR_OK) {
        fprintf(stderr, "Can't initialize search\n");
        return rv;
    }

    rv = pP11Functions->C_FindObjects(hSession, hObject, 1, count);
    if (rv != CKR_OK) {
        fprintf(stderr, "Can't run search\n");
        pP11Functions->C_FindObjectsFinal(hSession);
        return rv;
    }
    rv = pP11Functions->C_FindObjectsFinal(hSession);
    return rv;
}

int main(int argc, char *argv[])
{
    if (argc < 4) {
        fprintf(stderr, "Usage: %s <pkcs11_lib> <password> <plaintext>\n", argv[0]);
        return 1;
    }

    void *libHandle = dlopen(argv[1], RTLD_NOW);
    if (!libHandle) {
        fprintf(stderr, "Error loading library: %s\n", dlerror());
        return 1;
    }
    printf("Library loaded\n");

    if (LoadP11Functions(libHandle) == CK_FALSE) {
        fprintf(stderr, "Failed to load PKCS11 functions\n");
        goto done;
    } else {
        printf("PKCS11 functions loaded\n");
    }

    CK_RV rv = CKR_TOKEN_NOT_PRESENT;
    CK_SLOT_ID ckSlot = 0;
    CK_SESSION_HANDLE hSession = 0;

    rv = FindFirstSlot(&ckSlot);
    if ((rv != CKR_OK) || (ckSlot == 0)) {
        fprintf(stderr, "FindFirstSlot failed.\n");
        goto done;
    }
    printf("Slot: %ld\n", ckSlot);

    rv = pP11Functions->C_OpenSession(ckSlot, CKF_RW_SESSION|CKF_SERIAL_SESSION, NULL, NULL, &hSession);
    if (rv != CKR_OK) {
        fprintf(stderr, "C_OpenSession failed.\n");
        goto done;
    }
    printf("Session opened\n");

    char *szPassword = argv[2];
    rv = pP11Functions->C_Login(hSession, CKU_USER, (CK_UTF8CHAR_PTR)szPassword, (CK_ULONG)strlen(szPassword));
    if (rv != CKR_OK) {
        fprintf(stderr, "C_Login failed, ret=%lu\n", rv);
        goto done;
    }
    printf("Login successful!\n");

    CK_ULONG count = 0;
    CK_OBJECT_HANDLE hSymKey = 0;
    CK_BYTE_PTR label1 = "aes0";
    CK_ATTRIBUTE attr[] = {
            {CKA_LABEL, label1, strlen(label1)},
    };
    rv = FindKey(hSession, attr, 1, &count, &hSymKey);
    if (rv != CKR_OK) {
        fprintf(stderr, "FindKey failed, ret=%lu\n", rv);
        goto done;
    }
    if (count != 1) {
        printf("AES key not found\n");
        goto done;
    }

    char *plaintext = argv[3];
    CK_BYTE_PTR pEncrypted = NULL;
    CK_ULONG cbEncrypted;
    CK_BYTE_PTR pDecrypted = NULL;
    CK_ULONG cbDecrypted;
    CK_BYTE iv[16] = {0};
    CK_MECHANISM mech = {CKM_AES_CBC_PAD, iv, 16};

    // Encrypt the data.
    rv = EncryptData(hSession,
        hSymKey,
        &mech,
        (CK_BYTE_PTR)plaintext,
        (CK_ULONG)strlen(plaintext),
        &pEncrypted,
        &cbEncrypted);
    if(rv != CKR_OK) {
        fprintf(stderr, "Error encrypting data rv: %lu\n", rv);
        goto done;
    } else {
        printf("Encryption successful\n");
    }

    rv = pP11Functions->C_CloseSession(hSession);
    if (rv != CKR_OK) {
        fprintf(stderr, "C_CloseSession failed, ret=%lu\n", rv);
    }
done:
    rv = pP11Functions->C_Finalize(NULL_PTR);
    if (rv != CKR_OK) {
        fprintf(stderr, "C_Finalize failed, ret=%lu\n", rv);
    }
    dlclose(libHandle);
    return 0;
}
```
It expects an initialized token which have an AES key labeled "aes0". I have added the key like this:
```
tpm2_ptool addkey --algorithm=aes256 --label="my first token" --key-label="aes0" --userpin=1234
```
I found that `C_Encrypt` fails when `(input_size / 8) % 2 == 1`. The same problem exists with `C_Decrypt`.

**Comment by rgerganov** [comment]
The problem is that `encrypt_oneshot_op()` and `decrypt_oneshot_op()` in `encrypt.c` are stateful. The state in `opdata` must be cleared. I will submit a PR soon.
