### ISSUE TITLE
Documentation for doing crypto-on-TPM

### ISSUE THREAD

**Issue by dhbaird** [tpm2-software/tpm2-pkcs11#734]
Looking for clarification on the following (read through the docs, but I was unable to confirm any of this):
1. An option to guarantee that private keys can only be used on the TPM that generated the private keys. I think in TPM parlance, this means that the key should be forbidden from being unwrapped and then exported for another system to use.
2. And thus, since the secret can't be used anywhere except on that TPM, the key exchange here should be performed on-chip: `ssh-keygen -D /usr/lib/x86_64-linux-gnu/libtpm2_pkcs11.so.1 ...`? (Or, with an agent that can do crypto-on-TPM.)

Or, in other words, can tpm2-pkcs11 run in such a way that the private keys are never accessible to user space, not even in a transient sense: That it delegates all private key operations to the TPM (key generation, certificate signing, key exchanges, encryption, etc. all done on TPM). Is this already the case? Is that how it works by default? Is there any documentation that discusses this? If no to any of these, where should I actually be looking?

Thanks.

Edit: added "or with an agent that can do crypto-on-TPM."

**Comment by williamcroberts** [comment]
> Thanks @williamcroberts, with your hints from above, I was able to start reviewing code and documentation in a more focused way. If I understand correctly, the defaults in tpm2_ptool create the private keys in a way that they can never be used outside of that TPM nor transferred anywhere else, and in TPM terminology this is achieved by setting "fixedtpm" (and "fixedparent") properties on the key. And therefore, all crypto using them is necessarily done on-TPM (after transferring TPM-encrypted blobs back into the TPM). Unless there are some gotchas or nuances that you would recommend reading more about, I think this really helps a lot with answering my question and could close this issue.

That's pretty much it. If you create a key with different properties, its whatever those properties are, but the defaults are for it to never leave the TPM.

**Comment by achal1012** [comment]
Hi @williamcroberts and @dhbaird Do you folks know if an admin user can use the private key generated by tpm2_ptool in the TPM to sign some arbitrary data? I am asking this to know if we can say with surety that once an SSH key is generated on a TPM it cannot be used to make the connection from any other device than that particular one.

**Comment by williamcroberts** [comment]
> Hi @williamcroberts and @dhbaird Do you folks know if an admin user can use the private key generated by tpm2_ptool in the TPM to sign some arbitrary data?

In the pkcs11 model to use the keys you need:
1. Filesystem access to the store
2. The user or SO pin

If the admin has those two things, they can use the key in the TPM.

> I am asking this to know if we can say with surety that once an SSH key is generated on a TPM it cannot be used to make the connection from any other device than that particular one.

Short answer, yes, long answer no. In theory on Machine X, you could be connecting to another machine over SSH, say machine Y, but machine X could use the subprocess TCTI to connect to a TPM on Machine A. So the real assertion is that the key can only be used from the TPM but thiers no requirement for that TPM to be local.

```
Machine X  ------ SSH w/TPM Key ---> Machine Y
    |
  TCTI
  SSH
   |
Machine A   
     |
    TPM
```

**Comment by achal1012** [comment]
Thank you @williamcroberts! Just to confirm there is no way to enforce the locality here, is that right?

**Comment by williamcroberts** [comment]
> Thank you @williamcroberts! Just to confirm there is no way to enforce the locality here, is that right?

Yes, theirs not way on Linux to change the locality from user space, however you can't really rely on locality as a security property as it could just be spoofed. Its just a number and its originating from the untrusted side (ie not from the TPM).
