### ISSUE TITLE
How to TPM2_Import() duplicated keys so they can be used by the tpm2-pkcs11 PKCS#11 provider?

### ISSUE THREAD

**Issue by nicowilliams** [tpm2-software/tpm2-pkcs11#755]
We'd like to use PKCS#11 to use a key that was created on one TPM with a policy that allows duplication only to other TPMs in a fixed set of them, then duplicated and imported onto each of them.

The workflow of creating the policy, creating the key, and duplicating the key can be done entirely with tpm2-tools.

But how to import the duplicated keys so that tpm2-pkcs11 will see them?

I think the answer is to duplicate the key to the public key of the primary key rooting the tpm2-pkcs11 hierarchy, then manually import, load, and save the keys, then manually alter the tpm2-pkcs11 SQLite3 DB.  This should work provided the key being imported has an `emptyAuth`, except that the provider really wants every object to have any `authValue`, no?

**Comment by nicowilliams** [comment]
Separately, it would be nice to have a mode of operation where there is no database, where there is no real state outside the provider shared object / DLL itself, just PKCS#11 with some... built-in objects and authentications / policies.  Of course, PKCS#11 doesn't have any general way to deal with the richness of TPM 2.0, so that's a problem.  So, for example, suppose there was a way to _produce_ a PKCS#11 provider DLL/DSO that has a specific set of objects and code for satisfying policies and auth values, something like this:

```bash
$ # Make a new DLL / shared object that implements PKCS#11
$ # with a hard-coded set of objects:
$ tpm2-pkcs11-ptool create-provider \
        --output=my-pkcs11-provider.so \
        --token-label="foobar" \
        --tpm2-object=primary:"$template" \
        --tpm2-policy="$policy" \
        --tpm2-auth=file:"$auth_file" \
        --token-label="foobaz 2" \
        --tpm2-object=savefile:"$file" \
        ...
$ 
$ # Now use that provider in some application:
$ some-app --pkcs11-provider="${PWD}/my-pkcs11-provider.so" ...
```

Let's put it another way there is an impedance mismatch between TPM 2.0 and PKCS#11:

 - TPM 2.0 is infinitely richer than PKCS#11,
 - and PKCS#11 simply lacks enough things in its API to really map to TPM 2.0.

But at the same time, PKCS#11 is widely supported, so a way to use TPM 2.0 objects via PKCS#11 is desired.

I can see at least two possible approaches:

 - do everything via PKCS#11 and impose structure, maybe abusing token and object labels, maybe not
 - build a very custom PKCS#11 provider that knows how to load specific TPM 2.0 objects, satisfy their policies / authenticate, and use them, but can't really create new persistent objects

The common part in both of those approaches lies in _using_ the objects once they are loaded and authorized.

The hard part lies in identifying those objects and knowing what to do to be able to use them.

This project, tpm2-pkcs11, takes the first approach.  Nothing wrong with that!  I'm just thinking about what an alternative might mean.  The alternative isn't exactly great, but for some use cases it may be plenty good enough.

**Comment by nicowilliams** [comment]
Is the `link` command what I'm looking for?

**Comment by williamcroberts** [comment]
> Is the `link` command what I'm looking for?

ptool has two commandlets that could help:
link - adds a primary key created externally.
import - essentially a tpm2_import command under the hood moving it into the primary key.

So if you have some custom primary key, you would `link` it into a token and then `import` child keys.

As far as authValue goes, empty auth should be ok. You'll still have some encrypted blob there, it will be of empty.

Just be aware their is no policy support, so if you need to generate a policy session to satisfy something, that has to be done all externally.

As far as "stateless" goes, that's an interesting idea. You'd end up with an RO token.

**Comment by nicowilliams** [comment]
If you show me how to `./bootstrap`, I might send a PR for a test of importing of duplicated keys.

**Comment by williamcroberts** [comment]
in "test/integration/scripts/create_pkcs_store.sh" it uses tpm2_ptool to do an import. You should be able to hack it into there and when a test script executes your DB will be populated based on that create_pkcs_store.sh

**Comment by nicowilliams** [comment]
Yes, I see that.  But how do I build this code base?  `./bootstrap` fails for me with:

```
Generating file lists: src_vars.mk
automake: error: cannot open < aminclude_static.am: No such file or directory
autoreconf: automake failed with exit status: 1
```

**Comment by williamcroberts** [comment]
> Yes, I see that. But how do I build this code base? `./bootstrap` fails for me with:
> 
> ```
> Generating file lists: src_vars.mk
> automake: error: cannot open < aminclude_static.am: No such file or directory
> autoreconf: automake failed with exit status: 1
> ```

Do you have autoconf archive installed?

**Comment by nicowilliams** [comment]
> Do you have autoconf archive installed?

D'oh.  This is one reason I like GitHub workflows that don't use Docker: they document the build procedure!

**Comment by williamcroberts** [comment]
> > Do you have autoconf archive installed?
> 
> D'oh. This is one reason I like GitHub workflows that don't use Docker: they document the build procedure exactly and in detail!

Well their is the docs :-p

Documentation (tells you what you need):
- https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/BUILDING.md

Dockerfile (has the build prep):
- https://github.com/tpm2-software/tpm2-software-container

**Comment by nicowilliams** [comment]
Somehow I glossed over `autoconf-archive` ("I have installed autoconf...").  Thanks!
