### ISSUE TITLE
Cannot use linked certificates in firefox that contain fields marked as critical

### ISSUE THREAD

**Issue by kuhlmannmarkus** [tpm2-software/tpm2-pkcs11#757]
We have the following situation:

We generate a key in the TPM via https://github.com/google/go-attestation and generate a CSR from the key, also in Go. The CSR is used to request a certificate from an internal CA. We then use the tpm2_ptool to create the Smart Card and link the key, we export in the encrypted representation and the certificate itself. The Smart Card is then loadable via the shared object in Firefox as a security device and can be used for mutual TLS. Everything worked as expected, until we sitched to another CA that issues certificates with the keyUsage and the basicConstraints field marked as critical. We double checked that this is the only difference. We can still link this certificate to the Smart Card and can also view it in Firefox, but Firefox wont offer to use this certificate when browsing to the mTLS resource.
Is there any known issue with critical flags? We also verified that this is not an issue with Firefox itself, with preparing a certificate from the same CA with a key that is not TPM backed.
Any help would be appreciated. Also, please let me know, in case you need any more information about our process.

Thanks in advance!

**Comment by williamcroberts** [comment]
if you get the certificate out of the DB does it match what you put in? You can use objmod from tpm2_ptool to dump the certificate. Ive seen folks when it mismatches they just manually objmod the expected cert back into the db (hex encoded BER encoding).

**Comment by kuhlmannmarkus** [comment]
Thank you @williamcroberts!
After upgrading Firefox on Ubuntu from 96 to 97, the issue disappears. We can now use the certificates as expected. Icluding certificates that contain filds that are flagged as critical.
