### ISSUE TITLE
"out of memory for object contexts" using the swtpm emulator

### ISSUE THREAD

**Issue by rkgfk** [tpm2-software/tpm2-pkcs11#758]
I have set up a working swtpm emulator and try to configure the emulator to store an ssh key.
I successfully ran the `tpm2_ptool init` command. But when I try to add a token to the swtpm it fails:
```
[root@cbd4e0d71202 /]# export TPM2_PKCS11_TCTI="swtpm:port=2321"
[root@cbd4e0d71202 /]# tpm2_ptool init
action: Created
id: 1

[root@cbd4e0d71202 /]# tpm2_ptool addtoken --pid=1 --label=my-ssh-token --sopin=[....] --userpin=[....]
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/command.py", line 102, in init
    commandlet.get()[d['which']](d)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/commandlets_token.py", line 313, in __call__
    AddTokenCommand.do_token_init(db, path, args)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/commandlets_token.py", line 254, in do_token_init
    usersealpriv, usersealpub, _ = tpm2.create(
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2.py", line 226, in create
    raise RuntimeError("Could not execute tpm2_create: %s" %
RuntimeError: Could not execute tpm2_create: b'WARNING:esys:src/tss2-esys/api/Esys_Create.c:398:Esys_Create_Finish() Received TPM Error \nERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x00000902) \nERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts\nERROR: Unable to run tpm2_create\n'
```
I run the environment in a Fedora 35 docker container. The swtpm is running in the same container in different shell.

**Comment by williamcroberts** [comment]
pkcs11 assumes you're running a resource manager, are you running tpm2-abrmd?

**Comment by rkgfk** [comment]
Same problem like in [this issue](https://github.com/tpm2-software/tpm2-tools/issues/2960). I am running the `swtpm` and the `tpm2_ptool` inside a docker container. So no chance to get tpm2-abrmd running due to the missing dbus. So what now?

**Comment by williamcroberts** [comment]
> Same problem like in [this issue](https://github.com/tpm2-software/tpm2-tools/issues/2960). I am running the `swtpm` and the `tpm2_ptool` inside a docker container. So no chance to get tpm2-abrmd running due to the missing dbus. So what now?

See this: ./tools/tpm2 getrandom --tcti=tabrmd:bus_type=session --hex 4
7e0a8e03

**Comment by williamcroberts** [comment]
> Same problem like in [this issue](https://github.com/tpm2-software/tpm2-tools/issues/2960). I am running the `swtpm` and the `tpm2_ptool` inside a docker container. So no chance to get tpm2-abrmd running due to the missing dbus. So what now?

See the example on the thread under tpm2-tools: https://github.com/tpm2-software/tpm2-tools/issues/2960

**Comment by williamcroberts** [comment]
Closing stale.
