### ISSUE TITLE
Using the smart card in Chrome fails when accessing mTLS resource - Handshake failed

### ISSUE THREAD

**Issue by kuhlmannmarkus** [tpm2-software/tpm2-pkcs11#759]
We are successfully using the PKCS11 smart card in firefox. We then attempted to add the token to the NSS database via `modutil -dbdir sql:.pki/nssdb/ -add "token" -libfile /some_path/libtpm2_pkcs11.so.0.0.0`. Chrome then prompts with the certificate when accessing the mTLS resource, but the handshake fails. The following is the shell output with debugging level 2 (I removed most INFO messages). Any help is appreciated. Please let me know if you require more information on the situation.

`ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied`
`ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so`
`[154669:154669:0304/104524.541011:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization`
`ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied`
`ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so`
`[154763:154763:0304/104524.602844:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.`
`WARNING:fapi:src/tss2-fapi/api/Fapi_List.c:226:Fapi_List_Finish() Profile of path not provisioned: /HS/SRK`
`ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List`
`WARNING on line: "36" in file: "src/lib/backend_fapi.c": Listing FAPI token objects failed: "fapi:Provisioning was not executed."
Please see https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/FAPI.md for more details`
`WARNING on line: "198" in file: "src/lib/backend.c": Getting tokens from fapi backend failed.`
`ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied`
`ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so`
`INFO on line: "604" in file: "src/lib/token.c": Incremented tobject id: 1, value: 2`
`INFO on line: "2186" in file: "src/lib/tpm.c": Performing TPM RSA Decrypt`
`WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error`
`ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000182)`
`ERROR on line: "2226" in file: "src/lib/tpm.c": Esys_RSA_Decrypt: tpm:handle(1):inconsistent attributes`
`[154560:154832:0304/104544.748822:ERROR:ssl_platform_key_nss.cc(45)] PK11_SignWithMechanism failed: -8025 (SEC_ERROR_PKCS11_GENERAL_ERROR)`
`[154604:154619:0304/104544.749147:ERROR:ssl_client_socket_impl.cc(995)] handshake failed; returned -1, SSL error code 1, net_error -141`

**Comment by williamcroberts** [comment]
The FAPI messages you can ignore, but the " Could not initialize TCTI" errors are likely you're culprit. I have 0 knowledge of this NSS database, but is the process that is loading the pkcs11 module have the right permissions? Are you expecting the token to connect over tpm2-abrmd, /dev/tpmrm0 or /dev/tpm0 (which would be broken, you must run pkcs11 with a resource manager).

**Comment by kuhlmannmarkus** [comment]
Hi William,
thanks for your reply!
When using firefox, we see pretty much the same set of errors (exept the RSA decrypt failure) and everything works just fine. Below you can find the pkcs11 debug output when using firefox:

`ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied`
`ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so`
`ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied`
`ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so`
`WARNING:fapi:src/tss2-fapi/api/Fapi_List.c:226:Fapi_List_Finish() Profile of path not provisioned: /HS/SRK`
`ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List`
`WARNING on line: "36" in file: "src/lib/backend_fapi.c": Listing FAPI token objects failed: "fapi:Provisioning was not executed."
Please see https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/FAPI.md for more details`
`WARNING on line: "198" in file: "src/lib/backend.c": Getting tokens from fapi backend failed.`
`ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied`
`ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-default.so`

The user launching chrome is the same launching firefox and is member of the tss group, so I guess the permissions should be fine. Im not entirely sure whether we are using the abrmd correctly, but it is installed and seems to work. Is there any method to determine what the library actually attempts to open? We still have no clue whats wrong here. This might even be an issue with chrome and not tpm2-pkcs11, but I thought I have seen successful attempts using chrome. Any help is highly appreciated.

**Comment by williamcroberts** [comment]
Does it work using the token not in chrome (ie from p11-tool, openssl pkcs11 engine or pkcs11-tool)? If so how you set the location of the store (sqlite3 database)? Is their anyway you can bump up the log level via env variable `TPM2_PKCS11_LOG_LEVEL` set to 2?

**Comment by Kuenni** [comment]
Hi @williamcroberts, 

I'm jumping in here as Markus' co-worker.

I can use the token via OpenSSL on the same target page. After setting the module path to 
`export PKCS11_MODULE_PATH=/home/user/libtpm2_pkcs11.so.0.0.0`
I can create a GET request and receive the expected HTML page

`(echo -e "GET / HTTP/1.1\r\nHost: target.url\r\n\r\n"; sleep 10) | openssl s_client -keyform engine -engine pkcs11  -key "pkcs11:model=SLB9670%20FIPS%00%00%00%00;manufacturer=Infineon;serial=0000000000000000;token=karltoken;id=%63%34%31%37%32%33%39%31%35%37%31%62%63%30%37%62;object=link-key;type=cert;pin-value=myuserpin"  -connect target.url:443 -debug -msg  -state -cert cert.pem `

I set the libfile location in the modutil tool to the same location as above (`/home/user/libtpm2_pkcs11.so.0.0.0`)
the output of modutil list gives me that library name back. 

This is the output from the crash with `TPM2_PKCS11_LOG_LEVEL` set to 2.

```
INFO on line: "481" in file: "src/pkcs11.c": return "C_GetAttributeValue" value: 0
INFO on line: "557" in file: "src/pkcs11.c": enter "C_Sign"
INFO on line: "136" in file: "src/lib/encrypt.c": mechanism->mechanism: 3
mechanism->ulParameterLen: 0
mechanism->pParameter: (null)
INFO on line: "604" in file: "src/lib/token.c": Incremented tobject id: 1, value: 2
INFO on line: "2186" in file: "src/lib/tpm.c": Performing TPM RSA Decrypt
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000182) 
ERROR on line: "2226" in file: "src/lib/tpm.c": Esys_RSA_Decrypt: tpm:handle(1):inconsistent attributes
INFO on line: "514" in file: "src/lib/sign.c": Decremented tobject id: 1, value: 1
INFO on line: "557" in file: "src/pkcs11.c": return "C_Sign" value: 5
INFO on line: "437" in file: "src/pkcs11.c": enter "C_CloseSession"
INFO on line: "437" in file: "src/pkcs11.c": return "C_CloseSession" value: 0
[224440:224717:0311/072840.120006:ERROR:ssl_platform_key_nss.cc(45)] PK11_SignWithMechanism failed: -8025 (SEC_ERROR_PKCS11_GENERAL_ERROR)
[224484:224502:0311/072840.120366:ERROR:ssl_client_socket_impl.cc(995)] handshake failed; returned -1, SSL error code 1, net_error -141
Fontconfig error: Cannot load default config file: No such file: (null)
```

**Comment by Kuenni** [comment]
Thought it might be helpful to add a diff of the log output for working firefox/openssl (lines removed) and not working chrome (lines added).
First thing that jumps to my eye is the mechanism in sign.c.

```diff
4,6c4,6
< INFO on line: "156" in file: "src/lib/sign.c": mechanism: 0xd
<       has_params: yes
<       len: 24
---
> INFO on line: "156" in file: "src/lib/sign.c": mechanism: 0x1
>       has_params: no
>       len: 0
14,15c14,25
< INFO on line: "514" in file: "src/lib/sign.c": Decremented tobject id: 1, value: 0
< INFO on line: "557" in file: "src/pkcs11.c": return "C_Sign" value: 0
---
> INFO on line: "136" in file: "src/lib/encrypt.c": mechanism->mechanism: 3
> mechanism->ulParameterLen: 0
> mechanism->pParameter: (null)
> INFO on line: "604" in file: "src/lib/token.c": Incremented tobject id: 1, value: 2
> INFO on line: "2186" in file: "src/lib/tpm.c": Performing TPM RSA Decrypt
> INFO on line: "445" in file: "src/pkcs11.c": enter "C_GetSessionInfo"
> INFO on line: "445" in file: "src/pkcs11.c": return "C_GetSessionInfo" value: 0
> WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error
> ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000182)
> ERROR on line: "2226" in file: "src/lib/tpm.c": Esys_RSA_Decrypt: tpm:handle(1):inconsistent attributes
> INFO on line: "514" in file: "src/lib/sign.c": Decremented tobject id: 1, value: 1
> INFO on line: "557" in file: "src/pkcs11.c": return "C_Sign" value: 5
18,19c28,30
< INFO on line: "445" in file: "src/pkcs11.c": enter "C_GetSessionInfo"
< INFO on line: "445" in file: "src/pkcs11.c": return "C_GetSessionInfo" value: 0
\ No newline at end of file
---
> [226244:226496:0311/074713.831791:ERROR:ssl_platform_key_nss.cc(45)] PK11_SignWithMechanism failed: -8025 (SEC_ERROR_PKCS11_GENERAL_ERROR)
> [226286:226297:0311/074713.832204:ERROR:ssl_client_socket_impl.cc(995)] handshake failed; returned -1, SSL error code 1, net_error -141
> Fontconfig error: Cannot load default config file: No such file: (null)
```

**Comment by williamcroberts** [comment]
In the working case it's using CKM_RSA_PKCS (pkcs v1.5 padding)  and in the failing case it's using CKM_RSA_X_509 (raw rsa). So the key's attributes likely do not have decrypt set according to "https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf".

How did this key get generated and added to the token? Is their anyway you can get the public blob and print out the attributes?

Once you find the object id using listobjects/listtokens in tpm2_ptool, you can use objmod to dump the blob:
```bash
tpm2_ptool objmod --id=12 --key=2399141890 --path=~/tmp | cut -d ' ' -f2- | xxd -r -p > pub.blob
```

and tpm2_print to dump the public object information:
```bash
tpm2_print -t TPM2B_PUBLIC pub.blob 
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign
  raw: 0x60072
type:
  value: ecc
  raw: 0x23
curve-id:
  value: NIST p256
  raw: 0x3
kdfa-alg:
  value: null
  raw: 0x10
kdfa-halg:
  value: (null)
  raw: 0x0
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
x: 9911902cca506b717f8af6f50c50b7d9cf2c8538ba4585f9bc4cfa9b5fea4ecc
y: 618914b7879d6e84cbf9358597b7f1c0fa0c5d043cda707323996911d85b1795
```

**Comment by kuhlmannmarkus** [comment]
Hi @williamcroberts ,
first of all, sorry for the huge delay. We had freeze our environment for some demonstrations and could not continue to analyze this issue.
You were right: Our key does not have the "decrypt" attribute. We are generating the key with the help of this package: https://github.com/google/go-attestation
We are simply calling the "NewKey" function. I will try to get in contact with the developers and then get back to you.
Therefore this does not seem to be an issue with the pkcs11 library. Closing...

**Comment by williamcroberts** [comment]
> Hi @williamcroberts , first of all, sorry for the huge delay. We had freeze our environment for some demonstrations and could not continue to analyze this issue. You were right: Our key does not have the "decrypt" attribute. We are generating the key with the help of this package: https://github.com/google/go-attestation We are simply calling the "NewKey" function. I will try to get in contact with the developers and then get back to you. Therefore this does not seem to be an issue with the pkcs11 library. Closing...

Looks like you set an options, perhaps in those options you can set the decrypt attribute:
// NewKey creates an application key certified by the attestation key. If opts is nil
// then DefaultConfig is used.
func (t *TPM) NewKey(ak *AK, opts *KeyConfig) (*Key, error) {
	if opts == nil {
		opts = defaultConfig
	}
	if opts.Algorithm == "" && opts.Size == 0 {
		opts = defaultConfig
	}
	return t.tpm.newKey(ak, opts)
}

**Comment by hoxnox** [comment]
I'm trying to use chrome and firefox to access resources with mTLS. Where can I read any info - how to do it?

**Comment by williamcroberts** [comment]
> I'm trying to use chrome and firefox to access resources with mTLS. Where can I read any info - how to do it?

No idea, I would ask the Chrome or Firefox folks for information.
