### ISSUE TITLE
BUILDING.md: Inconsistent openssl version requirement

### ISSUE THREAD

**Issue by gotthardp** [tpm2-software/tpm2-pkcs11#762]
It seems that this is no longer correct:
https://github.com/tpm2-software/tpm2-pkcs11/blob/4b96a36701d508822519b43c9078acc8117462fc/docs/BUILDING.md?plain=1#L20

Because `configure.ac` says
https://github.com/tpm2-software/tpm2-pkcs11/blob/4b96a36701d508822519b43c9078acc8117462fc/configure.ac#L40

**Comment by williamcroberts** [comment]
This was fixed in 1.8.0 in commit 148847c79eda6. Closing.
