### ISSUE TITLE
Make fails with "missing separator"

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#77]
```
./bootstrap  -I /usr/share/gnulib/m4
./configure
make
Makefile:2059: *** missing separator.  Schluss.
```
The corresponding line in the makefile is
`@CODE_COVERAGE_RULES@`

Tested on raspberry pi with raspbian.
It used to work somehow (with the old m4 macros?)

**Comment by williamcroberts** [comment]
Weird. How are you satisfying the dependency?

is it perhaps pulling in a mix of autoconf-archive macros between system installed and local?

**Comment by PeterHuewe** [comment]
Yes totally weird - meanwhile it went away on my working copy.
It did occur on a freshly cloned copy of master.
I think we can close it ?

**Comment by williamcroberts** [comment]
Iv'e seen weird issues if you sigint autoconf....

I use:
```
git clean -fdx
```
Frequently, but be careful you don't rm something you want.
