### ISSUE TITLE
tpm2 pkcs11 C_InitToken fails to use password from TPM2_PKCS11_OWNER_AUTH variable

### ISSUE THREAD

**Issue by pchand20** [tpm2-software/tpm2-pkcs11#777]
Hi There,
 with export TPM2_PKCS11_OWNER_AUTH=<value> seems C_ apis are not taking this value properly. while this works in tpm2_ptool. 
before calling C_InitToken then env is printing as expected, but as it is still failing, seems its a bug. 

printf("TPM2_PKCS11_OWNER_AUTH: %s\n", getenv("TPM2_PKCS11_OWNER_AUTH"));
CK_RV rv = C_InitToken(request->slot_id(), pin, request->pin_len(), label);

C_GetSlotList() called
C_GetSlotList() called
C_GetMechanismInfo() called
C_GetMechanismInfo() called
C_GetTokenInfo() called
C_InitToken() called
TPM2_PKCS11_OWNER_AUTH: newpass
WARNING:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error
ERROR:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2)
ERROR: Esys_CreatePrimary: tpm:session(1):authorization failure without DA implications:
ERROR: Could not find nor create a primary object
ERROR: Could not create new token
C_Finalize() called

getenv("TPM2_PKCS11_OWNER_AUTH")) is returning correct password

**Comment by elliotmtx** [comment]
I have verified and this issue is fixed with PR [https://github.com/tpm2-software/tpm2-pkcs11/pull/776](url)
