### ISSUE TITLE
Segfault / Sigbus with OASIS headers on raspberry pi

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#78]
With the introduction of #72 tpm2-pkcs11 fails for me on the raspberry pi3.
I get either a segfault or a SIGBUS on C_Initialize.
I cannot really debug it at the moment.
If I revert the change it works again.

**Comment by williamcroberts** [comment]
> -----Original Message-----
> From: Peter Huewe [mailto:notifications@github.com]
> Sent: Thursday, November 15, 2018 6:51 AM
> To: tpm2-software/tpm2-pkcs11 <tpm2-pkcs11@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [tpm2-software/tpm2-pkcs11] Segfault / Sigbus with OASIS headers on
> raspberry pi (#78)
> 
> With the introduction of #72 <https://github.com/tpm2-software/tpm2-
> pkcs11/pull/72>  tpm2-pkcs11 fails for me on the raspberry pi3.
> I get either a segfault or a SIGBUS on C_Initialize.
> I cannot really debug it at the moment.
> If I revert the change it works again.

I wonder if something with structure packing is not working right.
Let me see if I can replicate this.

**Comment by williamcroberts** [comment]
```
$ p11-kit list-modules
p11-kit: couldn't load module: /usr/local/lib/softhsm/libsofthsm2.so: /usr/local/lib/softhsm/libsofthsm2.so: file too short
Segmentation fault (core dumped)
```
Looking into it.

**Comment by williamcroberts** [comment]
Sizes of structures changed (this isn't exhaustive)
```
New
CK_TOKEN_INFO: 204
CK_SESSION_INFO: 32
CK_ATTRIBUTE: 24
CK_DATE: 8
CK_MECHANISM: 24
CK_MECHANISM_INFO: 24
CK_C_INITIALIZE_ARGS: 48

Old
CK_TOKEN_INFO: 208
CK_SESSION_INFO: 32
CK_ATTRIBUTE: 24
CK_DATE: 8
CK_MECHANISM: 24
CK_MECHANISM_INFO: 24
CK_C_INITIALIZE_ARGS: 48
```

**Comment by PeterHuewe** [comment]
Thanks for looking into it - I appreciate it.
Because of the bus error (which was the first one I ever saw) I guess it might have to do with alignment/packing - but strange nevertheless.

**Comment by williamcroberts** [comment]
@PeterHuewe What's weird is that it shrunk without a structure definition change, and the spec says pack to alignment 1 ie __attribute__((packed)). I have no idea why it changed yet. I would imagine shrinking versus not shrinking indicates proper packing. I added them up by hand and get 204:
```
typedef struct CK_TOKEN_INFO {
  /* label, manufacturerID, and model have been changed from
   * CK_CHAR to CK_UTF8CHAR for v2.10 */
  CK_UTF8CHAR   label[32];           /* blank padded */
  CK_UTF8CHAR   manufacturerID[32];  /* blank padded */
  CK_UTF8CHAR   model[16];           /* blank padded */
  CK_CHAR       serialNumber[16];    /* blank padded */
  CK_FLAGS      flags;               /* see below */

  CK_ULONG      ulMaxSessionCount;     /* max open sessions */
  CK_ULONG      ulSessionCount;        /* sess. now open */
  CK_ULONG      ulMaxRwSessionCount;   /* max R/W sessions */
  CK_ULONG      ulRwSessionCount;      /* R/W sess. now open */
  CK_ULONG      ulMaxPinLen;           /* in bytes */
  CK_ULONG      ulMinPinLen;           /* in bytes */
  CK_ULONG      ulTotalPublicMemory;   /* in bytes */
  CK_ULONG      ulFreePublicMemory;    /* in bytes */
  CK_ULONG      ulTotalPrivateMemory;  /* in bytes */
  CK_ULONG      ulFreePrivateMemory;   /* in bytes */
  CK_VERSION    hardwareVersion;       /* version of hardware */
  CK_VERSION    firmwareVersion;       /* version of firmware */
  CK_CHAR       utcTime[16];           /* time */
} CK_TOKEN_INFO;

// 32+32+16+16+8+8+8+8+8+8+8+8+8+8+8+2+2+16=204
```
Weird...
