### ISSUE TITLE
Deadlock on logout

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#79]
I'm not sure why it doesn't trigger in the test,
but I get a deadlock on logout.

I already looked into it and 
the problem is session_ctx_logout tries to lock a ctx, which is already held via the session_table_lookup and then fails at
session_ctx_lock(tok->login_session_ctx);

I'll look up the steps to reproduce when I find some time :/

**Comment by williamcroberts** [comment]
the testing code isn't using locks, all the lock calls are NOPs at the moment.
