### ISSUE TITLE
Superfluous `WARNING: Getting tokens from fapi backend failed.`

### ISSUE THREAD

**Issue by JanPokorny** [tpm2-software/tpm2-pkcs11#792]
I have set-up according to this article: https://blog.ledger.com/ssh-with-tpm/

When using the key with SSH, an error is printed:

```
~                                                                                                                             
❯ ssh -T git@github.com
WARNING: Getting tokens from fapi backend failed.
Hi JanPokorny! You've successfully authenticated, but GitHub does not provide shell access.
```

Since everything works, and I did not do anything with "fapi" (not even sure what it is), I don't think this warning should be showing in this case.

**Workaround**: It can be disabled with env var `TPM2_PKCS11_LOG_LEVEL=0`

**Comment by monperrus** [comment]
I confirm the superfluous warning and that the workaround `TPM2_PKCS11_LOG_LEVEL=0` works
