### ISSUE TITLE
Add Design Documents

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#8]
Add design documents and diagrams.

**Comment by PeterHuewe** [comment]
Would be good to have more information on the objects, TPM keys and their types and attributes.

**Comment by williamcroberts** [comment]
Fixed in #265, however it needs an update to remove secondary object and wrapping object.

**Comment by williamcroberts** [comment]
so docs/ARCHITECTURE.md is gone, so now we have @idesai doc:
https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/tpm2-pkcs11_object_auth_model.md

Which is very close to correct. @idesai the wrapping object is gone, we just use a sealed AES key. So all wrapping/unwrapping occurs within library, not TPM. Since we release a secret, that is either the key or a password to a key, might as well just release a key, it doesn't change the attack.

@idesai can you update your doc when you get a chance?

**Comment by williamcroberts** [comment]
https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/ARCHITECTURE.md
