### ISSUE TITLE
Signing with multiple sessions does not work

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-pkcs11#80]
If I create two sessions,
login to the first one
and try to sign with the second one,
it fails with some esys error.

**Comment by williamcroberts** [comment]
What's the sys error?

**Comment by williamcroberts** [comment]
Do you have: https://github.com/tpm2-software/tpm2-pkcs11/commit/ea0b25d1cf8fbe52d99e49ca51f343fbd69c090f

in tree?

**Comment by PeterHuewe** [comment]
Okay, maybe I have to close this for now, sorry.
It was because of my local fix for #81
