### ISSUE TITLE
win11 support

### ISSUE THREAD

**Issue by heapxor** [tpm2-software/tpm2-pkcs11#801]
hello,
is there support for win11?  or some alternative?

Also is it possible setup whole thing in linux guest running on vmware player pro (host) win11?

thanks!

**Comment by williamcroberts** [comment]
> hello, is there support for win11? 

No, but I also never tried to see if it works.

> or some alternative?

Like a different version of Windows? If so, same answer, no official support but I never tried to see if it works.

> 
> Also is it possible setup whole thing in linux guest running on vmware player pro (host) win11?

Yes. I know with KVM you can pass the TPM device to the guest, I would imagine VMWare and others have similar support.

> 
> thanks!

**Comment by heapxor** [comment]
@williamcroberts 
oh i see, so basically there is no way to use TPM for storing ssh keys on windows11? thanks!

**Comment by niooss-ledger** [comment]
For information, Microsoft implemented on Windows a few years ago a mechanism to do exactly what tpm2-pkcs11 does on Linux: it is called "Virtual Smart Cards" and provides the ability to create a PKCS#11 virtual device using secrets stored in the TPM. It is documented on https://learn.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started

I've already seen this used for HTTPS and Kerberos user authentication. I don't know whether OpenSSH supports Virtual Smart Cards on Windows, but if it supports PKCS#11 there, it could support VSC too.
