### ISSUE TITLE
configure --with-fapi outdated tag 

### ISSUE THREAD

**Issue by l-sousa** [tpm2-software/tpm2-pkcs11#822]
The ./configure --with-fapi tag is outdated on the FAPI documentation and is present in the configure help.

**Comment by williamcroberts** [comment]
> The ./configure --with-fapi tag is outdated on the FAPI documentation and is present in the configure help.

The enable/disable fapi flag during configure for the tpm2-tss project is different than the flag used by the tpm2-pkcs11 project. In tpm2-tss, it is used to enable or disable the build of the FAPI library aka libtss2-fapi. Within tpm2-pkcs11 project its used as a way to disable the FAPI backend. When including or excluding certain packages the convention is to use `--with-pkgname`, see https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/External-Software.html.

Also, downstream packagers relying on this behavior would be broken.

For those two reasons, I don't want to take this change.
