### ISSUE TITLE
Keys still functional after SRK evicted

### ISSUE THREAD

**Issue by sandevins** [tpm2-software/tpm2-pkcs11#827]
I am trying to invalidate key pairs created with tpm2_ptool. As far as I know, the SRK is needed to decrypt the child keys created with tpm2_ptool.

I created the store and token with the following commands.

```
tpm2_ptool init --hierarchy-auth ownerauth --primary-handle 0x81000001
tpm2_ptool addtoken --pid=1 --sopin=mysopin --userpin=myuserpin --label=label_1
```

This means that the primary object is stored in `0x81000001`. I then create a key pair with the following.

`tpm2_ptool addkey --key-label "myrsakeypair" --label "label_1" --algorithm rsa2048 --sopin "mysopin"`

I then test the keys using `p11tool`. The result is the following.

```
Enter PIN: 
Signing using RSA-SHA256... ok
Verifying against private key parameters... ok
Verifying against public key in the token... ok
```

Then I try to change the SRK.

```
tpm2_createprimary -C o -c prim.ctx -P ownerauth
tpm2_evictcontrol -C o -c prim.ctx -P ownerauth 0x81000001
tpm2_flushcontext -t
```

After that I test the keys again, and the test works again.

```
Enter PIN: 
Signing using RSA-SHA256... ok
Verifying against private key parameters... ok
Verifying against public key in the token... ok
```

Am I missing something?

**Comment by PeterVagany** [comment]
The seed used to generate the SRK is persistent (until cleared).
See section 14.3.4 of https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf

**Comment by sandevins** [comment]
Yes, but after changing the Primary Key (not the seed) stored in 0x81000001 the child keys (created using tpm2_ptool) should be invalid (as far as I know).

**Comment by PeterVagany** [comment]
I think you are not really changing the primary key if you run the same commands, but regenerating and restoring it.

24.1 TPM2_CreatePrimary [TCG_TPM2_r1p59_Part3_Commands_pub](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf)
>If this command is called multiple times with the same inPublic parameter, inSensitive.data, and Primary
Seed, the TPM shall produce the same Primary Object.

You can verify this by comparing the public output of two tpm2_createprimary runs (stdout or --output file argument).

**Comment by sandevins** [comment]
I missed that part, as I forgot that the KDF used to create primary objects was deterministic.

Thank you very much for your help, I think this closes the issue.
