### ISSUE TITLE
Github code signing using SSH keys stored in tpm

### ISSUE THREAD

**Issue by shafr** [tpm2-software/tpm2-pkcs11#848]
Hi there.

I'm not able to find correct way how to specify which key should be used for code signing in .git config when using tpm2-software.
For SSH login it's described as:
```
Host github.com
  HostName github.com
  User git
  PKCS11Provider /usr/lib/x86_64-linux-gnu/libtpm2_pkcs11.so.1
  ForwardAgent yes
  PasswordAuthentication no
```

but not for code signing, it's not clear what should I put there:
```
[user]
	signingkey = ?
```

**Comment by rally-dimi** [comment]
So apparenlty github uses `public` key, so it's enough just to store result of 
```
ssh-keygen -D /usr/lib/x86_64-linux-gnu/libtpm2_pkcs11.so.1
```
somewhere and point to that file.
