### ISSUE TITLE
C_GenerateKeyPair

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#90]
Support RSA and ECC Keypair generation

**Comment by williamcroberts** [comment]
Start with CKA_TOKEN=true

**Comment by PeterHuewe** [comment]
If you already have a work in progress to share, that would be appreciated :)

**Comment by williamcroberts** [comment]
It's not very far along, hoping to make some more progress today:
https://github.com/williamcroberts/tpm2-pkcs11/tree/gen-rsa-key

**Comment by williamcroberts** [comment]
Update p11tool --generate-rsa is working.
**Note**: I haven't done any memory testing, so their could be corruption issues that will cause it not to run correctly on another machine, especially without -g. I'll be working on this part tomorrow and getting cleanups in.
```
GNUTLS_PIN=myuserpin /home/wcrobert/workspace/gnutls/src/.libs/p11tool --login --generate-rsa --bits=2048 --no-mark-private --label=p11kit pkcs11:model=TPM2%20PKCS%2311;manufacturer=Intel;serial=0000000000000000;token=label
```

**Comment by PeterHuewe** [comment]
I will give it a testrun tomorrow :)
Thanks for updating this!

**Comment by PeterHuewe** [comment]
Compiling 838ccd52b5b2ca1472bff545746d5c58fb357a55 fails for me:
```
src/lib/key.c: In function ‘rsa_add_missing_attrs’:
src/lib/key.c:109:18: error: pointer targets in passing argument 1 of ‘snprintf’ differ in signedness [-Werror=pointer-sign]
         snprintf(tmp, sizeof(tmp), "%u", tobj->id);
                  ^~~
In file included from /usr/include/openssl/bn.h:29:0,
                 from src/lib/key.c:6:
/usr/include/stdio.h:388:12: note: expected ‘char * restrict’ but argument is of type ‘CK_BYTE * {aka unsigned char *}’
 extern int snprintf (char *__restrict __s, size_t __maxlen,
            ^~~~~~~~
src/lib/session_ctx.c: In function ‘token_load_object’:
src/lib/key.c:110:30: error: pointer targets in passing argument 1 of ‘strlen’ differ in signedness [-Werror=pointer-sign]
         ADD_ATTR_STR(CKA_ID, tmp, newattrs, index);
                              ^
src/lib/key.c:35:42: note: in definition of macro ‘ADD_ATTR_STR’
     newattrs[offset].ulValueLen = strlen(V);        \
In file included from src/lib/utils.h:12:0,
                 from src/lib/object.h:15,
                 from src/lib/token.h:10,
                 from src/lib/db.h:12,
                 from src/lib/key.c:10:
/usr/include/string.h:394:15: note: expected ‘const char *’ but argument is of type ‘CK_BYTE * {aka unsigned char *}’
 extern size_t strlen (const char *__s)
               ^~~~~~
src/lib/key.c:110:30: error: pointer targets in passing argument 1 of ‘strdup’ differ in signedness [-Werror=pointer-sign]
         ADD_ATTR_STR(CKA_ID, tmp, newattrs, index);
                              ^
src/lib/key.c:36:38: note: in definition of macro ‘ADD_ATTR_STR’
     newattrs[offset].pValue = strdup(V);            \
                                      ^
In file included from src/lib/utils.h:12:0,
                 from src/lib/object.h:15,
                 from src/lib/token.h:10,
                 from src/lib/db.h:12,
                 from src/lib/key.c:10:
/usr/include/string.h:171:14: note: expected ‘const char *’ but argument is of type ‘CK_BYTE * {aka unsigned char *}’
 extern char *strdup (const char *__s)
              ^~~~~~
src/lib/session_ctx.c:154:25: error: unused variable ‘wobj’ [-Werror=unused-variable]
         wrappingobject *wobj = &tok->wrappingobject;
                         ^~~~
src/lib/utils.c: In function ‘utils_ctx_wrap_objauth’:
src/lib/utils.c:559:33: error: pointer targets in passing argument 1 of ‘twist_hex_new’ differ in signedness [-Werror=pointer-sign]
         wrapped = twist_hex_new(xtext, xtextlen);
                                 ^~~~~
In file included from src/lib/object.h:14:0,
                 from src/lib/token.h:10,
                 from src/lib/utils.c:13:
src/lib/twist.h:287:7: note: expected ‘const char *’ but argument is of type ‘CK_BYTE * {aka unsigned char *}’
 twist twist_hex_new(const char *data, size_t len);
       ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:1213: die Regel für Ziel „src/lib/session_ctx.lo“ scheiterte
make: *** [src/lib/session_ctx.lo] Fehler 1
make: *** Es wird auf noch nicht beendete Prozesse gewartet...
cc1: all warnings being treated as errors
src/lib/db.c: In function ‘attr_generic_hex_handler’:
src/lib/db.c:1318:15: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (bytes >= len) {
               ^~
Makefile:1213: die Regel für Ziel „src/lib/key.lo“ scheiterte
make: *** [src/lib/key.lo] Fehler 1
cc1: all warnings being treated as errors
Makefile:1213: die Regel für Ziel „src/lib/utils.lo“ scheiterte
make: *** [src/lib/utils.lo] Fehler 1
src/lib/tpm.c: In function ‘tpm2_generate_key’:
src/lib/tpm.c:2111:14: error: unused variable ‘is_pub’ [-Werror=unused-variable]
         bool is_pub = i == 1;
```

**Comment by PeterHuewe** [comment]
I added some comments in your commits.
I can confirm that it creates a key using your example (and other tools) and bascially works, but the label and other attributes do not get stored correctly in the database.

generated with p11tool:
```
Data object 6
  label:          <empty>
  application:    <empty>
  app_id:         <empty>
  flags:          <empty>
```

vs: 
generated with tpm2_ptool:

```
Private Key Object; RSA 
  label:      test5
  ID:         33623532643531633236353561373135
  Usage:      none
```

**Comment by williamcroberts** [comment]
Fix:
- [ ] exponent serialization code, see: https://github.com/williamcroberts/tpm2-pkcs11/commit/838ccd52b5b2ca1472bff545746d5c58fb357a55#r32468678
- [ ] storage of attributes to db

**Comment by williamcroberts** [comment]
@PeterHuewe You had a few attributes you needed supported, can you list them here?

I updated that branch fixing a bunch of issues you pointed out, but I still need to:
1. add tests for RSA generation
2. add tests that verify a signature done in the TPM with public key constructed from the relevant attributes like CKA_MODULUS and CKA_EXPONENT, for example.

**Comment by PeterHuewe** [comment]
CKA_CLASS and CKA_EXTRACTABLE

**Comment by williamcroberts** [comment]
`CKA_CLASS` should be supported, no?
I do see a bug where I check if CKA_CLASS is present and if so that someone sent in the `CKA_CLASS: CKA_PRIVATE` and `CKA_CLASS : CKA_PUBLIC`. I need to check both of those
more specifically.

`CKA_EXTRACTABLE` looks like that has an inverse relationship with `CKA_SENSITIVE` and it will require me to turn down the `TPMA_FIXEDPARENT` and `TPMA_FIXEDTPM` flags when set.

However, the plumbing to actually pill it out through the PKCS#11 API is not on my short list of features to add, so it would have to be done manually running the tpm_duplicate command (commandline tool not available at the moment)

**Comment by PeterHuewe** [comment]
Hi,
I did have an issue if the cka_class is specified in the template.

About cka_extractable in template
I'm okay if that is fixed to false.
But the provider should not fail if that flag is specified.

**Comment by williamcroberts** [comment]
> Hi,
> I did have an issue if the cka_class is specified in the template.
> 
> About cka_extractable in template
> I'm okay if that is fixed to false.
> But the provider should not fail if that flag is specified.

Roger ill add these in. Ill have it turn down those flags in the TPM, seems pretty simple to at least add basic support so you have a way to dup it if needed. Thanks for running these for me, your feedback has been well received and appreciated.
