### ISSUE TITLE
coveralls: fix status

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#93]
Travis is uploading builds to coveralls, but the coveralls UI isn't updating with the most recent builds. In fact it only shows the first build.
- travis job (Nov 27 2018): https://travis-ci.org/tpm2-software/tpm2-pkcs11/jobs/460507260
- coveralls: https://coveralls.io/github/tpm2-software/tpm2-pkcs11?branch=master

**Comment by williamcroberts** [comment]
I clicked some refresh buttons and regenreated the coveralls token and re-configured travis. I then started a build to see if this will cause it to update to build 2:
  - https://travis-ci.org/tpm2-software/tpm2-pkcs11/builds/460831721

**Comment by williamcroberts** [comment]
It's seeing the builds: https://coveralls.io/jobs/42668244

But it's not populating the last build or the build count.

**Comment by PeterHuewe** [comment]
Maybe consider switching to codecov.io?
We had the same issues in the tpm2-tss a while ago.

**Comment by williamcroberts** [comment]
https://github.com/tpm2-software/tpm2-pkcs11/pull/154
